-- Script de inserção dos produtos mapeados

INSERT INTO public.products (name, price, category, description, image) VALUES
('Real Madrid 22/23 - Titular', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 22/23. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (1).png'),
('Flamengo Retrô Lubrax - Titular', 109.9, 'Brasileirão', 'Manto premium do Flamengo, temporada Retrô Lubrax. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (2).png'),
('Flamengo Retrô Manga Longa - Titular', 109.9, 'Brasileirão', 'Manto premium do Flamengo, temporada Retrô Manga Longa. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (3).png'),
('Chelsea 12/13 - Titular', 109.9, 'Premier League', 'Manto premium do Chelsea, temporada 12/13. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (4).png'),
('Real Madrid 21/22 - Titular (Benzema 9)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 21/22. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (5).png'),
('Real Madrid 19/20 - Titular (Gold trim)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 19/20. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (6).png'),
('Real Madrid 17/18 - Titular (Blue trim)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 17/18. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (7).png'),
('Real Madrid Retrô 99/00 - Titular (Teka)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada Retrô 99/00. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (8).png'),
('Santos 2012 - Terceira (Azul)', 109.9, 'Brasileirão', 'Manto premium do Santos, temporada 2012. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (9).png'),
('Inter de Milão Retrô 98/99 - Titular (Pirelli)', 109.9, 'Serie A', 'Manto premium do Inter de Milão, temporada Retrô 98/99. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (10).png'),
('Manchester United 23/24 - Titular (Manga Longa)', 109.9, 'Premier League', 'Manto premium do Manchester United, temporada 23/24. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (11).png'),
('Barcelona Retrô 01/02 - Reserva (Dourada)', 109.9, 'La Liga', 'Manto premium do Barcelona, temporada Retrô 01/02. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (12).png'),
('Argentina 2022/24 - Titular (3 Estrelas)', 109.9, 'Seleções', 'Manto premium do Argentina, temporada 2022/24. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (13).png'),
('Espanha 2024 - Titular (Lamine Yamal 19)', 109.9, 'Seleções', 'Manto premium do Espanha, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (14).png'),
('Real Madrid 16/17 - Reserva (Roxa - Manga Longa)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 16/17. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (15).png'),
('Real Madrid 23/24 - Terceira (Preta - Rodrygo 11)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 23/24. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (16).png'),
('Real Madrid 14/15 - Reserva (Rosa)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 14/15. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (17).png'),
('Manchester United Retrô 07/08 - Titular (AIG)', 109.9, 'Premier League', 'Manto premium do Manchester United, temporada Retrô 07/08. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (18).png'),
('Manchester United Retrô 07/08 - Titular (Final Moscow)', 109.9, 'Premier League', 'Manto premium do Manchester United, temporada Retrô 07/08. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (19).png'),
('Milan Retrô 06/07 - Titular (Manga Longa)', 109.9, 'Serie A', 'Manto premium do Milan, temporada Retrô 06/07. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (20).png'),
('Milan Retrô 06/07 - Titular', 109.9, 'Serie A', 'Manto premium do Milan, temporada Retrô 06/07. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (21).png'),
('PSG Retrô 95/96 - Titular (Costas)', 109.9, 'International', 'Manto premium do PSG, temporada Retrô 95/96. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (22).png'),
('Real Madrid Retrô 99/00 - Reserva (Preta - Teka)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada Retrô 99/00. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (23).png'),
('PSG Retrô 98/00 - Titular (Opel)', 109.9, 'International', 'Manto premium do PSG, temporada Retrô 98/00. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (24).png'),
('Real Madrid 17/18 - Terceira (Turquesa - Manga Longa)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 17/18. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (25).png'),
('Barcelona Retrô 10/11 - Titular (Unicef)', 109.9, 'La Liga', 'Manto premium do Barcelona, temporada Retrô 10/11. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (26).png'),
('Al-Hilal 23/24 - Titular (Neymar Jr 10)', 109.9, 'International', 'Manto premium do Al-Hilal, temporada 23/24. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (27).png'),
('Alemanha 2024 - Titular (Havertz 7)', 109.9, 'Seleções', 'Manto premium do Alemanha, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (28).png'),
('Croácia 2024 - Titular (Modric 10)', 109.9, 'Seleções', 'Manto premium do Croácia, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (29).png'),
('Flamengo 2024 - Reserva (Branca)', 109.9, 'Brasileirão', 'Manto premium do Flamengo, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (30).png'),
('Flamengo 2024 - Titular (De La Cruz 18)', 109.9, 'Brasileirão', 'Manto premium do Flamengo, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (31).png'),
('França 2024 - Titular (Mbappé 10)', 109.9, 'Seleções', 'Manto premium do França, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (32).png'),
('Inglaterra 2024 - Titular (Bellingham 10)', 109.9, 'Seleções', 'Manto premium do Inglaterra, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (33).png'),
('Portugal 2024 - Titular (Ronaldo 7)', 109.9, 'Seleções', 'Manto premium do Portugal, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (34).png'),
('Portugal 2024 - Reserva (Ronaldo 7 - Pattern)', 109.9, 'Seleções', 'Manto premium do Portugal, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (35).png'),
('PSG 23/24 - Titular (Dembélé 10)', 109.9, 'Internacional', 'Manto premium do PSG, temporada 23/24. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (36).png'),
('Real Madrid 24/25 - Titular (Mbappé 9)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (37).png'),
('Flamengo 2024 - Reserva (De La Cruz 18)', 109.9, 'Brasileirão', 'Manto premium do Flamengo, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (38).png'),
('Brasil 2024 - Titular (Pattern)', 109.9, 'Seleções', 'Manto premium do Brasil, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (39).png'),
('Barcelona Retrô 11/12 - Titular (Qatar Foundation)', 109.9, 'La Liga', 'Manto premium do Barcelona, temporada Retrô 11/12. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (40).png'),
('Brasil Retrô 2002 - Titular', 109.9, 'Seleções', 'Manto premium do Brasil, temporada Retrô 2002. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (41).png'),
('Brasil Retrô 2004 - Titular (T90 Style)', 109.9, 'Seleções', 'Manto premium do Brasil, temporada Retrô 2004. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (42).png'),
('Brasil Retrô 2004 - Reserva (Azul - T90 Style)', 109.9, 'Seleções', 'Manto premium do Brasil, temporada Retrô 2004. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (43).png'),
('Manchester United 22/23 - Titular', 109.9, 'Premier League', 'Manto premium do Manchester United, temporada 22/23. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (44).png'),
('Holanda 2024 - Titular', 109.9, 'Seleções', 'Manto premium do Holanda, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (45).png'),
('Real Madrid Retrô 16/17 - Reserva (Roxa)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada Retrô 16/17. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (46).png'),
('Manchester United 22/23 - Titular (Perspectiva)', 109.9, 'Premier League', 'Manto premium do Manchester United, temporada 22/23. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (47).png'),
('Arsenal 23/24 - Titular', 109.9, 'Premier League', 'Manto premium do Arsenal, temporada 23/24. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (48).png'),
('Arsenal 23/24 - Titular (Lateral)', 109.9, 'Premier League', 'Manto premium do Arsenal, temporada 23/24. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (49).png'),
('Real Madrid Retrô 14/15 - Titular (Manga Longa)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada Retrô 14/15. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (50).png'),
('Real Madrid Retrô 06/07 - Reserva (Preta - Manga Longa)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada Retrô 06/07. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (51).png'),
('Real Madrid Retrô 13/14 - Reserva (Laranja - Manga Longa)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada Retrô 13/14. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (52).png'),
('Brasil 2024 - Titular (Pattern - Perspectiva)', 109.9, 'Seleções', 'Manto premium do Brasil, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (53).png'),
('Manchester United 22/23 - Titular (Lado)', 109.9, 'Premier League', 'Manto premium do Manchester United, temporada 22/23. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (54).png'),
('Barcelona Retrô 13/14 - Titular (Qatar Airways)', 109.9, 'La Liga', 'Manto premium do Barcelona, temporada Retrô 13/14. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (55).png'),
('Barcelona Retrô 18/19 - Titular (Rakuten)', 109.9, 'La Liga', 'Manto premium do Barcelona, temporada Retrô 18/19. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (56).png'),
('Real Madrid Retrô 16/17 - Reserva (Roxa - Sem Número)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada Retrô 16/17. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (57).png'),
('Barcelona Retrô 12/13 - Titular (Qatar Foundation - Fade)', 109.9, 'La Liga', 'Manto premium do Barcelona, temporada Retrô 12/13. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (58).png'),
('Real Madrid Retrô 17/18 - Titular', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada Retrô 17/18. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (59).png'),
('Manchester United 22/23 - Reserva (Branca)', 109.9, 'Premier League', 'Manto premium do Manchester United, temporada 22/23. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (60).png'),
('Barcelona 14/15 - Titular', 109.9, 'La Liga', 'Manto premium do Barcelona, temporada 14/15. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (61).png'),
('Barcelona 20/21 - Titular', 109.9, 'La Liga', 'Manto premium do Barcelona, temporada 20/21. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (62).png'),
('Borussia Dortmund 22/23 - Especial (Blackout)', 109.9, 'Bundesliga', 'Manto premium do Borussia Dortmund, temporada 22/23. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (63).png'),
('Manchester City 22/23 - Titular (Haaland 9 - Costas)', 109.9, 'Premier League', 'Manto premium do Manchester City, temporada 22/23. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (64).png'),
('Manchester United 18/19 - Reserva (Rosa)', 109.9, 'Premier League', 'Manto premium do Manchester United, temporada 18/19. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (65).png'),
('Argentina 2024 - Titular (Costas)', 109.9, 'Seleções', 'Manto premium do Argentina, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (66).png'),
('Argentina 2024 - Titular', 109.9, 'Seleções', 'Manto premium do Argentina, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (67).png'),
('Brasil 2024 - Titular (Costas)', 109.9, 'Seleções', 'Manto premium do Brasil, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (68).png'),
('França 2024 - Reserva (Mbappé 10)', 109.9, 'Seleções', 'Manto premium do França, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (69).png'),
('Real Madrid 21/22 - Titular (Modric 10)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 21/22. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (70).png'),
('Real Madrid 23/24 - Reserva (Carvajal 2 - Costas)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 23/24. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (71).png'),
('Manchester City 22/23 - Titular', 109.9, 'Premier League', 'Manto premium do Manchester City, temporada 22/23. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (72).png'),
('Brasil Retrô 2016 - Titular', 109.9, 'Seleções', 'Manto premium do Brasil, temporada Retrô 2016. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (73).png'),
('Barcelona 16/17 - Reserva (Roxa)', 109.9, 'La Liga', 'Manto premium do Barcelona, temporada 16/17. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (74).png'),
('Vasco da Gama 23/24 - Titular', 109.9, 'Brasileirão', 'Manto premium do Vasco da Gama, temporada 23/24. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (75).png'),
('Palmeiras 2024 - Titular (110 Anos)', 109.9, 'Brasileirão', 'Manto premium do Palmeiras, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (76).png'),
('São Paulo 2024 - Titular', 109.9, 'Brasileirão', 'Manto premium do São Paulo, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (77).png'),
('Grêmio Retrô 2005 - Titular (Kappa)', 109.9, 'Brasileirão', 'Manto premium do Grêmio, temporada Retrô 2005. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (78).png'),
('Chelsea 21/22 - Titular', 109.9, 'Premier League', 'Manto premium do Chelsea, temporada 21/22. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (79).png'),
('Grêmio Retrô 2005 - Titular (Kappa - Repetida)', 109.9, 'Brasileirão', 'Manto premium do Grêmio, temporada Retrô 2005. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (80).png'),
('Palmeiras 2024 - Titular', 109.9, 'Brasileirão', 'Manto premium do Palmeiras, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (81).png'),
('Borussia Dortmund 23/24 - Titular', 109.9, 'Bundesliga', 'Manto premium do Borussia Dortmund, temporada 23/24. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (82).png'),
('Argentina 2024 - Titular (Repetida)', 109.9, 'Seleções', 'Manto premium do Argentina, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (83).png'),
('Atlético de Madrid 22/23 - Titular', 109.9, 'La Liga', 'Manto premium do Atlético de Madrid, temporada 22/23. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (84).png'),
('Flamengo 2024 - Titular (Manga Longa)', 109.9, 'Brasileirão', 'Manto premium do Flamengo, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (85).png'),
('Botafogo 2024 - Titular (Costas)', 109.9, 'Brasileirão', 'Manto premium do Botafogo, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (86).png'),
('Botafogo 2024 - Titular', 109.9, 'Brasileirão', 'Manto premium do Botafogo, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (87).png'),
('Santos 2024 - Reserva (Listrada)', 109.9, 'Brasileirão', 'Manto premium do Santos, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (88).png'),
('Santos 2024 - Titular', 109.9, 'Brasileirão', 'Manto premium do Santos, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (89).png'),
('Corinthians 2024 - Especial (Anti-Racismo)', 109.9, 'Brasileirão', 'Manto premium do Corinthians, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (90).png'),
('Real Madrid 23/24 - Terceira (Preta - Vini Jr 7)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 23/24. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (91).png'),
('Real Madrid 23/24 - Titular (Camavinga 12 - Costas)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 23/24. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (92).png'),
('Real Madrid 23/24 - Titular (Bellingham 5)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 23/24. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (93).png'),
('Real Madrid 23/24 - Titular (Bellingham 5 - Manga Longa)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 23/24. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (94).png'),
('Argentina 2022/24 - Titular (Messi 10 - 3 Estrelas)', 109.9, 'Seleções', 'Manto premium do Argentina, temporada 2022/24. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (95).png'),
('Real Madrid 24/25 - Titular', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (96).png'),
('Real Madrid 24/25 - Titular (Mbappé 9 - Costas)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (97).png'),
('Real Madrid 2024 - Edição Especial Balmain', 109.9, 'Especiais', 'Manto premium do Real Madrid, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (98).png'),
('Real Madrid 2024 - Edição Especial Balmain (Costas)', 109.9, 'Especiais', 'Manto premium do Real Madrid, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (99).png'),
('Espanha 2024 - Titular (Carvajal 2 - Costas)', 109.9, 'Seleções', 'Manto premium do Espanha, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (100).png'),
('Espanha 2024 - Titular (Carvajal 2)', 109.9, 'Seleções', 'Manto premium do Espanha, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (101).png'),
('Manchester United Retrô 2008 - Titular (Final Moscow)', 109.9, 'Premier League', 'Manto premium do Manchester United, temporada Retrô 2008. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (102).png'),
('Real Madrid 21/22 - Reserva (Azul Graffiti - Costas)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 21/22. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (103).png'),
('Real Madrid 21/22 - Reserva (Azul Graffiti)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 21/22. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (104).png'),
('Bayern de Munique 24/25 - Titular (Kane 9 - Costas)', 109.9, 'Bundesliga', 'Manto premium do Bayern de Munique, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (105).png'),
('Bayern de Munique 24/25 - Titular', 109.9, 'Bundesliga', 'Manto premium do Bayern de Munique, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (106).png'),
('Colômbia 2024 - Reserva (Azul/Laranja - Costas)', 109.9, 'Seleções', 'Manto premium do Colômbia, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (107).png'),
('Colômbia 2024 - Reserva (Azul/Laranja)', 109.9, 'Seleções', 'Manto premium do Colômbia, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (108).png'),
('Cruzeiro 2024 - Titular (Costas)', 109.9, 'Brasileirão', 'Manto premium do Cruzeiro, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (109).png'),
('Cruzeiro 2024 - Titular', 109.9, 'Brasileirão', 'Manto premium do Cruzeiro, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (110).png'),
('Real Madrid 23/24 - Terceira (Preta)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 23/24. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (111).png'),
('Real Madrid 23/24 - Titular', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 23/24. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (112).png'),
('Borussia Dortmund 22/23 - Titular (Costas)', 109.9, 'Bundesliga', 'Manto premium do Borussia Dortmund, temporada 22/23. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (113).png'),
('Brasil 2024 - Titular', 109.9, 'Seleções', 'Manto premium do Brasil, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (114).png'),
('Palmeiras Retrô 1993 - Titular (Parmalat)', 109.9, 'Brasileirão', 'Manto premium do Palmeiras, temporada Retrô 1993. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (115).png'),
('Real Madrid Retrô 16/17 - Reserva (Roxa)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada Retrô 16/17. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (116).png'),
('Real Madrid 23/24 - Reserva (Azul Marinho)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 23/24. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (117).png'),
('Real Madrid 23/24 - Titular (Repetida)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 23/24. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (118).png'),
('Real Madrid 21/22 - Titular', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 21/22. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (119).png'),
('Real Madrid 21/22 - Titular (Repetida)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 21/22. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (120).png'),
('Santos 2024 - Especial (Charlie Brown Jr)', 109.9, 'Brasileirão', 'Manto premium do Santos, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (121).png'),
('Santos 2024 - Especial (Charlie Brown Jr - Costas)', 109.9, 'Brasileirão', 'Manto premium do Santos, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (122).png'),
('Portugal 2024 - Titular', 109.9, 'Seleções', 'Manto premium do Portugal, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (123).png'),
('Manchester City 24/25 - Titular', 109.9, 'Premier League', 'Manto premium do Manchester City, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (124).png'),
('Vasco da Gama 2024 - Titular', 109.9, 'Brasileirão', 'Manto premium do Vasco da Gama, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (125).png'),
('Vasco da Gama 2024 - Reserva', 109.9, 'Brasileirão', 'Manto premium do Vasco da Gama, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (126).png'),
('Flamengo 2024 - Especial (1895)', 109.9, 'Brasileirão', 'Manto premium do Flamengo, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (127).png'),
('Vasco da Gama 2024 - Titular (Coutinho 11 - Costas)', 109.9, 'Brasileirão', 'Manto premium do Vasco da Gama, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (128).png'),
('Vasco da Gama 2024 - Reserva (Coutinho 11 - Costas)', 109.9, 'Brasileirão', 'Manto premium do Vasco da Gama, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (129).png'),
('Barcelona 14/15 - Titular', 109.9, 'La Liga', 'Manto premium do Barcelona, temporada 14/15. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (130).png'),
('Holanda Retrô 2014 - Titular', 109.9, 'Seleções', 'Manto premium do Holanda, temporada Retrô 2014. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (131).png'),
('Manchester United 21/22 - Titular', 109.9, 'Premier League', 'Manto premium do Manchester United, temporada 21/22. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (132).png'),
('Real Madrid 22/23 - Titular (120 Anos)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 22/23. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (133).png'),
('Real Madrid 17/18 - Titular', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 17/18. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (134).png'),
('Real Madrid Retrô 2001 - Titular (Centenário)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada Retrô 2001. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (135).png'),
('Portugal 2024 - Titular (Ronaldo 7)', 109.9, 'Seleções', 'Manto premium do Portugal, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (136).png'),
('Portugal 2024 - Titular (Ronaldo 7 - Costas)', 109.9, 'Seleções', 'Manto premium do Portugal, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (137).png'),
('Brasil 2017 - Reserva (Azul)', 109.9, 'Seleções', 'Manto premium do Brasil, temporada 2017. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (138).png'),
('Argentina Retrô 2006 - Titular', 109.9, 'Seleções', 'Manto premium do Argentina, temporada Retrô 2006. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (139).png'),
('Alemanha 2024 - Titular (Kroos 8)', 109.9, 'Seleções', 'Manto premium do Alemanha, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (140).png'),
('Alemanha 2024 - Titular (Kroos 8 - Costas)', 109.9, 'Seleções', 'Manto premium do Alemanha, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (141).png'),
('Real Madrid 14/15 - Reserva (Rosa)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 14/15. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (142).png'),
('Portugal 2024 - Titular (Similar)', 109.9, 'Seleções', 'Manto premium do Portugal, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (143).png'),
('Real Madrid 24/25 - Titular (Similar)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (144).png'),
('França 2024 - Titular', 109.9, 'Seleções', 'Manto premium do França, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (145).png'),
('Real Madrid 13/14 - Titular', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 13/14. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (146).png'),
('Real Madrid 13/14 - Titular (Costas)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 13/14. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (147).png'),
('França 2018 - Titular', 109.9, 'Seleções', 'Manto premium do França, temporada 2018. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (148).png'),
('França 2018 - Titular (Costas)', 109.9, 'Seleções', 'Manto premium do França, temporada 2018. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (149).png'),
('Chelsea 24/25 - Titular', 109.9, 'Premier League', 'Manto premium do Chelsea, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (150).png'),
('Real Madrid 23/24 - Titular (Modric 10 - Costas)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 23/24. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (151).png'),
('Real Madrid 23/24 - Titular (Bellingham 5 - Costas)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 23/24. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (152).png'),
('Real Madrid 23/24 - Titular', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 23/24. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (153).png'),
('Vasco da Gama 2024 - Titular (Payet 10)', 109.9, 'Brasileirão', 'Manto premium do Vasco da Gama, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (154).png'),
('Vasco da Gama 2024 - Reserva (Payet 10)', 109.9, 'Brasileirão', 'Manto premium do Vasco da Gama, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (155).png'),
('São Paulo 2024 - Titular (Galoppo 14)', 109.9, 'Brasileirão', 'Manto premium do São Paulo, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (156).png'),
('São Paulo 2024 - Reserva (Galoppo 14)', 109.9, 'Brasileirão', 'Manto premium do São Paulo, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (157).png'),
('Palmeiras 2024 - Titular (Rony 10)', 109.9, 'Brasileirão', 'Manto premium do Palmeiras, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (158).png'),
('Palmeiras 2024 - Reserva (Rony 10)', 109.9, 'Brasileirão', 'Manto premium do Palmeiras, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (159).png'),
('México 2024 - Titular (Alvarado 10)', 109.9, 'Seleções', 'Manto premium do México, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (160).png'),
('Grêmio 2024 - Titular (Cristaldo 10)', 109.9, 'Brasileirão', 'Manto premium do Grêmio, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (161).png'),
('Corinthians 2024 - Titular (Yuri Alberto 9)', 109.9, 'Brasileirão', 'Manto premium do Corinthians, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (162).png'),
('Corinthians 2024 - Reserva (Yuri Alberto 9)', 109.9, 'Brasileirão', 'Manto premium do Corinthians, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (163).png'),
('Colômbia 2024 - Titular (James Rodriguez 10)', 109.9, 'Seleções', 'Manto premium do Colômbia, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (164).png'),
('Chile 2024 - Titular (Alexis Sanchez 10)', 109.9, 'Seleções', 'Manto premium do Chile, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (165).png'),
('Atlético Mineiro 2024 - Titular (Hulk 7)', 109.9, 'Brasileirão', 'Manto premium do Atlético Mineiro, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (166).png'),
('Argentina 2024 - Titular (Messi 10)', 109.9, 'Seleções', 'Manto premium do Argentina, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (167).png'),
('Espanha 2024 - Titular (Lamine Yamal 19)', 109.9, 'Seleções', 'Manto premium do Espanha, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (168).png'),
('Borussia Dortmund 19/20 - Titular', 109.9, 'Bundesliga', 'Manto premium do Borussia Dortmund, temporada 19/20. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (169).png'),
('Liverpool 22/23 - Especial (LeBron James)', 109.9, 'Premier League', 'Manto premium do Liverpool, temporada 22/23. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (170).png'),
('Corinthians 2024 - Reserva (Blackout)', 109.9, 'Brasileirão', 'Manto premium do Corinthians, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (171).png'),
('Corinthians 2024 - Reserva (Blackout - Costas)', 109.9, 'Brasileirão', 'Manto premium do Corinthians, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (172).png'),
('PSG 21/22 - Titular (Jordan)', 109.9, 'Ligue 1', 'Manto premium do PSG, temporada 21/22. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (173).png'),
('Real Madrid 23/24 - Titular (V2)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 23/24. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (174).png'),
('Real Madrid 23/24 - Titular (Vini Jr 7 - Costas)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 23/24. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (175).png'),
('Barcelona 12/13 - Titular', 109.9, 'La Liga', 'Manto premium do Barcelona, temporada 12/13. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (176).png'),
('Fluminense 2012 - Especial (Grená)', 109.9, 'Brasileirão', 'Manto premium do Fluminense, temporada 2012. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (177).png'),
('Atlético de Madrid 13/14 - Titular', 109.9, 'La Liga', 'Manto premium do Atlético de Madrid, temporada 13/14. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (178).png'),
('Real Madrid 17/18 - Reserva (Azul)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 17/18. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (179).png'),
('Palmeiras 2024 - Reserva', 109.9, 'Brasileirão', 'Manto premium do Palmeiras, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (180).png'),
('Bayern de Munique 24/25 - Terceiro (Bege - Trefoil - Costas)', 109.9, 'Bundesliga', 'Manto premium do Bayern de Munique, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (181).png'),
('Bayern de Munique 24/25 - Terceiro (Bege - Trefoil)', 109.9, 'Bundesliga', 'Manto premium do Bayern de Munique, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (182).png'),
('AS Roma 24/25 - Titular', 109.9, 'Serie A', 'Manto premium do AS Roma, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (183).png'),
('Aston Villa 24/25 - Reserva', 109.9, 'Premier League', 'Manto premium do Aston Villa, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (184).png'),
('Borussia Dortmund 24/25 - Titular', 109.9, 'Bundesliga', 'Manto premium do Borussia Dortmund, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (185).png'),
('Borussia Dortmund 24/25 - Titular (Adeyemi 27 - Costas)', 109.9, 'Bundesliga', 'Manto premium do Borussia Dortmund, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (186).png'),
('Aston Villa 24/25 - Titular', 109.9, 'Premier League', 'Manto premium do Aston Villa, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (187).png'),
('Milan 24/25 - Titular', 109.9, 'Serie A', 'Manto premium do Milan, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (188).png'),
('Juventus 23/24 - Titular (Zebra)', 109.9, 'Serie A', 'Manto premium do Juventus, temporada 23/24. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (189).png'),
('Juventus 23/24 - Titular (Zebra - Costas)', 109.9, 'Serie A', 'Manto premium do Juventus, temporada 23/24. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (190).png'),
('Milan 08/09 - Retrô (Ronaldinho 80 - Costas)', 109.9, 'Serie A', 'Manto premium do Milan, temporada 08/09. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (191).png'),
('Palmeiras 2024 - Titular (Costas)', 109.9, 'Brasileirão', 'Manto premium do Palmeiras, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (192).png'),
('Palmeiras 2024 - Titular (Frente)', 109.9, 'Brasileirão', 'Manto premium do Palmeiras, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (193).png'),
('Real Madrid 24/25 - Reserva (Laranja - Manga Longa - Costas)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (194).png'),
('Real Madrid 24/25 - Reserva (Laranja - Manga Longa)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (195).png'),
('Manchester United 08/09 - Retrô (Azul - Manga Longa)', 109.9, 'Premier League', 'Manto premium do Manchester United, temporada 08/09. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (196).png'),
('Real Madrid 24/25 - Reserva (Laranja)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (197).png'),
('Bayern de Munique 14/15 - Retrô (Listrada)', 109.9, 'Bundesliga', 'Manto premium do Bayern de Munique, temporada 14/15. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (198).png'),
('Bayern de Munique 14/15 - Retrô (Listrada - Costas)', 109.9, 'Bundesliga', 'Manto premium do Bayern de Munique, temporada 14/15. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (199).png'),
('Real Madrid 24/25 - Reserva (Laranja - Costas)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (200).png'),
('Inglaterra 2024 - Titular (Bellingham 10 - Costas)', 109.9, 'Seleções', 'Manto premium do Inglaterra, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (201).png'),
('Inglaterra 2024 - Titular (Bellingham 10)', 109.9, 'Seleções', 'Manto premium do Inglaterra, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (202).png'),
('Napoli 24/25 - Titular', 109.9, 'Serie A', 'Manto premium do Napoli, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (203).png'),
('Napoli 24/25 - Titular (Costas)', 109.9, 'Serie A', 'Manto premium do Napoli, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (204).png'),
('França 2024 - Titular (Mbappé 10 - Costas)', 109.9, 'Seleções', 'Manto premium do França, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (205).png'),
('França 2024 - Titular (Mbappé 10)', 109.9, 'Seleções', 'Manto premium do França, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (206).png'),
('Borussia Dortmund 24/25 - Especial (Preta)', 109.9, 'Bundesliga', 'Manto premium do Borussia Dortmund, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (207).png'),
('Real Madrid 24/25 - Titular', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (208).png'),
('Real Madrid 24/25 - Titular (Costas)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (209).png'),
('Real Madrid 24/25 - Terceiro (Cinza - Costas)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (210).png'),
('Cruzeiro 24/25 - Titular (Costas)', 109.9, 'Brasileirão', 'Manto premium do Cruzeiro, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (211).png'),
('Cruzeiro 24/25 - Titular', 109.9, 'Brasileirão', 'Manto premium do Cruzeiro, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (212).png'),
('Atlético Mineiro 2024 - Titular (Costas)', 109.9, 'Brasileirão', 'Manto premium do Atlético Mineiro, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (213).png'),
('Atlético Mineiro 2024 - Titular', 109.9, 'Brasileirão', 'Manto premium do Atlético Mineiro, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (214).png'),
('Real Madrid 23/24 - Reserva (Azul Marinho - Costas)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 23/24. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (215).png'),
('Real Madrid 23/24 - Reserva (Azul Marinho)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 23/24. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (216).png'),
('Manchester United 24/25 - Titular (Costas)', 109.9, 'Premier League', 'Manto premium do Manchester United, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (217).png'),
('Manchester United 24/25 - Titular', 109.9, 'Premier League', 'Manto premium do Manchester United, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (218).png'),
('Palmeiras 2024 - Titular (Costas - Outro Ângulo)', 109.9, 'Brasileirão', 'Manto premium do Palmeiras, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (219).png'),
('Real Madrid 17/18 - Reserva (Turquesa)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 17/18. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (220).png'),
('Barcelona 14/15 - Titular', 109.9, 'La Liga', 'Manto premium do Barcelona, temporada 14/15. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (221).png'),
('Real Madrid 22/23 - Titular (Benzema 9 - Costas)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 22/23. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (222).png'),
('Real Madrid 22/23 - Titular (Benzema 9 - Costas - Duplicada)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 22/23. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (223).png'),
('Flamengo 1995 - Retrô (Centenário)', 109.9, 'Brasileirão', 'Manto premium do Flamengo, temporada 1995. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (224).png'),
('Real Madrid 17/18 - Titular', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 17/18. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (225).png'),
('Real Madrid 16/17 - Reserva (Roxa)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 16/17. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (226).png'),
('Bayer Leverkusen 23/24 - Titular', 109.9, 'Bundesliga', 'Manto premium do Bayer Leverkusen, temporada 23/24. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (227).png'),
('Bayer Leverkusen 23/24 - Titular (Costas)', 109.9, 'Bundesliga', 'Manto premium do Bayer Leverkusen, temporada 23/24. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (228).png'),
('Napoli 23/24 - Titular (Costas)', 109.9, 'Serie A', 'Manto premium do Napoli, temporada 23/24. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (229).png'),
('Real Madrid 24/25 - Terceiro (Cinza Padrão - Costas)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (230).png'),
('Bayern de Munique 24/25 - Titular (Costas)', 109.9, 'Bundesliga', 'Manto premium do Bayern de Munique, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (231).png'),
('Real Madrid 23/24 - Reserva (Azul Padrão - Costas)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 23/24. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (232).png'),
('Bayern de Munique 24/25 - Titular', 109.9, 'Bundesliga', 'Manto premium do Bayern de Munique, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (233).png'),
('Napoli 23/24 - Titular', 109.9, 'Serie A', 'Manto premium do Napoli, temporada 23/24. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (234).png'),
('Santos 2024 - Especial (Charlie Brown Jr)', 109.9, 'Brasileirão', 'Manto premium do Santos, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (235).png'),
('Real Madrid 21/22 - Titular', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 21/22. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (236).png'),
('Borussia Dortmund 23/24 - Especial (Preta/Amarela - Costas)', 109.9, 'Bundesliga', 'Manto premium do Borussia Dortmund, temporada 23/24. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (237).png'),
('Real Madrid 23/24 - Reserva (Azul Padrão)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 23/24. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (238).png'),
('Arsenal 05/06 - Retrô (Highbury Farewell)', 109.9, 'Premier League', 'Manto premium do Arsenal, temporada 05/06. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (239).png'),
('Vasco da Gama 2024 - Titular (Costas)', 109.9, 'Brasileirão', 'Manto premium do Vasco da Gama, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (240).png'),
('Vasco da Gama 2024 - Titular', 109.9, 'Brasileirão', 'Manto premium do Vasco da Gama, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (241).png'),
('Inter de Milão 23/24 - Titular (Costas)', 109.9, 'Serie A', 'Manto premium do Inter de Milão, temporada 23/24. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (242).png'),
('Inter de Milão 23/24 - Titular', 109.9, 'Serie A', 'Manto premium do Inter de Milão, temporada 23/24. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (243).png'),
('AS Roma 23/24 - Titular (Costas)', 109.9, 'Serie A', 'Manto premium do AS Roma, temporada 23/24. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (244).png'),
('AS Roma 23/24 - Titular', 109.9, 'Serie A', 'Manto premium do AS Roma, temporada 23/24. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (245).png'),
('Bélgica 2024 - Titular (Costas)', 109.9, 'Seleções', 'Manto premium do Bélgica, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (246).png'),
('Bélgica 2024 - Titular', 109.9, 'Seleções', 'Manto premium do Bélgica, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (247).png'),
('Alemanha 2024 - Titular (Costas)', 109.9, 'Seleções', 'Manto premium do Alemanha, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (248).png'),
('Alemanha 2024 - Titular', 109.9, 'Seleções', 'Manto premium do Alemanha, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (249).png'),
('Real Madrid 14/15 - Reserva (Rosa)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 14/15. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (250).png'),
('Real Madrid 14/15 - Reserva (Rosa - Costas)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 14/15. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (251).png'),
('Barcelona 04/05 - Retrô (Costas)', 109.9, 'La Liga', 'Manto premium do Barcelona, temporada 04/05. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (252).png'),
('Barcelona 04/05 - Retrô', 109.9, 'La Liga', 'Manto premium do Barcelona, temporada 04/05. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (253).png'),
('Brasil 2004 - Retrô (Azul - Costas)', 109.9, 'Seleções', 'Manto premium do Brasil, temporada 2004. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (254).png'),
('Brasil 2004 - Retrô (Azul)', 109.9, 'Seleções', 'Manto premium do Brasil, temporada 2004. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (255).png'),
('Real Madrid 16/17 - Reserva (Roxa - Duplicada)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 16/17. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (256).png'),
('Real Madrid 16/17 - Reserva (Roxa - Costas)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 16/17. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (257).png'),
('Real Madrid 17/18 - Terceiro (Preta/Turquesa - Costas)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 17/18. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (258).png'),
('Real Madrid 17/18 - Terceiro (Preta/Turquesa)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 17/18. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (259).png'),
('Fluminense 2024 - Titular (Costas)', 109.9, 'Brasileirão', 'Manto premium do Fluminense, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (260).png'),
('Fluminense 2024 - Titular', 109.9, 'Brasileirão', 'Manto premium do Fluminense, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (261).png'),
('Inter de Milão 24/25 - Titular (Frente)', 109.9, 'Serie A', 'Manto premium do Inter de Milão, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (262).png'),
('Inter de Milão 24/25 - Titular (Costas)', 109.9, 'Serie A', 'Manto premium do Inter de Milão, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (263).png'),
('Inter de Milão 24/25 - Titular (Detalhe)', 109.9, 'Serie A', 'Manto premium do Inter de Milão, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (264).png'),
('Barcelona 24/25 - Titular', 109.9, 'La Liga', 'Manto premium do Barcelona, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (265).png'),
('Barcelona 24/25 - Titular (Costas)', 109.9, 'La Liga', 'Manto premium do Barcelona, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (266).png'),
('Inter Miami 2024 - Titular (Costas)', 109.9, 'MLS', 'Manto premium do Inter Miami, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (267).png'),
('Inter Miami 2024 - Titular', 109.9, 'MLS', 'Manto premium do Inter Miami, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (268).png'),
('Croácia 2024 - Reserva (Costas)', 109.9, 'Seleções', 'Manto premium do Croácia, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (269).png'),
('Croácia 2024 - Reserva', 109.9, 'Seleções', 'Manto premium do Croácia, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (270).png'),
('Vasco da Gama 2024 - Reserva', 109.9, 'Brasileirão', 'Manto premium do Vasco da Gama, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (271).png'),
('Botafogo 2024 - Titular', 109.9, 'Brasileirão', 'Manto premium do Botafogo, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (272).png'),
('Botafogo 2024 - Titular (Costas)', 109.9, 'Brasileirão', 'Manto premium do Botafogo, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (273).png'),
('Barcelona 95/97 - Retrô (Reserva - Costas)', 109.9, 'La Liga', 'Manto premium do Barcelona, temporada 95/97. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (274).png'),
('Barcelona 95/97 - Retrô (Reserva)', 109.9, 'La Liga', 'Manto premium do Barcelona, temporada 95/97. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (275).png'),
('Arsenal 05/06 - Retrô (Highbury Farewell - Costas)', 109.9, 'Premier League', 'Manto premium do Arsenal, temporada 05/06. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (276).png'),
('Argentina 2006 - Retrô (Costas)', 109.9, 'Seleções', 'Manto premium do Argentina, temporada 2006. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (277).png'),
('Argentina 2006 - Retrô', 109.9, 'Seleções', 'Manto premium do Argentina, temporada 2006. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (278).png'),
('Al-Nassr 24/25 - Titular', 109.9, 'Saudi Pro League', 'Manto premium do Al-Nassr, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (279).png'),
('Al-Nassr 24/25 - Titular (Costas)', 109.9, 'Saudi Pro League', 'Manto premium do Al-Nassr, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (280).png'),
('Real Madrid 17/18 - Titular (Ronaldo 7 - Costas)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 17/18. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (281).png'),
('Milan 24/25 - Titular', 109.9, 'Serie A', 'Manto premium do Milan, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (282).png'),
('PSG 24/25 - Titular (Costas)', 109.9, 'Ligue 1', 'Manto premium do PSG, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (283).png'),
('PSG 24/25 - Titular', 109.9, 'Ligue 1', 'Manto premium do PSG, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (284).png'),
('Liverpool 24/25 - Titular (Costas)', 109.9, 'Premier League', 'Manto premium do Liverpool, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (285).png'),
('Liverpool 24/25 - Titular', 109.9, 'Premier League', 'Manto premium do Liverpool, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (286).png'),
('Real Madrid 23/24 - Terceiro (Preta/Dourada)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 23/24. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (287).png'),
('Atlético de Madrid 22/23 - Titular (Costas)', 109.9, 'La Liga', 'Manto premium do Atlético de Madrid, temporada 22/23. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (288).png'),
('Atlético de Madrid 22/23 - Titular', 109.9, 'La Liga', 'Manto premium do Atlético de Madrid, temporada 22/23. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (289).png'),
('Borussia Dortmund 23/24 - Titular (Costas)', 109.9, 'Bundesliga', 'Manto premium do Borussia Dortmund, temporada 23/24. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (290).png'),
('Borussia Dortmund 23/24 - Titular', 109.9, 'Bundesliga', 'Manto premium do Borussia Dortmund, temporada 23/24. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (291).png'),
('Real Madrid 24/25 - Titular (Detalhe)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (292).png'),
('Bayern de Munique 24/25 - Titular (Costas)', 109.9, 'Bundesliga', 'Manto premium do Bayern de Munique, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (293).png'),
('Bayern de Munique 24/25 - Titular (Frente)', 109.9, 'Bundesliga', 'Manto premium do Bayern de Munique, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (294).png'),
('França 2024 - Titular', 109.9, 'Seleções', 'Manto premium do França, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (295).png'),
('Brasil 2024 - Titular', 109.9, 'Seleções', 'Manto premium do Brasil, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (296).png'),
('Real Madrid 24/25 - Titular (Detalhe 2)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (297).png'),
('Palmeiras 2024 - Titular', 109.9, 'Brasileirão', 'Manto premium do Palmeiras, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (298).png'),
('Real Madrid 24/25 - Titular', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (299).png'),
('Manchester United 08/09 - Retrô (Preta/Vermelha)', 109.9, 'Premier League', 'Manto premium do Manchester United, temporada 08/09. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (300).png'),
('Real Madrid 23/24 - Especial (Cinza)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 23/24. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (301).png'),
('Manchester United 07/09 - Retrô (Titular)', 109.9, 'Premier League', 'Manto premium do Manchester United, temporada 07/09. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (302).png'),
('Milan 06/07 - Retrô (Titular - Costas)', 109.9, 'Serie A', 'Manto premium do Milan, temporada 06/07. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (303).png'),
('Manchester United 07/08 - Retrô (Final Moscow)', 109.9, 'Premier League', 'Manto premium do Manchester United, temporada 07/08. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (304).png'),
('Chelsea 03/05 - Retrô (Reserva)', 109.9, 'Premier League', 'Manto premium do Chelsea, temporada 03/05. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (305).png'),
('Barcelona 16/17 - Retrô (Titular)', 109.9, 'La Liga', 'Manto premium do Barcelona, temporada 16/17. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (306).png'),
('Barcelona 16/17 - Retrô (Neymar Jr 11 - Costas)', 109.9, 'La Liga', 'Manto premium do Barcelona, temporada 16/17. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (307).png'),
('Milan 06/07 - Retrô (Titular)', 109.9, 'Serie A', 'Manto premium do Milan, temporada 06/07. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (308).png'),
('Real Madrid 05/06 - Retrô (Reserva - Costas)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 05/06. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (309).png'),
('Chelsea 03/05 - Retrô (Reserva - Costas)', 109.9, 'Premier League', 'Manto premium do Chelsea, temporada 03/05. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (310).png'),
('Inter de Milão 05/06 - Retrô (Titular - Costas)', 109.9, 'Serie A', 'Manto premium do Inter de Milão, temporada 05/06. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (311).png'),
('Barcelona 11/12 - Retrô (Titular - Costas)', 109.9, 'La Liga', 'Manto premium do Barcelona, temporada 11/12. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (312).png'),
('Manchester United 06/07 - Retrô (Goleiro Preta - Costas)', 109.9, 'Premier League', 'Manto premium do Manchester United, temporada 06/07. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (313).png'),
('São Paulo 00/01 - Retrô (Motorola - Costas)', 109.9, 'Brasileirão', 'Manto premium do São Paulo, temporada 00/01. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (314).png'),
('Fluminense 2012 - Retrô (Costas)', 109.9, 'Brasileirão', 'Manto premium do Fluminense, temporada 2012. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (315).png'),
('Atlético de Madrid 04/05 - Retrô (Costas)', 109.9, 'La Liga', 'Manto premium do Atlético de Madrid, temporada 04/05. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (316).png'),
('PSG 95/96 - Retrô (Titular - Costas)', 109.9, 'Ligue 1', 'Manto premium do PSG, temporada 95/96. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (317).png'),
('Flamengo 1995 - Retrô (Centenário - Costas)', 109.9, 'Brasileirão', 'Manto premium do Flamengo, temporada 1995. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (318).png'),
('Parma 98/99 - Retrô', 109.9, 'Serie A', 'Manto premium do Parma, temporada 98/99. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (319).png'),
('Manchester United 07/08 - Retrô (Goleiro Azul - Costas)', 109.9, 'Premier League', 'Manto premium do Manchester United, temporada 07/08. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (320).png'),
('PSG 95/96 - Retrô (Reserva - Costas)', 109.9, 'Ligue 1', 'Manto premium do PSG, temporada 95/96. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (321).png'),
('São Paulo 04/05 - Retrô (LG - Costas)', 109.9, 'Brasileirão', 'Manto premium do São Paulo, temporada 04/05. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (322).png'),
('Grêmio 95/96 - Retrô (Chevrolet - Costas)', 109.9, 'Brasileirão', 'Manto premium do Grêmio, temporada 95/96. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (323).png'),
('Arsenal 05/06 - Retrô (Highbury Farewell 2 - Costas)', 109.9, 'Premier League', 'Manto premium do Arsenal, temporada 05/06. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (324).png'),
('Barcelona 98/99 - Retrô (Titular - Costas)', 109.9, 'La Liga', 'Manto premium do Barcelona, temporada 98/99. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (325).png'),
('Santos 2011 - Retrô (BMG - Costas)', 109.9, 'Brasileirão', 'Manto premium do Santos, temporada 2011. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (326).png'),
('Borussia Dortmund 22/23 - Titular (Costas)', 109.9, 'Bundesliga', 'Manto premium do Borussia Dortmund, temporada 22/23. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (327).png'),
('Barcelona 98/99 - Retrô (Titular 2 - Costas)', 109.9, 'La Liga', 'Manto premium do Barcelona, temporada 98/99. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (328).png'),
('Real Madrid 14/15 - Retrô (Dragão - Costas)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 14/15. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (329).png'),
('Flamengo 2008 - Retrô (Reserva - Costas)', 109.9, 'Brasileirão', 'Manto premium do Flamengo, temporada 2008. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (330).png'),
('Real Madrid 99/00 - Retrô (Goleiro Teka)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 99/00. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (331).png'),
('Barcelona 12/13 - Retrô (Titular)', 109.9, 'La Liga', 'Manto premium do Barcelona, temporada 12/13. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (332).png'),
('Inter de Milão 09/10 - Retrô (Final Madrid)', 109.9, 'Serie A', 'Manto premium do Inter de Milão, temporada 09/10. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (333).png'),
('São Paulo 00/01 - Retrô (Motorola)', 109.9, 'Brasileirão', 'Manto premium do São Paulo, temporada 00/01. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (334).png'),
('Real Madrid 15/16 - Retrô (Goleiro Preta)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 15/16. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (335).png'),
('Fluminense 2012 - Retrô (Titular)', 109.9, 'Brasileirão', 'Manto premium do Fluminense, temporada 2012. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (336).png'),
('Atlético de Madrid 13/14 - Retrô (Titular)', 109.9, 'La Liga', 'Manto premium do Atlético de Madrid, temporada 13/14. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (337).png'),
('PSG 01/02 - Retrô (Opel)', 109.9, 'Ligue 1', 'Manto premium do PSG, temporada 01/02. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (338).png'),
('Real Madrid 17/18 - Retrô (Goleiro Verde)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 17/18. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (339).png'),
('São Paulo 04/05 - Retrô (LG)', 109.9, 'Brasileirão', 'Manto premium do São Paulo, temporada 04/05. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (340).png'),
('Parma 98/99 - Retrô (Costas)', 109.9, 'Serie A', 'Manto premium do Parma, temporada 98/99. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (341).png'),
('PSG 01/02 - Retrô (Opel 2)', 109.9, 'Ligue 1', 'Manto premium do PSG, temporada 01/02. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (342).png'),
('Brasil 2024 - Titular (Costas)', 109.9, 'Seleções', 'Manto premium do Brasil, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (343).png'),
('Barcelona 10/11 - Retrô (Titular)', 109.9, 'La Liga', 'Manto premium do Barcelona, temporada 10/11. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (344).png'),
('Grêmio 2003 - Retrô (Astra)', 109.9, 'Brasileirão', 'Manto premium do Grêmio, temporada 2003. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (345).png'),
('Arsenal 11/12 - Retrô (125 Anos)', 109.9, 'Premier League', 'Manto premium do Arsenal, temporada 11/12. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (346).png'),
('Borussia Dortmund 12/13 - Retrô (Titular)', 109.9, 'Bundesliga', 'Manto premium do Borussia Dortmund, temporada 12/13. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (347).png'),
('Santos 2012 - Retrô (Centenário)', 109.9, 'Brasileirão', 'Manto premium do Santos, temporada 2012. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (348).png'),
('Real Madrid 14/15 - Retrô (Dragão)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 14/15. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (349).png'),
('Barcelona 08/09 - Retrô (Final Roma)', 109.9, 'La Liga', 'Manto premium do Barcelona, temporada 08/09. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (350).png'),
('Flamengo 99/00 - Retrô (Lubrax)', 109.9, 'Brasileirão', 'Manto premium do Flamengo, temporada 99/00. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (351).png'),
('Barcelona 16/17 - Retrô (Messi 10 - Costas)', 109.9, 'La Liga', 'Manto premium do Barcelona, temporada 16/17. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (352).png'),
('São Paulo 2024 - Titular (Costas)', 109.9, 'Brasileirão', 'Manto premium do São Paulo, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (353).png'),
('São Paulo 2024 - Titular', 109.9, 'Brasileirão', 'Manto premium do São Paulo, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (354).png'),
('Flamengo 10/11 - Retrô (Manga Longa - Costas)', 109.9, 'Brasileirão', 'Manto premium do Flamengo, temporada 10/11. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (355).png'),
('Flamengo 10/11 - Retrô (Manga Longa)', 109.9, 'Brasileirão', 'Manto premium do Flamengo, temporada 10/11. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (356).png'),
('Barcelona 14/15 - Retrô (Neymar 11 - Costas)', 109.9, 'La Liga', 'Manto premium do Barcelona, temporada 14/15. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (357).png'),
('Barcelona 24/25 - Titular (Costas)', 109.9, 'La Liga', 'Manto premium do Barcelona, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (358).png'),
('Barcelona 24/25 - Titular', 109.9, 'La Liga', 'Manto premium do Barcelona, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (359).png'),
('RB Leipzig 23/24 - Titular (Costas)', 109.9, 'Bundesliga', 'Manto premium do RB Leipzig, temporada 23/24. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (360).png'),
('Santos 2024 - Titular (Costas)', 109.9, 'Brasileirão', 'Manto premium do Santos, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (361).png'),
('Santos 2024 - Titular', 109.9, 'Brasileirão', 'Manto premium do Santos, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (362).png'),
('Milan 23/24 - Titular (Costas)', 109.9, 'Serie A', 'Manto premium do Milan, temporada 23/24. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (363).png'),
('Milan 23/24 - Titular', 109.9, 'Serie A', 'Manto premium do Milan, temporada 23/24. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (364).png'),
('Santos 2012 - Retrô (Costas)', 109.9, 'Brasileirão', 'Manto premium do Santos, temporada 2012. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (365).png'),
('Barcelona 16/17 - Retrô (Reserva - Costas)', 109.9, 'La Liga', 'Manto premium do Barcelona, temporada 16/17. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (366).png'),
('RB Leipzig 23/24 - Titular', 109.9, 'Bundesliga', 'Manto premium do RB Leipzig, temporada 23/24. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (367).png'),
('Real Madrid 24/25 - Titular (Manga Longa)', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (368).png'),
('Santos 2012 - Retrô (Titular)', 109.9, 'Brasileirão', 'Manto premium do Santos, temporada 2012. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (369).png'),
('Barcelona 16/17 - Retrô (Reserva)', 109.9, 'La Liga', 'Manto premium do Barcelona, temporada 16/17. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (370).png'),
('Barcelona 24/25 - Titular (Manga Longa)', 109.9, 'La Liga', 'Manto premium do Barcelona, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (371).png'),
('Bahia 2024 - Quarto Uniforme', 109.9, 'Brasileirão', 'Manto premium do Bahia, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (372).png'),
('Grêmio 2024 - Titular', 109.9, 'Brasileirão', 'Manto premium do Grêmio, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (373).png'),
('Grêmio 2024 - Titular (Ângulo)', 109.9, 'Brasileirão', 'Manto premium do Grêmio, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (374).png'),
('Portugal 2024 - Ronaldo 7 (Costas)', 109.9, 'Seleções', 'Manto premium do Portugal, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (375).png'),
('Portugal 2024 - Titular', 109.9, 'Seleções', 'Manto premium do Portugal, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (376).png'),
('Real Madrid 24/25 - Uniforme de Treino', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (377).png'),
('Barcelona 24/25 - Reserva', 109.9, 'La Liga', 'Manto premium do Barcelona, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (378).png'),
('Barcelona 24/25 - Titular (Manga Curta)', 109.9, 'La Liga', 'Manto premium do Barcelona, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (379).png'),
('Argentina 2024 - Titular', 109.9, 'Seleções', 'Manto premium do Argentina, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (380).png'),
('Juventus 24/25 - Titular', 109.9, 'Serie A', 'Manto premium do Juventus, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (381).png'),
('Vasco 2024 - Terceiro Uniforme (Dinamite)', 109.9, 'Brasileirão', 'Manto premium do Vasco, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (382).png'),
('Vasco 2024 - Terceiro Uniforme (Costas)', 109.9, 'Brasileirão', 'Manto premium do Vasco, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (383).png'),
('Internacional 2024 - Reserva (Costas)', 109.9, 'Brasileirão', 'Manto premium do Internacional, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (384).png'),
('Real Madrid 24/25 - Titular', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (385).png'),
('Flamengo 2024 - Reserva', 109.9, 'Brasileirão', 'Manto premium do Flamengo, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (386).png'),
('Flamengo 2024 - Titular', 109.9, 'Brasileirão', 'Manto premium do Flamengo, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (387).png'),
('Vasco 23/24 - Terceiro Uniforme (Resposta Histórica)', 109.9, 'Brasileirão', 'Manto premium do Vasco, temporada 23/24. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (388).png'),
('Real Madrid 24/25 - Titular 2', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (389).png'),
('Real Madrid 24/25 - Terceiro Uniforme', 109.9, 'La Liga', 'Manto premium do Real Madrid, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (390).png'),
('Barcelona 24/25 - Titular (Versão Jogador)', 109.9, 'La Liga', 'Manto premium do Barcelona, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (391).png'),
('Bahia 2024 - Titular', 109.9, 'Brasileirão', 'Manto premium do Bahia, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (392).png'),
('Espanha 2024 - Titular', 109.9, 'Seleções', 'Manto premium do Espanha, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (393).png'),
('Argentina 2024 - Titular (Costas)', 109.9, 'Seleções', 'Manto premium do Argentina, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (394).png'),
('Flamengo Retrô - Titular (Adidas Originals)', 109.9, 'Brasileirão', 'Manto premium do Flamengo, temporada Retrô. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (395).png'),
('Botafogo 2024 - Reserva', 109.9, 'Brasileirão', 'Manto premium do Botafogo, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (396).png'),
('Botafogo 2024 - Titular', 109.9, 'Brasileirão', 'Manto premium do Botafogo, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (397).png'),
('Botafogo 2024 - Reserva (Costas - Soares 9)', 109.9, 'Brasileirão', 'Manto premium do Botafogo, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (398).png'),
('Internacional 2024 - Titular', 109.9, 'Brasileirão', 'Manto premium do Internacional, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (399).png'),
('Fluminense 2024 - Titular', 109.9, 'Brasileirão', 'Manto premium do Fluminense, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (400).png'),
('Grêmio 2024 - Titular (Costas - 10)', 109.9, 'Brasileirão', 'Manto premium do Grêmio, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (401).png'),
('Internacional 2024 - Titular 2', 109.9, 'Brasileirão', 'Manto premium do Internacional, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (402).png'),
('Vasco 23/24 - Terceiro Uniforme (Costas)', 109.9, 'Brasileirão', 'Manto premium do Vasco, temporada 23/24. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (403).png'),
('Juventus 24/25 - Terceiro Uniforme', 109.9, 'Serie A', 'Manto premium do Juventus, temporada 24/25. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (404).png'),
('Flamengo 2024 - Treino (Azul)', 109.9, 'Brasileirão', 'Manto premium do Flamengo, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (405).png'),
('Flamengo 2024 - Quarto Uniforme (Blackout)', 109.9, 'Brasileirão', 'Manto premium do Flamengo, temporada 2024. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (406).png'),
('Barcelona 15/16 - Retrô (Titular)', 109.9, 'La Liga', 'Manto premium do Barcelona, temporada 15/16. Tecido de alta qualidade e acabamento impecável.', '/camisas/@carinhacriativo (407).png');
