-- Script de ATUALIZAÇÃO MASSIVA dos atributos das camisas

UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (1).png';
UPDATE public.products SET team = 'Flamengo', league = 'Brasileirão', version = 'Retrô', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (2).png';
UPDATE public.products SET team = 'Flamengo', league = 'Brasileirão', version = 'Retrô', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (3).png';
UPDATE public.products SET team = 'Chelsea', league = 'Premier League', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (4).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (5).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (6).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (7).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (8).png';
UPDATE public.products SET team = 'Santos', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (9).png';
UPDATE public.products SET team = 'Inter de Milão', league = 'Serie A', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (10).png';
UPDATE public.products SET team = 'Manchester United', league = 'Premier League', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (11).png';
UPDATE public.products SET team = 'Barcelona', league = 'La Liga', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (12).png';
UPDATE public.products SET team = 'Argentina', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (13).png';
UPDATE public.products SET team = 'Espanha', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (14).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (15).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (16).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (17).png';
UPDATE public.products SET team = 'Manchester United', league = 'Premier League', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (18).png';
UPDATE public.products SET team = 'Manchester United', league = 'Premier League', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (19).png';
UPDATE public.products SET team = 'Milan', league = 'Serie A', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (20).png';
UPDATE public.products SET team = 'Milan', league = 'Serie A', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (21).png';
UPDATE public.products SET team = 'PSG', league = 'International', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (22).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (23).png';
UPDATE public.products SET team = 'PSG', league = 'International', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (24).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (25).png';
UPDATE public.products SET team = 'Barcelona', league = 'La Liga', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (26).png';
UPDATE public.products SET team = 'Al-Hilal', league = 'International', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (27).png';
UPDATE public.products SET team = 'Alemanha', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (28).png';
UPDATE public.products SET team = 'Croácia', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (29).png';
UPDATE public.products SET team = 'Flamengo', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (30).png';
UPDATE public.products SET team = 'Flamengo', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (31).png';
UPDATE public.products SET team = 'França', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (32).png';
UPDATE public.products SET team = 'Inglaterra', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (33).png';
UPDATE public.products SET team = 'Portugal', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (34).png';
UPDATE public.products SET team = 'Portugal', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (35).png';
UPDATE public.products SET team = 'PSG', league = 'Internacional', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (36).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (37).png';
UPDATE public.products SET team = 'Flamengo', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (38).png';
UPDATE public.products SET team = 'Brasil', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (39).png';
UPDATE public.products SET team = 'Barcelona', league = 'La Liga', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (40).png';
UPDATE public.products SET team = 'Brasil', league = 'Seleções', version = 'Retrô', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (41).png';
UPDATE public.products SET team = 'Brasil', league = 'Seleções', version = 'Retrô', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (42).png';
UPDATE public.products SET team = 'Brasil', league = 'Seleções', version = 'Retrô', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (43).png';
UPDATE public.products SET team = 'Manchester United', league = 'Premier League', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (44).png';
UPDATE public.products SET team = 'Holanda', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (45).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (46).png';
UPDATE public.products SET team = 'Manchester United', league = 'Premier League', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (47).png';
UPDATE public.products SET team = 'Arsenal', league = 'Premier League', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (48).png';
UPDATE public.products SET team = 'Arsenal', league = 'Premier League', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (49).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (50).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (51).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (52).png';
UPDATE public.products SET team = 'Brasil', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (53).png';
UPDATE public.products SET team = 'Manchester United', league = 'Premier League', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (54).png';
UPDATE public.products SET team = 'Barcelona', league = 'La Liga', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (55).png';
UPDATE public.products SET team = 'Barcelona', league = 'La Liga', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (56).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (57).png';
UPDATE public.products SET team = 'Barcelona', league = 'La Liga', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (58).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (59).png';
UPDATE public.products SET team = 'Manchester United', league = 'Premier League', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (60).png';
UPDATE public.products SET team = 'Barcelona', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (61).png';
UPDATE public.products SET team = 'Barcelona', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (62).png';
UPDATE public.products SET team = 'Borussia Dortmund', league = 'Bundesliga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (63).png';
UPDATE public.products SET team = 'Manchester City', league = 'Premier League', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (64).png';
UPDATE public.products SET team = 'Manchester United', league = 'Premier League', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (65).png';
UPDATE public.products SET team = 'Argentina', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (66).png';
UPDATE public.products SET team = 'Argentina', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (67).png';
UPDATE public.products SET team = 'Brasil', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (68).png';
UPDATE public.products SET team = 'França', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (69).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (70).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (71).png';
UPDATE public.products SET team = 'Manchester City', league = 'Premier League', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (72).png';
UPDATE public.products SET team = 'Brasil', league = 'Seleções', version = 'Retrô', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (73).png';
UPDATE public.products SET team = 'Barcelona', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (74).png';
UPDATE public.products SET team = 'Vasco da Gama', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (75).png';
UPDATE public.products SET team = 'Palmeiras', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (76).png';
UPDATE public.products SET team = 'São Paulo', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (77).png';
UPDATE public.products SET team = 'Grêmio', league = 'Brasileirão', version = 'Retrô', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (78).png';
UPDATE public.products SET team = 'Chelsea', league = 'Premier League', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (79).png';
UPDATE public.products SET team = 'Grêmio', league = 'Brasileirão', version = 'Retrô', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (80).png';
UPDATE public.products SET team = 'Palmeiras', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (81).png';
UPDATE public.products SET team = 'Borussia Dortmund', league = 'Bundesliga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (82).png';
UPDATE public.products SET team = 'Argentina', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (83).png';
UPDATE public.products SET team = 'Atlético de Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (84).png';
UPDATE public.products SET team = 'Flamengo', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (85).png';
UPDATE public.products SET team = 'Botafogo', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (86).png';
UPDATE public.products SET team = 'Botafogo', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (87).png';
UPDATE public.products SET team = 'Santos', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (88).png';
UPDATE public.products SET team = 'Santos', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (89).png';
UPDATE public.products SET team = 'Corinthians', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (90).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (91).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (92).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (93).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (94).png';
UPDATE public.products SET team = 'Argentina', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (95).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (96).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (97).png';
UPDATE public.products SET team = 'Real Madrid', league = 'Especiais', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (98).png';
UPDATE public.products SET team = 'Real Madrid', league = 'Especiais', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (99).png';
UPDATE public.products SET team = 'Espanha', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (100).png';
UPDATE public.products SET team = 'Espanha', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (101).png';
UPDATE public.products SET team = 'Manchester United', league = 'Premier League', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (102).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (103).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (104).png';
UPDATE public.products SET team = 'Bayern de Munique', league = 'Bundesliga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (105).png';
UPDATE public.products SET team = 'Bayern de Munique', league = 'Bundesliga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (106).png';
UPDATE public.products SET team = 'Colômbia', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (107).png';
UPDATE public.products SET team = 'Colômbia', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (108).png';
UPDATE public.products SET team = 'Cruzeiro', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (109).png';
UPDATE public.products SET team = 'Cruzeiro', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (110).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (111).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (112).png';
UPDATE public.products SET team = 'Borussia Dortmund', league = 'Bundesliga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (113).png';
UPDATE public.products SET team = 'Brasil', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (114).png';
UPDATE public.products SET team = 'Palmeiras', league = 'Brasileirão', version = 'Retrô', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (115).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (116).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (117).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (118).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (119).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (120).png';
UPDATE public.products SET team = 'Santos', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (121).png';
UPDATE public.products SET team = 'Santos', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (122).png';
UPDATE public.products SET team = 'Portugal', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (123).png';
UPDATE public.products SET team = 'Manchester City', league = 'Premier League', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (124).png';
UPDATE public.products SET team = 'Vasco da Gama', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (125).png';
UPDATE public.products SET team = 'Vasco da Gama', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (126).png';
UPDATE public.products SET team = 'Flamengo', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (127).png';
UPDATE public.products SET team = 'Vasco da Gama', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (128).png';
UPDATE public.products SET team = 'Vasco da Gama', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (129).png';
UPDATE public.products SET team = 'Barcelona', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (130).png';
UPDATE public.products SET team = 'Holanda', league = 'Seleções', version = 'Retrô', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (131).png';
UPDATE public.products SET team = 'Manchester United', league = 'Premier League', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (132).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (133).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (134).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (135).png';
UPDATE public.products SET team = 'Portugal', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (136).png';
UPDATE public.products SET team = 'Portugal', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (137).png';
UPDATE public.products SET team = 'Brasil', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (138).png';
UPDATE public.products SET team = 'Argentina', league = 'Seleções', version = 'Retrô', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (139).png';
UPDATE public.products SET team = 'Alemanha', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (140).png';
UPDATE public.products SET team = 'Alemanha', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (141).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (142).png';
UPDATE public.products SET team = 'Portugal', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (143).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (144).png';
UPDATE public.products SET team = 'França', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (145).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (146).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (147).png';
UPDATE public.products SET team = 'França', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (148).png';
UPDATE public.products SET team = 'França', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (149).png';
UPDATE public.products SET team = 'Chelsea', league = 'Premier League', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (150).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (151).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (152).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (153).png';
UPDATE public.products SET team = 'Vasco da Gama', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (154).png';
UPDATE public.products SET team = 'Vasco da Gama', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (155).png';
UPDATE public.products SET team = 'São Paulo', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (156).png';
UPDATE public.products SET team = 'São Paulo', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (157).png';
UPDATE public.products SET team = 'Palmeiras', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (158).png';
UPDATE public.products SET team = 'Palmeiras', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (159).png';
UPDATE public.products SET team = 'México', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (160).png';
UPDATE public.products SET team = 'Grêmio', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (161).png';
UPDATE public.products SET team = 'Corinthians', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (162).png';
UPDATE public.products SET team = 'Corinthians', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (163).png';
UPDATE public.products SET team = 'Colômbia', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (164).png';
UPDATE public.products SET team = 'Chile', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (165).png';
UPDATE public.products SET team = 'Atlético Mineiro', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (166).png';
UPDATE public.products SET team = 'Argentina', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (167).png';
UPDATE public.products SET team = 'Espanha', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (168).png';
UPDATE public.products SET team = 'Borussia Dortmund', league = 'Bundesliga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (169).png';
UPDATE public.products SET team = 'Liverpool', league = 'Premier League', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (170).png';
UPDATE public.products SET team = 'Corinthians', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (171).png';
UPDATE public.products SET team = 'Corinthians', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (172).png';
UPDATE public.products SET team = 'PSG', league = 'Ligue 1', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (173).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (174).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (175).png';
UPDATE public.products SET team = 'Barcelona', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (176).png';
UPDATE public.products SET team = 'Fluminense', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (177).png';
UPDATE public.products SET team = 'Atlético de Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (178).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (179).png';
UPDATE public.products SET team = 'Palmeiras', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (180).png';
UPDATE public.products SET team = 'Bayern de Munique', league = 'Bundesliga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (181).png';
UPDATE public.products SET team = 'Bayern de Munique', league = 'Bundesliga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (182).png';
UPDATE public.products SET team = 'AS Roma', league = 'Serie A', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (183).png';
UPDATE public.products SET team = 'Aston Villa', league = 'Premier League', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (184).png';
UPDATE public.products SET team = 'Borussia Dortmund', league = 'Bundesliga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (185).png';
UPDATE public.products SET team = 'Borussia Dortmund', league = 'Bundesliga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (186).png';
UPDATE public.products SET team = 'Aston Villa', league = 'Premier League', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (187).png';
UPDATE public.products SET team = 'Milan', league = 'Serie A', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (188).png';
UPDATE public.products SET team = 'Juventus', league = 'Serie A', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (189).png';
UPDATE public.products SET team = 'Juventus', league = 'Serie A', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (190).png';
UPDATE public.products SET team = 'Milan', league = 'Serie A', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (191).png';
UPDATE public.products SET team = 'Palmeiras', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (192).png';
UPDATE public.products SET team = 'Palmeiras', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (193).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (194).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (195).png';
UPDATE public.products SET team = 'Manchester United', league = 'Premier League', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (196).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (197).png';
UPDATE public.products SET team = 'Bayern de Munique', league = 'Bundesliga', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (198).png';
UPDATE public.products SET team = 'Bayern de Munique', league = 'Bundesliga', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (199).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (200).png';
UPDATE public.products SET team = 'Inglaterra', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (201).png';
UPDATE public.products SET team = 'Inglaterra', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (202).png';
UPDATE public.products SET team = 'Napoli', league = 'Serie A', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (203).png';
UPDATE public.products SET team = 'Napoli', league = 'Serie A', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (204).png';
UPDATE public.products SET team = 'França', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (205).png';
UPDATE public.products SET team = 'França', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (206).png';
UPDATE public.products SET team = 'Borussia Dortmund', league = 'Bundesliga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (207).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (208).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (209).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (210).png';
UPDATE public.products SET team = 'Cruzeiro', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (211).png';
UPDATE public.products SET team = 'Cruzeiro', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (212).png';
UPDATE public.products SET team = 'Atlético Mineiro', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (213).png';
UPDATE public.products SET team = 'Atlético Mineiro', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (214).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (215).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (216).png';
UPDATE public.products SET team = 'Manchester United', league = 'Premier League', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (217).png';
UPDATE public.products SET team = 'Manchester United', league = 'Premier League', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (218).png';
UPDATE public.products SET team = 'Palmeiras', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (219).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (220).png';
UPDATE public.products SET team = 'Barcelona', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (221).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (222).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (223).png';
UPDATE public.products SET team = 'Flamengo', league = 'Brasileirão', version = 'Retrô', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (224).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (225).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (226).png';
UPDATE public.products SET team = 'Bayer Leverkusen', league = 'Bundesliga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (227).png';
UPDATE public.products SET team = 'Bayer Leverkusen', league = 'Bundesliga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (228).png';
UPDATE public.products SET team = 'Napoli', league = 'Serie A', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (229).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (230).png';
UPDATE public.products SET team = 'Bayern de Munique', league = 'Bundesliga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (231).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (232).png';
UPDATE public.products SET team = 'Bayern de Munique', league = 'Bundesliga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (233).png';
UPDATE public.products SET team = 'Napoli', league = 'Serie A', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (234).png';
UPDATE public.products SET team = 'Santos', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (235).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (236).png';
UPDATE public.products SET team = 'Borussia Dortmund', league = 'Bundesliga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (237).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (238).png';
UPDATE public.products SET team = 'Arsenal', league = 'Premier League', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (239).png';
UPDATE public.products SET team = 'Vasco da Gama', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (240).png';
UPDATE public.products SET team = 'Vasco da Gama', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (241).png';
UPDATE public.products SET team = 'Inter de Milão', league = 'Serie A', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (242).png';
UPDATE public.products SET team = 'Inter de Milão', league = 'Serie A', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (243).png';
UPDATE public.products SET team = 'AS Roma', league = 'Serie A', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (244).png';
UPDATE public.products SET team = 'AS Roma', league = 'Serie A', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (245).png';
UPDATE public.products SET team = 'Bélgica', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (246).png';
UPDATE public.products SET team = 'Bélgica', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (247).png';
UPDATE public.products SET team = 'Alemanha', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (248).png';
UPDATE public.products SET team = 'Alemanha', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (249).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (250).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (251).png';
UPDATE public.products SET team = 'Barcelona', league = 'La Liga', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (252).png';
UPDATE public.products SET team = 'Barcelona', league = 'La Liga', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (253).png';
UPDATE public.products SET team = 'Brasil', league = 'Seleções', version = 'Retrô', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (254).png';
UPDATE public.products SET team = 'Brasil', league = 'Seleções', version = 'Retrô', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (255).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (256).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (257).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (258).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (259).png';
UPDATE public.products SET team = 'Fluminense', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (260).png';
UPDATE public.products SET team = 'Fluminense', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (261).png';
UPDATE public.products SET team = 'Inter de Milão', league = 'Serie A', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (262).png';
UPDATE public.products SET team = 'Inter de Milão', league = 'Serie A', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (263).png';
UPDATE public.products SET team = 'Inter de Milão', league = 'Serie A', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (264).png';
UPDATE public.products SET team = 'Barcelona', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (265).png';
UPDATE public.products SET team = 'Barcelona', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (266).png';
UPDATE public.products SET team = 'Inter Miami', league = 'MLS', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (267).png';
UPDATE public.products SET team = 'Inter Miami', league = 'MLS', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (268).png';
UPDATE public.products SET team = 'Croácia', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (269).png';
UPDATE public.products SET team = 'Croácia', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (270).png';
UPDATE public.products SET team = 'Vasco da Gama', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (271).png';
UPDATE public.products SET team = 'Botafogo', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (272).png';
UPDATE public.products SET team = 'Botafogo', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (273).png';
UPDATE public.products SET team = 'Barcelona', league = 'La Liga', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (274).png';
UPDATE public.products SET team = 'Barcelona', league = 'La Liga', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (275).png';
UPDATE public.products SET team = 'Arsenal', league = 'Premier League', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (276).png';
UPDATE public.products SET team = 'Argentina', league = 'Seleções', version = 'Retrô', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (277).png';
UPDATE public.products SET team = 'Argentina', league = 'Seleções', version = 'Retrô', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (278).png';
UPDATE public.products SET team = 'Al-Nassr', league = 'Saudi Pro League', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (279).png';
UPDATE public.products SET team = 'Al-Nassr', league = 'Saudi Pro League', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (280).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (281).png';
UPDATE public.products SET team = 'Milan', league = 'Serie A', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (282).png';
UPDATE public.products SET team = 'PSG', league = 'Ligue 1', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (283).png';
UPDATE public.products SET team = 'PSG', league = 'Ligue 1', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (284).png';
UPDATE public.products SET team = 'Liverpool', league = 'Premier League', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (285).png';
UPDATE public.products SET team = 'Liverpool', league = 'Premier League', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (286).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (287).png';
UPDATE public.products SET team = 'Atlético de Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (288).png';
UPDATE public.products SET team = 'Atlético de Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (289).png';
UPDATE public.products SET team = 'Borussia Dortmund', league = 'Bundesliga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (290).png';
UPDATE public.products SET team = 'Borussia Dortmund', league = 'Bundesliga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (291).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (292).png';
UPDATE public.products SET team = 'Bayern de Munique', league = 'Bundesliga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (293).png';
UPDATE public.products SET team = 'Bayern de Munique', league = 'Bundesliga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (294).png';
UPDATE public.products SET team = 'França', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (295).png';
UPDATE public.products SET team = 'Brasil', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (296).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (297).png';
UPDATE public.products SET team = 'Palmeiras', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (298).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (299).png';
UPDATE public.products SET team = 'Manchester United', league = 'Premier League', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (300).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (301).png';
UPDATE public.products SET team = 'Manchester United', league = 'Premier League', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (302).png';
UPDATE public.products SET team = 'Milan', league = 'Serie A', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (303).png';
UPDATE public.products SET team = 'Manchester United', league = 'Premier League', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (304).png';
UPDATE public.products SET team = 'Chelsea', league = 'Premier League', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (305).png';
UPDATE public.products SET team = 'Barcelona', league = 'La Liga', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (306).png';
UPDATE public.products SET team = 'Barcelona', league = 'La Liga', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (307).png';
UPDATE public.products SET team = 'Milan', league = 'Serie A', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (308).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (309).png';
UPDATE public.products SET team = 'Chelsea', league = 'Premier League', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (310).png';
UPDATE public.products SET team = 'Inter de Milão', league = 'Serie A', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (311).png';
UPDATE public.products SET team = 'Barcelona', league = 'La Liga', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (312).png';
UPDATE public.products SET team = 'Manchester United', league = 'Premier League', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (313).png';
UPDATE public.products SET team = 'São Paulo', league = 'Brasileirão', version = 'Retrô', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (314).png';
UPDATE public.products SET team = 'Fluminense', league = 'Brasileirão', version = 'Retrô', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (315).png';
UPDATE public.products SET team = 'Atlético de Madrid', league = 'La Liga', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (316).png';
UPDATE public.products SET team = 'PSG', league = 'Ligue 1', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (317).png';
UPDATE public.products SET team = 'Flamengo', league = 'Brasileirão', version = 'Retrô', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (318).png';
UPDATE public.products SET team = 'Parma', league = 'Serie A', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (319).png';
UPDATE public.products SET team = 'Manchester United', league = 'Premier League', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (320).png';
UPDATE public.products SET team = 'PSG', league = 'Ligue 1', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (321).png';
UPDATE public.products SET team = 'São Paulo', league = 'Brasileirão', version = 'Retrô', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (322).png';
UPDATE public.products SET team = 'Grêmio', league = 'Brasileirão', version = 'Retrô', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (323).png';
UPDATE public.products SET team = 'Arsenal', league = 'Premier League', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (324).png';
UPDATE public.products SET team = 'Barcelona', league = 'La Liga', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (325).png';
UPDATE public.products SET team = 'Santos', league = 'Brasileirão', version = 'Retrô', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (326).png';
UPDATE public.products SET team = 'Borussia Dortmund', league = 'Bundesliga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (327).png';
UPDATE public.products SET team = 'Barcelona', league = 'La Liga', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (328).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (329).png';
UPDATE public.products SET team = 'Flamengo', league = 'Brasileirão', version = 'Retrô', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (330).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (331).png';
UPDATE public.products SET team = 'Barcelona', league = 'La Liga', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (332).png';
UPDATE public.products SET team = 'Inter de Milão', league = 'Serie A', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (333).png';
UPDATE public.products SET team = 'São Paulo', league = 'Brasileirão', version = 'Retrô', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (334).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (335).png';
UPDATE public.products SET team = 'Fluminense', league = 'Brasileirão', version = 'Retrô', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (336).png';
UPDATE public.products SET team = 'Atlético de Madrid', league = 'La Liga', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (337).png';
UPDATE public.products SET team = 'PSG', league = 'Ligue 1', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (338).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (339).png';
UPDATE public.products SET team = 'São Paulo', league = 'Brasileirão', version = 'Retrô', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (340).png';
UPDATE public.products SET team = 'Parma', league = 'Serie A', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (341).png';
UPDATE public.products SET team = 'PSG', league = 'Ligue 1', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (342).png';
UPDATE public.products SET team = 'Brasil', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (343).png';
UPDATE public.products SET team = 'Barcelona', league = 'La Liga', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (344).png';
UPDATE public.products SET team = 'Grêmio', league = 'Brasileirão', version = 'Retrô', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (345).png';
UPDATE public.products SET team = 'Arsenal', league = 'Premier League', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (346).png';
UPDATE public.products SET team = 'Borussia Dortmund', league = 'Bundesliga', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (347).png';
UPDATE public.products SET team = 'Santos', league = 'Brasileirão', version = 'Retrô', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (348).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (349).png';
UPDATE public.products SET team = 'Barcelona', league = 'La Liga', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (350).png';
UPDATE public.products SET team = 'Flamengo', league = 'Brasileirão', version = 'Retrô', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (351).png';
UPDATE public.products SET team = 'Barcelona', league = 'La Liga', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (352).png';
UPDATE public.products SET team = 'São Paulo', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (353).png';
UPDATE public.products SET team = 'São Paulo', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (354).png';
UPDATE public.products SET team = 'Flamengo', league = 'Brasileirão', version = 'Retrô', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (355).png';
UPDATE public.products SET team = 'Flamengo', league = 'Brasileirão', version = 'Retrô', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (356).png';
UPDATE public.products SET team = 'Barcelona', league = 'La Liga', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (357).png';
UPDATE public.products SET team = 'Barcelona', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (358).png';
UPDATE public.products SET team = 'Barcelona', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (359).png';
UPDATE public.products SET team = 'RB Leipzig', league = 'Bundesliga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (360).png';
UPDATE public.products SET team = 'Santos', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (361).png';
UPDATE public.products SET team = 'Santos', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (362).png';
UPDATE public.products SET team = 'Milan', league = 'Serie A', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (363).png';
UPDATE public.products SET team = 'Milan', league = 'Serie A', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (364).png';
UPDATE public.products SET team = 'Santos', league = 'Brasileirão', version = 'Retrô', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (365).png';
UPDATE public.products SET team = 'Barcelona', league = 'La Liga', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (366).png';
UPDATE public.products SET team = 'RB Leipzig', league = 'Bundesliga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (367).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (368).png';
UPDATE public.products SET team = 'Santos', league = 'Brasileirão', version = 'Retrô', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (369).png';
UPDATE public.products SET team = 'Barcelona', league = 'La Liga', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (370).png';
UPDATE public.products SET team = 'Barcelona', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (371).png';
UPDATE public.products SET team = 'Bahia', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (372).png';
UPDATE public.products SET team = 'Grêmio', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (373).png';
UPDATE public.products SET team = 'Grêmio', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (374).png';
UPDATE public.products SET team = 'Portugal', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (375).png';
UPDATE public.products SET team = 'Portugal', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (376).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (377).png';
UPDATE public.products SET team = 'Barcelona', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (378).png';
UPDATE public.products SET team = 'Barcelona', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (379).png';
UPDATE public.products SET team = 'Argentina', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (380).png';
UPDATE public.products SET team = 'Juventus', league = 'Serie A', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (381).png';
UPDATE public.products SET team = 'Vasco', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (382).png';
UPDATE public.products SET team = 'Vasco', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (383).png';
UPDATE public.products SET team = 'Internacional', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (384).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (385).png';
UPDATE public.products SET team = 'Flamengo', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (386).png';
UPDATE public.products SET team = 'Flamengo', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (387).png';
UPDATE public.products SET team = 'Vasco', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (388).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (389).png';
UPDATE public.products SET team = 'Real Madrid', league = 'La Liga', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (390).png';
UPDATE public.products SET team = 'Barcelona', league = 'La Liga', version = 'Jogador', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (391).png';
UPDATE public.products SET team = 'Bahia', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (392).png';
UPDATE public.products SET team = 'Espanha', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (393).png';
UPDATE public.products SET team = 'Argentina', league = 'Seleções', version = 'Torcedor', category = 'Seleções' WHERE image = '/camisas/@carinhacriativo (394).png';
UPDATE public.products SET team = 'Flamengo', league = 'Brasileirão', version = 'Retrô', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (395).png';
UPDATE public.products SET team = 'Botafogo', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (396).png';
UPDATE public.products SET team = 'Botafogo', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (397).png';
UPDATE public.products SET team = 'Botafogo', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (398).png';
UPDATE public.products SET team = 'Internacional', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (399).png';
UPDATE public.products SET team = 'Fluminense', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (400).png';
UPDATE public.products SET team = 'Grêmio', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (401).png';
UPDATE public.products SET team = 'Internacional', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (402).png';
UPDATE public.products SET team = 'Vasco', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (403).png';
UPDATE public.products SET team = 'Juventus', league = 'Serie A', version = 'Torcedor', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (404).png';
UPDATE public.products SET team = 'Flamengo', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (405).png';
UPDATE public.products SET team = 'Flamengo', league = 'Brasileirão', version = 'Torcedor', category = 'Brasileirão' WHERE image = '/camisas/@carinhacriativo (406).png';
UPDATE public.products SET team = 'Barcelona', league = 'La Liga', version = 'Retrô', category = 'Internacionais' WHERE image = '/camisas/@carinhacriativo (407).png';
