import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  pt: {
    nav_home: 'Home',
    nav_br: 'Brasileirão',
    nav_intl: 'Internacionais',
    nav_retro: 'Retrô',
    nav_tenis: 'Tênis',
    nav_nba: 'NBA',
    nav_streetwear: 'Streetwear',
    top_bar_announcement: '🍁 Free Shipping Across Canada',
    nav_admin: 'Admin',
    hero_title_part1: 'VISTA AS CORES DO SEU TIME MESMO ',
    hero_title_accent: 'LONGE DE CASA',
    hero_subtitle: 'Camisas brasileiras, europeias e internacionais | Envio para Canadá e EUA',
    hero_satisfied_clients: '⭐ +400 clientes satisfeitos no Canadá & EUA',
    hero_shipping_all: 'Canadá & EUA',
    hero_shipping_calgary: 'Entrega prioritária para Calgary',
    hero_shipping_guaranteed: 'Entrega garantida',
    hero_shipping_moneyback: 'Ou devolução do dinheiro',
    hero_btn_guarantee: 'GARANTIR MINHA CAMISA',
    hero_btn_view_all: 'Ver todas as camisas',
    btn_shop_now: 'Ver Catálogo',
    section_favorites: 'Nossas Queridinhas',
    section_best_seller: 'Mais Vendida do Momento',
    section_new: 'Lançamento',
    section_categories: 'Navegue por Categorias',
    promo_banner_title: '🔥 OFERTA ESPECIAL',
    promo_banner_combo2: '2 Camisas',
    promo_banner_combo3: '3 Camisas',
    promo_banner_from: 'De',
    promo_banner_for: 'por apenas',
    promo_banner_each: 'cada',
    promo_banner_savings: 'Economia de',
    promo_banner_apply: 'Aplicar desconto',
    promo_banner_best_offer: 'Maior Desconto',
    product_price_transfer: 'no e-Transfer',
    product_customization: 'Personalização',
    product_customization_none: 'Não',
    product_customization_yes: 'Sim',
    product_size: 'Tamanho',
    product_qty: 'Quantidade',
    product_buy_now: 'COMPRAR AGORA',
    product_wholesale_table: '🔥 Tabela de Atacado / Combos',
    product_wholesale_unit: 'unit.',
    product_wholesale_each: 'cada',
    product_from: 'A partir de',
    product_composition: 'Itens Inclusos',
    product_composition_full: 'Kit Completo (Camisa + Calção)',
    product_composition_only_shirt: 'Apenas Camisa',
    product_coming_soon: 'Tenho Interesse (Pré-Venda)',
    interest_modal_title: 'Tenho Interesse neste Lançamento',
    interest_modal_subtitle: 'Cadastre seu interesse para ser avisado em primeira mão assim que este manto estiver disponível para venda.',
    interest_name_label: 'Seu Nome',
    interest_whatsapp_label: 'Seu WhatsApp (Ex: +1 403 123 4567)',
    interest_size_label: 'Tamanho de Interesse',
    interest_submit: 'REGISTRAR MEU INTERESSE',
    interest_success_title: 'Sucesso!',
    interest_success_msg: 'Seu interesse foi registrado com sucesso! Entraremos em contato assim que este modelo for lançado.',
    interest_success_whatsapp: 'Chamar no WhatsApp do Suporte',
    cart_title: 'Minha Sacola',
    cart_empty: 'Sua sacola está vazia.',
    cart_subtotal: 'Subtotal',
    cart_discount: 'Desconto de Volume',
    cart_total: 'Total',
    cart_checkout: 'Finalizar Pedido',
    cart_continue_shopping: 'Continuar Comprando',
    sales_popup_bought: 'comprou',
    sales_popup_time: 'Comprado',
    stats_clients: 'Clientes satisfeitos no Canadá & EUA',
    stats_shipping: 'Taxa de envio no prazo',
    stats_whatsapp: 'Resposta média no WhatsApp',
    stats_payment: 'Pagamento seguro garantido',
    section_favorites_title: 'As Queridinhas 🇧🇷',
    section_favorites_subtitle: 'Deslize para ver os mantos sagrados mais pedidos.',
    promo_footer_note: '* Preços baseados na camisa padrão. O desconto se aplica a qualquer peça. Adicione à sacola e a mágica acontece!',
    customization_title: 'Deixe sua camisa única ✍️',
    customization_subtitle: 'Você poderá solicitar a personalização com a mesma fonte oficial dos jogadores diretamente dentro das opções do produto.',
    customization_item1: 'Nome + Número',
    customization_item2: 'Patch de Campeonatos',
    emotional_title: 'Porque ser torcedor não tem distância 🇧🇷',
    emotional_text: 'A saudade do seu país e a paixão pelo futebol vivem na mesma gaveta. Entregamos a qualidade de jogador profissional diretamente na sua porta no Canadá e EUA.',
    social_proof_title: 'Voz da Arquibancada 🗣️',
    social_proof_subtitle: 'Desde 2022, conectando brasileiros em todo o Canadá & EUA com seus mantos favoritos.',
    social_proof_client_since: 'Cliente desde',
    social_proof_swipe: 'Deslize lateralmente para ler mais →',
    faq_title: 'Dúvidas Frequentes',
    faqs: [
      { question: 'As camisas da iFooty são originais?', answer: 'Não. Somos transparentes: nossas camisas são réplicas premium tailandesas (Thai AAA), consideradas as melhores do mundo em qualidade de réplica. Usamos os mesmos tecidos dry-fit, costuras reforçadas e acabamentos dos modelos oficiais, por uma fração do preço.' },
      { question: 'Por que o preço é menor que nas lojas oficiais?', answer: 'As camisas oficiais Nike/Adidas custam CA$150-200 porque você paga pela licença da marca, logística oficial e margem da varejista. Nossas réplicas Thai AAA entregam 99% da qualidade visual e de material sem esses custos, ficando entre CA$47.90 e CA$74.90.' },
      { question: 'Posso cancelar depois de personalizar?', answer: 'Infelizmente não. Personalização é feita sob demanda e torna a camisa exclusiva sua — não conseguimos revender. Por isso, confira nome, número e tamanho antes de finalizar a compra. Pedidos personalizados não aceitam troca por arrependimento (apenas defeito de fábrica).' },
      { question: 'Quais formas de pagamento vocês aceitam?', answer: 'Aceitamos pagamento via PayPal (cartão de crédito, débito ou saldo PayPal) e atendimento direto via WhatsApp. Também aceitamos E‑transfer Interac.' },
      { question: 'É seguro comprar no iFooty?', answer: 'Sim. Não processamos seus dados de cartão diretamente — todo pagamento passa por provedores certificados (PayPal) com criptografia SSL e proteção ao comprador. Seus dados ficam com eles, não conosco.' },
      { question: 'Quanto tempo demora pra chegar?', answer: '10 a 15 dias corridos após o envio da mercadoria. Camisas personalizadas podem levar 1-2 dias a mais. Você recebe código de rastreio por email assim que o pedido é despachado.' },
      { question: 'Entregam em todo o Canadá e Estados Unidos?', answer: 'Sim — entregamos para todas as províncias do Canadá e estados dos EUA. Os prazos podem variar levemente para regiões remotas.' },
      { question: 'Quanto custa o frete?', answer: 'Grátis para todo o Canadá & EUA. Oferta por tempo limitado.' },
      { question: 'Posso trocar se o tamanho não servir?', answer: 'Não. A troca só acontece por defeito de fábrica. Por ser erro de escolha, a camisa não pode ser trocada. Por isso, confira sempre a tabela de medidas antes de comprar.' },
      { question: 'E se o produto vier com defeito?', answer: 'Entre em contato em até 7 dias após o recebimento com fotos do defeito. Após nossa análise, a iFooty arca com todos os custos e realiza o reembolso ou a troca sem custo adicional.' },
      { question: 'Como devo lavar e cuidar da minha camisa (especialmente a Versão Jogador)?', answer: 'As camisas de futebol (especialmente a Versão Jogador, que possui escudos e patrocínios emborrachados termocolantes) exigem cuidados especiais. Recomendamos: 1) Lavar sempre à mão e pelo avesso; 2) Utilizar água fria e sabão neutro; 3) Não alvejar, não torcer e não usar secadora (secar sempre à sombra); 4) Nunca passar o ferro de passar diretamente sobre as estampas e emborrachados.' }
    ],
    cta_security: 'Site 100% Blindado',
    cta_title: 'Garanta sua camisa antes que acabe!',
    cta_btn: 'Ver Catálogo',
    footer_about: 'A sua conexão com o futebol, onde quer que você esteja. Especialistas em camisas de futebol para brasileiros no Canadá & EUA.',
    footer_links: 'Links Rápidos',
    footer_how_to_buy: 'Como Comprar',
    footer_about_us: 'Sobre Nós',
    footer_payment: 'Pagamento',
    footer_payment_desc: 'Aceitamos PayPal (Cartão/Saldo) e Interac e-Transfer.',
    footer_rights: 'Todos os direitos reservados.',
    footer_dev: 'Desenvolvido por',
    footer_affiliates: 'Programa de Afiliados',
    footer_contact: 'Fale Conosco',
    nav_selecoes: 'Seleções',
    nav_lancamentos: 'Lançamentos',
    footer_catalog: 'Catálogo',
    about_title: 'Nossa História ⚽',
    about_text1: 'Nascida em Coquitlam/BC, em 2022, a iFooty surgiu de um desejo simples, mas poderoso: aproximar os brasileiros no Canadá e EUA de suas raízes.',
    about_text2: 'Após conquistar nossa comunidade na Columbia Britânica, agora chegamos com tudo em Calgary, especializados em entregar mantos de alta qualidade.',
    success_support_wa_msg: 'Olá! Acabei de fazer um pedido na iFooty e gostaria de tirar algumas dúvidas. 😊',
    checkout_summary_footer_note: 'Você enviará um resumo do pedido para nosso atendimento. O pagamento só será feito após confirmarmos os detalhes do pedido com você. Pagamento via e-Transfer Interac!',
    checkout_summary_footer_note_paypal: 'O pagamento é processado de forma segura pelo PayPal. Seus dados estão protegidos e você receberá uma confirmação imediata após a conclusão.',
    home_numbers_title: 'Nossos números',
    home_empty_team: 'Nenhuma camisa encontrada no momento. Tente outro clube!',
    home_comes_out_to: 'Sai por',
    home_only: 'Sai por só',
    home_savings: 'Você economiza',
    home_view_all: 'Ver todas',
    home_best_options: 'As melhores opções em',
    home_comming_soon: 'Novidades em breve de',
    product_loading: 'Carregando produto...',
    product_not_found: 'Produto não encontrado.',
    product_free_shipping: 'Frete grátis para todo o Canadá e EUA',
    product_volume_promo: '🚀 Desconto progressivo: na compra de 2 ou mais itens você economiza! 🚀',
    product_reviews_count: 'Avaliações',
    product_questions_count: 'Perguntas',
    product_ask_question: 'Tirar dúvidas',
    product_size_guide: 'GUIA DE MEDIDAS',
    product_plus_size_alert: '* Tamanho Plus Size selecionado',
    product_size_tip: '💡 Dica de Tamanho: Nossas camisas possuem modelagem atlética mais justa. Se preferir um caimento mais solto/confortável, recomendamos escolher um tamanho acima do seu tamanho habitual.',
    product_custom_name: 'NOME',
    product_custom_number: 'NÚMERO',
    product_wholesale_header: '🔥 Guia de Medidas Oficial',
    product_table_length: 'COMPRIMENTO',
    product_table_width: 'LARGURA',
    product_table_height: 'ALTURA IND.',
    product_table_weight: 'PESO IND.',
    product_social_title: 'O que nossos clientes dizem',
    product_social_subtitle_part1: 'Já somos ',
    product_social_subtitle_part2: ' vestindo a paixão no Canadá & EUA! 🍁',
    product_faq_title: 'Perguntas Frequentes',
    product_cta_secure: 'Compra Segura',
    product_cta_guarantee: 'Garantimos a qualidade do produto e suporte completo ao cliente via WhatsApp.',
    success_title: 'Pedido Recebido! ⚽',
    success_subtitle: 'Seu manto já está sendo preparado.',
    success_subtitle_paid: 'Seu pagamento foi confirmado!',
    success_message: 'Enviamos um resumo detalhado para seu e-mail. Por favor, verifique sua caixa de entrada (e a pasta de spam).',
    success_whatsapp_error: 'Não conseguiu abrir o WhatsApp?',
    success_whatsapp_btn: 'Enviar Resumo Manualmente',
    success_support_btn: 'Tirar dúvidas com nossa equipe',
    success_home_btn: 'Voltar para a Loja',
    auth_title: 'Área do Torcedor',
    auth_subtitle: 'Identifique-se para acessar seus pedidos e concluir suas compras na iFooty.',
    auth_loading: 'Aguardando Google...',
    auth_google_btn: 'Entrar com Google',
    auth_terms: 'Ao entrar, você concorda com nossos termos de privacidade e política de envios internacionais.',
    auth_error_default: 'Erro ao fazer login. Tente novamente.',
    profile_loading: 'Carregando perfil...',
    profile_tab_orders: 'Meus Pedidos',
    profile_tab_feedback: 'Meu Feedback',
    profile_logout: 'Sair da Conta',
    profile_orders_loading: 'Buscando suas armaduras...',
    profile_no_orders_title: 'Nenhum pedido encontrado.',
    profile_no_orders_text: 'Você ainda não garantiu a sua armadura. Visite as coleções para escolher a sua!',
    profile_explore_btn: 'Explorar Coleção',
    profile_status_pending: '🟡 Aguardando Confirmação',
    profile_status_paid: '💳 Pago',
    profile_status_processing: '🔵 Preparando Envio',
    profile_status_shipped: '🟢 Enviado',
    profile_status_completed: '✅ Entregue',
    profile_status_cancelled: '❌ Cancelado',
    profile_delivery: 'Entrega:',
    profile_order_prefix: 'Pedido #',
    profile_feedback_title: 'O que você achou da iFooty? 🗣️',
    profile_feedback_subtitle: 'Sua opinião nos ajuda a crescer e ajuda outros brasileiros no Canadá & EUA!',
    profile_feedback_rating_label: 'Nota para sua experiência:',
    profile_feedback_location_label: 'De onde você comprou? (Cidade, Província)',
    profile_feedback_location_placeholder: 'Ex: Toronto, ON',
    profile_feedback_comment_label: 'Seu comentário:',
    profile_feedback_comment_placeholder: 'Conte sua experiência com o produto, entrega e atendimento...',
    profile_feedback_submitting: 'Enviando...',
    profile_feedback_submit: 'Publicar Depoimento',
    profile_feedback_my_reviews: 'Meus Depoimentos Enviados',
    profile_feedback_loading: 'Carregando histórico...',
    profile_feedback_empty: 'Você ainda não enviou feedbacks.',
    profile_feedback_approved: 'Publicado',
    profile_feedback_pending_review: 'Em Análise',
    profile_feedback_sent_on: 'Enviado em:',
    profile_feedback_error: 'Erro ao enviar feedback: ',
    profile_feedback_success: 'Depoimento enviado com sucesso! Ele aparecerá no site após a moderação.',
    category_home: 'Início',
    category_items_found: 'itens encontrados',
    category_filters: 'Filtros',
    category_filter_fan: 'Torcedor',
    category_filter_player: 'Jogador',
    category_filter_retro: 'Retrô',
    category_jersey_version: 'Versão da Camisa',
    category_clear_filters: 'Limpar filtros',
    category_filter_btn: 'Filtrar Produtos',
    category_showing: 'Exibindo',
    category_of: 'de',
    category_products: 'produtos',
    category_filtered_by: 'filtrado por:',
    category_sort_by: 'Ordenar por:',
    category_sort_popular: 'Mais Populares',
    category_sort_price_asc: 'Menor Preço',
    category_sort_price_desc: 'Maior Preço',
    category_loading: 'Buscando o manto sagrado...',
    category_empty_title: 'Vestiário vazio!',
    category_empty_text: 'Não encontramos camisas para essa categoria no momento.',
    checkout_login_title: 'Calma lá, artilheiro!',
    checkout_login_text: 'Você precisa se identificar no nosso sistema para separar suas camisas.',
    checkout_login_btn: 'Fazer Login / Cadastro',
    checkout_delivery_title: 'Entrega no Canadá / EUA',
    checkout_summary_title: 'Resumo',
    checkout_subtotal: 'Subtotal',
    checkout_discount: 'Desconto Progressivo',
    checkout_back_btn: 'Voltar',
    checkout_attention: 'Atenção',
    checkout_attention_btn: 'Entendido!',
    checkout_select_province: 'Selecione...',
    checkout_name: 'Nome Completo *',
    checkout_street: 'Endereço (Rua e Número) *',
    checkout_apt: 'Apto/Suite',
    checkout_city: 'Cidade *',
    checkout_province: 'Província *',
    checkout_postal: 'Postal Code *',
    checkout_phone: 'Telefone *',
    checkout_social: 'Instagram ou WhatsApp (Opcional)',
    checkout_social_placeholder: 'Ex: @seuinsta ou Telefone',
    checkout_save_address: 'Salvar este endereço para futuras compras',
    checkout_validation_error: 'Por favor, preencha todos os campos obrigatórios de endereço.',
    checkout_processing: 'Processando...',
    checkout_confirm_btn: 'Confirmar Pedido (WhatsApp)',
    checkout_cart_empty_title: 'Seu carrinho está vazio.',
    checkout_wa_order_title: '*NOVO PEDIDO - iFooty*',
    checkout_wa_customer: '*CLIENTE:*',
    checkout_wa_shipping: '*ENDEREÇO DE ENTREGA:*',
    checkout_wa_items: '*ITENS DO PEDIDO:*',
    checkout_wa_total: '*TOTAL:*',
    checkout_wa_footer: 'Aguardo as instruções para o Interac e-Transfer! 🇨🇦',
    payment_method_title: 'Forma de Pagamento',
    coming_soon: 'Em breve',
    success_message_paid: 'Recebemos seu pedido pago. Você receberá o código de rastreio em breve por e-mail.',
    success_support_wa_msg_paid: 'Olá! Acabei de fazer um pedido pago via PayPal e gostaria de acompanhar o envio. 😊',
    product_ready_delivery: '⚡ Pronta Entrega - Envio em 24h',
    product_stock_units: 'Restam apenas {count} unidades no Canadá & EUA',
    product_stock_sizes_available: 'Disponível em Estoque (Envio 24h):',
    product_stock_preorder: 'Tamanhos sob encomenda (10-15 dias):',
    checkout_title: 'Entrega ou Retirada',
    checkout_home_delivery: 'Receber em Casa',
    checkout_home_delivery_desc: 'Envio Padrão (10-15 dias corridos)',
    checkout_pickup_delivery: 'Retirar em Wolf Willow',
    checkout_pickup_delivery_desc: 'Frete Grátis',
    checkout_pickup_alert_title: '⚠️ IMPORTANTE: Retirada Somente Após Confirmação',
    checkout_pickup_alert_text: 'A retirada em Wolf Willow (Sul de Calgary) só ocorre mediante confirmação prévia de disponibilidade de estoque local.',
    checkout_autocomplete_label: 'Comece pelo Nº e Rua (Autocomplete) *',
    checkout_autocomplete_hint: '💡 Digite o número primeiro para preencher o resto automaticamente.',
    checkout_address_number: 'Número *',
    checkout_district: 'Bairro (District) *',
    checkout_unit: 'Unit (Apto)',
    checkout_city_label: 'Cidade *',
    checkout_province_label: 'Estado/Província *',
    checkout_country_label: 'País',
    exit_title: 'Antes de ir...',
    exit_subtitle: 'Sentimos muito que você não tenha encontrado o que procurava.',
    exit_label: 'Conta pra gente: qual produto você queria ver aqui na iFooty?',
    exit_placeholder: 'Ex: Camisa retrô do Brasil 1970, agasalho do Real Madrid...',
    exit_btn_submit: 'Enviar Sugestão',
    exit_submitting: 'Enviando...',
    exit_footer: 'Prometemos tentar trazer essa novidade para você! ⚽',
    exit_success: 'Obrigado pelo seu feedback! Vamos verificar isso. ⚽',
    exit_error: 'Ocorreu um erro ao enviar. Tente novamente mais tarde.',

    // ═══ REBRAND KEYS (rb_*) — PT ═══
    rb_free_shipping: 'Frete Grátis para todo o Canadá',
    rb_vip_whatsapp: 'Grupo VIP WhatsApp',
    rb_track_order: 'Rastrear Pedido',
    rb_my_account: 'Minha Conta',
    rb_hello_sign_in: 'Olá, Entrar',
    rb_guest: 'Convidado',
    rb_popup_weekly_deal: 'Oferta da Semana',
    rb_popup_get_extra: 'GANHE 10% OFF EXTRA',
    rb_popup_subtitle: 'Adicione as camisas em promoção diretamente ao seu carrinho e use o cupom no checkout:',
    rb_popup_coupon_label: 'CUPOM:',
    rb_popup_copied: 'Copiado',
    rb_popup_copy: 'Copiar',
    rb_popup_selected_promos: '🏷️ Camisas Selecionadas em Promoção',
    rb_popup_added: 'Adicionado!',
    rb_popup_add: 'Adicionar',
    rb_popup_disclaimer: '* Cupom de 10% válido para todas as compras.',
    rb_popup_view_all: 'Ver Todas as Camisas em Promoção',
    rb_my_cart: 'Meu Carrinho',
    rb_jerseys_bag: 'Sacola',
    rb_search_placeholder: 'Encontre seu time favorito...',
    rb_slogan: 'Loja de Camisas Esportivas do Canadá',
    rb_admin_panel: 'Painel Admin',
    rb_my_profile: 'Meu Perfil',
    rb_guest_checkout: 'Checkout Visitante',
    rb_sign_out: 'Sair',
    rb_exit_guest: 'Sair do Modo Visitante',
    rb_nav_soccer: 'Futebol',
    rb_nav_basketball: 'Basquete',
    rb_nav_football: 'Futebol Americano',
    rb_nav_baseball: 'Beisebol',
    rb_nav_hockey: 'Hóquei',
    rb_nav_new_arrivals: 'Novidades',
    rb_nav_best_sellers: 'Mais Vendidos',
    rb_nav_sale: 'Ofertas',
    rb_footer_shipping_title: 'Frete para Todo o Canadá',
    rb_footer_shipping_desc: 'Frete grátis em pedidos premium',
    rb_footer_quality_title: '100% Qualidade Premium',
    rb_footer_quality_desc: 'Detalhes e tecidos costurados oficialmente',
    rb_footer_support_title: 'Suporte VIP 24/7',
    rb_footer_support_desc: 'Fale diretamente com nosso time via WhatsApp',
    rb_footer_about_text: 'Na iFooty, somos apaixonados por conectar fãs de esportes com camisas premium das maiores ligas e seleções do mundo. Do futebol ao hóquei, basquete, futebol americano e beisebol, ajudamos fãs a vestir sua paixão todos os dias.',
    rb_footer_shop_by_sport: 'Compre por Esporte',
    rb_footer_soccer_jerseys: '⚽ Camisas de Futebol',
    rb_footer_basketball_jerseys: '🏀 Camisas de Basquete',
    rb_footer_football_jerseys: '🏈 Camisas de Futebol Americano',
    rb_footer_baseball_jerseys: '⚾ Camisas de Beisebol',
    rb_footer_hockey_jerseys: '🏒 Camisas de Hóquei',
    rb_footer_info_service: 'Info & Atendimento',
    rb_footer_track_order: 'Rastrear Pedido',
    rb_footer_about_us: 'Sobre Nós',
    rb_footer_affiliate: 'Programa de Afiliados',
    rb_footer_contact: 'Fale Conosco',
    rb_footer_join_vip: 'Entrar no Grupo VIP WhatsApp',
    rb_footer_rights: 'Loja de Camisas Esportivas do Canadá. Todos os direitos reservados.',
    rb_prod_back_catalog: 'Voltar ao Catálogo',
    rb_prod_reviews: 'Avaliações',
    rb_prod_size: 'Tamanho',
    rb_prod_size_guide: 'Guia de Medidas',
    rb_prod_whats_included: 'O que está incluído',
    rb_prod_full_kit: 'Kit Completo (Camisa + Calção)',
    rb_prod_shirt_only: 'Apenas Camisa',
    rb_prod_add_custom: 'Adicionar Nome & Número Personalizados',
    rb_prod_player_name: 'Nome do Jogador (ex: MAHOMES)',
    rb_prod_player_number: 'Número (ex: 15)',
    rb_prod_add_patch: 'Adicionar Patch',
    rb_prod_patch_placeholder: 'Patch Desejado (ex: Champions League)',
    rb_prod_quantity: 'Quantidade',
    rb_prod_add_to_cart: 'Adicionar ao Carrinho',
    rb_prod_shipping: 'Frete',
    rb_prod_shipping_leaves: 'Este item sai do nosso armazém em 1-3 dias úteis.',
    rb_prod_shipping_ready: '✓ Pronto para Envio imediatamente após processamento.',
    rb_prod_shipping_free: 'Elegível para frete grátis para todo o Canadá em pedidos acima de $99 CAD.',
    rb_prod_description: 'Descrição',
    rb_prod_premium_quality: 'Qualidade Premium',
    rb_prod_high_grade: 'Tecidos de alta qualidade',
    rb_prod_defect_warranty: 'Garantia Contra Defeitos',
    rb_prod_factory_covered: '100% coberto pela fábrica',
    rb_prod_fast_shipping: 'Envio Rápido',
    rb_prod_with_tracking: 'Com número de rastreio',
    rb_prod_loading: 'Carregando produto...',
    rb_prod_not_found: 'Produto não encontrado.',
    rb_prod_free_shipping_eligible: '✓ Frete Grátis Elegível',
    rb_search_title: 'Resultados da Busca',
    rb_search_results_for: 'Resultados para',
    rb_search_no_results: 'Nenhum resultado encontrado.',
    rb_search_try_again: 'Tente pesquisar com outros termos.',
    rb_cart_title: 'Sacola de Camisas',
    rb_cart_empty: 'Sua sacola está vazia.',
    rb_cart_start_shopping: 'Comece a comprar!',
    rb_cart_subtotal: 'Subtotal',
    rb_cart_volume_discount: 'Desconto de Volume',
    rb_cart_shipping: 'Frete',
    rb_cart_free: 'GRÁTIS',
    rb_cart_total: 'Total',
    rb_cart_checkout: 'Finalizar Pedido',
    rb_cart_continue: 'Continuar Comprando',
    rb_cart_remove: 'Remover',
    rb_cart_size: 'Tam',
    rb_cart_custom: 'Personalização',
    rb_checkout_title: 'Entrega ou Retirada',
    rb_checkout_home_delivery: 'Entrega em Casa',
    rb_checkout_home_delivery_desc: 'Enviado para sua porta (10-15 dias)',
    rb_checkout_pickup: 'Retirar em Wolf Willow',
    rb_checkout_pickup_desc: 'Frete Grátis',
    rb_checkout_login_title: 'Faça login primeiro!',
    rb_checkout_login_text: 'Você precisa entrar para finalizar seu pedido.',
    rb_checkout_login_btn: 'Entrar / Cadastrar',
    rb_checkout_summary: 'Resumo',
    rb_checkout_subtotal: 'Subtotal',
    rb_checkout_discount: 'Desconto de Volume',
    rb_checkout_shipping_cost: 'Frete',
    rb_checkout_handling: 'Taxa de Manuseio',
    rb_checkout_total: 'Total',
    rb_checkout_place_order: 'Finalizar Pedido',
    rb_checkout_processing: 'Processando...',
    rb_checkout_name: 'Nome Completo *',
    rb_checkout_street: 'Endereço *',
    rb_checkout_apt: 'Apto/Suite',
    rb_checkout_city: 'Cidade *',
    rb_checkout_province: 'Província *',
    rb_checkout_postal: 'Código Postal *',
    rb_checkout_phone: 'Telefone *',
    rb_checkout_country: 'País',
    rb_checkout_payment: 'Forma de Pagamento',
    rb_checkout_empty: 'Seu carrinho está vazio.',
    rb_checkout_back: 'Voltar às Compras',
    rb_auth_title: 'Área do Torcedor',
    rb_auth_subtitle: 'Entre para acompanhar seus pedidos e finalizar suas compras na iFooty.',
    rb_auth_google: 'Entrar com Google',
    rb_auth_loading: 'Aguardando Google...',
    rb_auth_terms: 'Ao entrar, você concorda com nossos termos de privacidade e política de envios.',
    rb_auth_error: 'Falha no login. Tente novamente.',
    rb_auth_loading_google: 'Carregando login do Google...',
    rb_auth_or_email_code: 'OU USE CÓDIGO POR E-MAIL',
    rb_auth_email_placeholder: 'Digite seu endereço de e-mail',
    rb_auth_send_code: 'Enviar Código de Verificação',
    rb_auth_code_sent_to: 'Enviamos o código de verificação para:',
    rb_auth_verify_signin: 'Confirmar Código e Entrar',
    rb_auth_change_email: 'Alterar e-mail',
    rb_auth_processing: 'Processando, por favor aguarde...',
    rb_profile_loading: 'Carregando perfil...',
    rb_profile_orders: 'Meus Pedidos',
    rb_profile_feedback: 'Meu Feedback',
    rb_profile_sign_out: 'Sair da Conta',
    rb_profile_no_orders: 'Nenhum pedido encontrado.',
    rb_profile_no_orders_text: 'Você ainda não fez nenhum pedido. Explore nossas coleções!',
    rb_profile_explore: 'Explorar Coleção',
    rb_profile_order: 'Pedido',
    rb_profile_status_pending: '🟡 Aguardando Confirmação',
    rb_profile_status_paid: '💳 Pago',
    rb_profile_status_processing: '🔵 Preparando Envio',
    rb_profile_status_shipped: '🟢 Enviado',
    rb_profile_status_completed: '✅ Entregue',
    rb_profile_status_cancelled: '❌ Cancelado',
    rb_about_title: 'Nossa História ⚽',
    rb_about_text1: 'Na iFooty, somos apaixonados por conectar fãs de esportes com camisas premium das maiores ligas e seleções do mundo.',
    rb_about_text2: 'Nascida no Canadá em 2022, crescemos de uma pequena operação para uma loja de confiança atendendo fãs de coast a coast.',
    rb_affiliates_title: 'Programa de Afiliados',
    rb_affiliates_subtitle: 'Ganhe comissão indicando camisas da iFooty',
    rb_language: 'Idioma',
    rb_home_hero_title: 'VISTA SEU TIME.',
    rb_home_hero_subtitle: 'Encontre Sua Camisa Favorita',
    rb_home_shop_now: 'Comprar Agora',
    rb_home_trending: 'Em Alta Agora 🔥',
    rb_home_trending_subtitle: 'As camisas mais procuradas desta semana',
    rb_home_shop_by_sport: 'Compre por Esporte',
    rb_home_view_collection: 'Ver Coleção',
    rb_home_testimonials_title: 'O Que Nossos Clientes Dizem',
    rb_home_testimonials_subtitle: 'Junte-se a centenas de fãs satisfeitos no Canadá e EUA',
    rb_home_customer_since: 'Cliente desde',
    rb_home_faq_title: 'Perguntas Frequentes',
    rb_home_promo_title: '🔥 OFERTA ESPECIAL',
    rb_home_promo_jerseys: 'Camisas',
    rb_home_promo_for_only: 'por apenas',
    rb_home_promo_each: 'cada',
    rb_home_promo_save: 'Você economiza',
    rb_home_promo_apply: 'Aplicar Desconto',
    rb_home_promo_best: 'Melhor Oferta',
    rb_home_view_all: 'Ver Todos',
    rb_home_browse_licensed: 'Coleção Oficial Licenciada',
    rb_home_shop_by_league: 'Compre por Liga',
    rb_home_starting_at: 'A partir de',
    rb_home_featured_in: 'Destaques em',
    rb_home_spotlight_collection: 'Coleção em Destaque',
    rb_home_special_bundle_deals: '⚡ Combos e Ofertas Especiais',
    rb_home_buy_2_jerseys: 'Compre 2 Camisas',
    rb_home_buy_3_jerseys: 'Compre 3 Camisas',
    rb_home_get_2_for_only: 'Leve por apenas',
    rb_home_save: 'Economize',
    rb_home_select_jerseys: 'Escolher Camisas',
    rb_home_best_deal: 'Melhor Oferta',
    rb_home_discounts_calculated_at_checkout: '* Os descontos são calculados e aplicados automaticamente no checkout',
    rb_home_trending_fan_gear: 'Camisas em Destaque',
    rb_home_show_all: 'Ver Todas',
    rb_home_trending_teams_in_canada: 'TIMES EM DESTAQUE NO CANADÁ',
    rb_sport_soccer: 'Futebol',
    rb_sport_basketball: 'Basquete',
    rb_sport_football: 'Futebol Americano',
    rb_sport_baseball: 'Beisebol',
    rb_sport_hockey: 'Hóquei',
    rb_badge_new_arrival: 'Lançamento',
    rb_badge_best_seller: 'Mais Vendido',
    rb_badge_sale: 'Promoção',
    rb_badge_almost_gone: 'Poucas Unidades',
    rb_badge_trending: 'Em Alta',
    rb_cat_back_home: 'Voltar para Home',
    rb_cat_jerseys: 'Camisas',
    rb_cat_items_found: 'itens encontrados',
    rb_cat_filters: 'Filtros',
    rb_cat_jersey_version: 'Versão da Camisa',
    rb_cat_fan: 'Torcedor',
    rb_cat_player: 'Jogador',
    rb_cat_retro: 'Retrô',
    rb_cat_league: 'Liga',
    rb_cat_team: 'Time',
    rb_cat_all: 'Todos',
    rb_cat_clear_filters: 'Limpar Filtros',
    rb_cat_official_fan_shop: 'Loja Oficial de Fãs',
    rb_cat_items: 'ITENS',
    rb_cat_up_to_discount: '● Até 30% de desconto em itens selecionados',
    rb_cat_shop_by_category: 'Compre por Categoria',
    rb_cat_department: 'Departamento',
    rb_cat_league_comp: 'Liga / Competição',
    rb_cat_gender_age: 'Gênero / Idade',
    rb_cat_teams: 'Times',
    rb_cat_all_teams: 'Todos os Times',
    rb_cat_players: 'Jogadores',
    rb_cat_all_players: 'Todos os Jogadores',
    rb_cat_price_range: 'Faixa de Preço',
    rb_cat_all_prices: 'Todos os Preços',
    rb_cat_under_100: 'Abaixo de $100 CAD',
    rb_cat_over_100: 'Acima de $100 CAD',
    rb_cat_men: 'Masculino',
    rb_cat_women: 'Feminino',
    rb_cat_kids: 'Infantil & Juvenil',
    rb_cat_tshirts: 'Camisetas',
    rb_cat_caps: 'Bonés & Chapéus',
    rb_cat_hoodies: 'Moletons',
    rb_cart_urgency_banner: 'Os itens podem esgotar, peça agora!',
    rb_cart_each: 'cada',
    rb_cart_have_promo_code: 'Tem um cupom de desconto?',
    rb_cart_promo_code: 'Cupom de Desconto',
    rb_cart_add: 'ADICIONAR',
    rb_cart_edit: 'EDITAR',
    rb_cart_applied: 'aplicado',
    rb_cart_apply: 'Aplicar',
    rb_checkout_guest_continue: 'Continuar sem conta',
    rb_checkout_or: 'Ou',
    rb_checkout_signin_create: 'Entrar / Criar Conta',
    rb_checkout_signin_desc: 'Faça login ou crie uma conta para rastrear pedidos e salvar seu endereço.',
    rb_checkout_delivery_method: 'Método de Entrega',
    rb_checkout_home_delivery_label: 'Entrega em Domicílio',
    rb_checkout_shipped_to_door: 'Entregue na sua porta (10 - 15 dias)',
    rb_checkout_local_pickup: 'Retirada Local',
    rb_checkout_pickup_subtext: 'GRÁTIS — Calgary, AB',
    rb_checkout_contact_info: 'Informações de Contato',
    rb_checkout_full_name: 'Nome Completo',
    rb_checkout_as_on_id: 'Como no documento',
    rb_checkout_phone_number: 'Telefone',
    rb_checkout_shipping_address: 'Endereço de Entrega',
    rb_checkout_postal_code: 'CEP / Código Postal',
    rb_checkout_street_address: 'Rua e Logradouro',
    rb_checkout_type_autocomplete: '(digite para autocompletar)',
    rb_checkout_number: 'Número',
    rb_checkout_neighbourhood: 'Bairro',
    rb_checkout_unit_apt: 'Complemento / Apto (Opcional)',
    rb_checkout_province_state: 'Estado / Província',
    rb_checkout_instructions: 'Instruções de Entrega (Opcional — APENAS EM INGLÊS)',
    rb_checkout_instructions_placeholder: 'Ex: Deixar na porta da frente, código do portão 1234...',
    rb_checkout_save_address: 'Salvar meu endereço para futuros pedidos',
    rb_checkout_order_summary: 'Resumo do Pedido',
    rb_checkout_payment_method: 'Método de Pagamento',
    rb_checkout_place_order_wa: 'Fazer Pedido via WhatsApp',
    rb_checkout_pay_card: 'Pagar com Cartão',
    rb_checkout_secure: 'Checkout Seguro e Criptografado',
    rb_checkout_ready_to_ship_banner: 'Este item sai do nosso galpão em 1 a 4 dias úteis. Elegível para frete grátis no Canadá.',
    rb_cat_sort_by: 'Ordenar por:',
    rb_cat_sort_popular: 'Mais Populares',
    rb_cat_sort_newest: 'Mais Recentes',
    rb_cat_sort_price_asc: 'Menor Preço',
    rb_cat_sort_price_desc: 'Maior Preço',
    rb_cat_showing: 'Exibindo',
    rb_cat_of: 'de',
    rb_cat_products: 'produtos',
    rb_cat_loading: 'Buscando camisas...',
    rb_cat_empty_title: 'Vestiário vazio!',
    rb_cat_empty_text: 'Nenhuma camisa encontrada para esta categoria no momento.',
    rb_cat_load_more: 'Carregar Mais',
    rb_cat_previous: 'Anterior',
    rb_cat_next: 'Próximo',
  },

  en: {
    nav_home: 'Home',
    nav_br: 'Brazilian League',
    nav_intl: 'International',
    nav_retro: 'Retro',
    nav_tenis: 'Shoes',
    nav_nba: 'NBA',
    nav_streetwear: 'Streetwear',
    top_bar_announcement: '🍁 Free Shipping Across Canada',
    nav_admin: 'Admin',
    hero_title_part1: 'WEAR YOUR TEAM COLORS EVEN ',
    hero_title_accent: 'FAR FROM HOME',
    hero_subtitle: 'Brazilian, European and International Jerseys | Shipping across Canada & US',
    hero_satisfied_clients: '⭐ +400 satisfied customers in Canada & US',
    hero_shipping_all: 'Canada & US',
    hero_shipping_calgary: 'Priority delivery to Calgary',
    hero_shipping_guaranteed: 'Guaranteed delivery',
    hero_shipping_moneyback: 'Or money back guarantee',
    hero_btn_guarantee: 'GET YOUR JERSEY',
    hero_btn_view_all: 'View all jerseys',
    btn_shop_now: 'Shop Now',
    section_favorites: 'Our Favorites',
    section_best_seller: 'Current Best Seller',
    section_new: 'New Arrival',
    section_categories: 'Browse Categories',
    promo_banner_title: '🔥 SPECIAL OFFER',
    promo_banner_combo2: '2 Jerseys',
    promo_banner_combo3: '3 Jerseys',
    promo_banner_from: 'From',
    promo_banner_for: 'for only',
    promo_banner_each: 'each',
    promo_banner_savings: 'Savings of',
    promo_banner_apply: 'Apply Discount',
    promo_banner_best_offer: 'Best Offer',
    product_price_transfer: 'via e-Transfer',
    product_customization: 'Customization',
    product_customization_none: 'No',
    product_customization_yes: 'Yes',
    product_size: 'Size',
    product_qty: 'Quantity',
    product_buy_now: 'BUY NOW',
    product_wholesale_table: '🔥 Wholesale Table / Combos',
    product_wholesale_unit: 'each',
    product_wholesale_each: 'each',
    product_from: 'From',
    product_composition: 'Items Included',
    product_composition_full: 'Full Kit (Shirt + Shorts)',
    product_composition_only_shirt: 'Shirt Only',
    product_coming_soon: 'Register Interest (Pre-Order)',
    interest_modal_title: 'Interested in this Release',
    interest_modal_subtitle: 'Register your interest to get notified first as soon as this jersey is available for purchase.',
    interest_name_label: 'Your Name',
    interest_whatsapp_label: 'Your WhatsApp (e.g. +1 403 123 4567)',
    interest_size_label: 'Preferred Size',
    interest_submit: 'REGISTER MY INTEREST',
    interest_success_title: 'Success!',
    interest_success_msg: 'Your interest has been successfully registered! We will notify you as soon as this model is launched.',
    interest_success_whatsapp: 'Chat on WhatsApp Support',
    cart_title: 'My Cart',
    cart_empty: 'Your cart is empty.',
    cart_subtotal: 'Subtotal',
    cart_discount: 'Volume Discount',
    cart_total: 'Total',
    cart_checkout: 'Checkout',
    cart_continue_shopping: 'Continue Shopping',
    sales_popup_bought: 'bought',
    sales_popup_time: 'Purchased',
    stats_clients: 'Satisfied customers in Canada & US',
    stats_shipping: 'On-time shipping rate',
    stats_whatsapp: 'Avg response time on WhatsApp',
    stats_payment: 'Secure payment guaranteed',
    section_favorites_title: 'Trending Jerseys 🇧🇷',
    section_favorites_subtitle: 'Swipe to see the most requested holy mantles.',
    promo_footer_note: '* Prices based on standard jerseys. Discount applies to any item. Add to cart and the magic happens!',
    customization_title: 'Make your jersey unique ✍️',
    customization_subtitle: 'You can request customization with the same official font as the players directly in the product options.',
    customization_item1: 'Name + Number',
    customization_item2: 'League Patches',
    emotional_title: 'Because being a fan knows no distance 🇧🇷',
    emotional_text: 'The longing for your country and the passion for football live in the same drawer. We deliver professional player quality directly to your door in Canada & US.',
    social_proof_title: 'Voice of the Stands 🗣️',
    social_proof_subtitle: 'Since 2022, connecting Brazilians across Canada & US with their favorite mantles.',
    social_proof_client_since: 'Customer since',
    social_proof_swipe: 'Swipe to read more →',
    faq_title: 'Common Questions',
    faqs: [
      { question: 'Are iFooty jerseys original?', answer: 'No. We are transparent: our jerseys are premium Thai replicas (Thai AAA), considered the best in the world in terms of replica quality. We use the same dry-fit fabrics, reinforced seams, and finishes as the official models, for a fraction of the price.' },
      { question: 'Why is the price lower than in official stores?', answer: 'Official Nike/Adidas jerseys cost CA$150-200 because you pay for brand licensing, official logistics, and retailer margins. Our Thai AAA replicas deliver 99% of the visual and material quality without these costs, ranging between CA$47.90 and CA$74.90.' },
      { question: 'Can I cancel after customizing?', answer: 'Unfortunately, no. Customization is done on demand and makes the jersey exclusively yours — we cannot resell it. Therefore, check the name, number, and size before finalizing the purchase.' },
      { question: 'Which payment types do you accept?', answer: 'We accept payments via PayPal (credit card, debit, or PayPal balance) and direct customer service via WhatsApp.' },
      { question: 'Is it safe to buy from iFooty?', answer: 'Yes. We do not process your card data directly — all payments go through certified providers (PayPal) with SSL encryption and buyer protection.' },
      { question: 'How long does it take to arrive?', answer: '10 to 15 calendar days after the order is shipped. Customized jerseys may take 1-2 days longer. You will receive a tracking code by email as soon as the order is shipped.' },
      { question: 'Do you deliver to all provinces in Canada and states in the US?', answer: 'Yes — we ship to all provinces in Canada and states in the US. Delivery times may vary slightly for remote regions.' },
      { question: 'How much is shipping?', answer: 'Free for all of Canada & US. Limited time offer.' },
      { question: "Can I exchange it if the size doesn't fit?", answer: 'No. Exchanges only happen due to manufacturing defects. Always check the size guide before buying.' },
      { question: 'What if the product comes with a defect?', answer: 'Contact us within 7 days of receipt with photos of the defect. After our analysis, iFooty bears all costs and provides a refund or exchange at no additional cost.' },
      { question: 'How should I wash and care for my jersey (especially the Player Version)?', answer: 'Soccer jerseys (especially the Player Version) require special care. We recommend: 1) Always hand wash inside out; 2) Use cold water and mild soap; 3) Do not bleach, wring, or use a dryer; 4) Never iron directly over prints or rubberized crests.' }
    ],
    cta_security: '100% Shielded Site',
    cta_title: 'Guarantee your jersey before it sells out!',
    cta_btn: 'View Catalog',
    footer_about: 'Your connection to football, wherever you are. Specialized in football jerseys for Brazilians in Canada & US.',
    footer_links: 'Quick Links',
    footer_how_to_buy: 'How to Buy',
    footer_about_us: 'About Us',
    footer_payment: 'Payment',
    footer_payment_desc: 'We accept PayPal (Card/Balance) and Interac e-Transfer.',
    footer_rights: 'All rights reserved.',
    footer_dev: 'Developed by',
    footer_affiliates: 'Affiliate Program',
    footer_contact: 'Contact Us',
    nav_selecoes: 'National Teams',
    nav_lancamentos: 'New Arrivals',
    footer_catalog: 'Catalog',
    about_title: 'Our Story ⚽',
    about_text1: 'Born in Coquitlam, BC in 2022, iFooty emerged from a simple but powerful desire: to bring Brazilians in Canada & US closer to their roots.',
    about_text2: 'After winning over our community in British Columbia, we have now arrived in Calgary, specialized in delivering high-quality fan jerseys.',
    success_support_wa_msg: 'Hi! I just placed an order on iFooty and have some questions. 😊',
    checkout_summary_footer_note: 'You will send an order summary to our support. Payment will only be made after we confirm the order details with you. Payment via Interac e-Transfer!',
    checkout_summary_footer_note_paypal: 'Payment is securely processed by PayPal. Your data is protected and you will receive an immediate confirmation upon completion.',
    home_numbers_title: 'Our numbers',
    home_empty_team: 'No jerseys found for this team at the moment. Try another club!',
    home_comes_out_to: 'Comes out to',
    home_only: 'Only',
    home_savings: 'You save',
    home_view_all: 'View all',
    home_best_options: 'The best options in',
    home_comming_soon: 'New arrivals soon for',
    product_loading: 'Loading product...',
    product_not_found: 'Product not found.',
    product_free_shipping: 'Free shipping to all Canada & US',
    product_volume_promo: '🚀 Volume discount: buy 2 or more items and save! 🚀',
    product_reviews_count: 'Reviews',
    product_questions_count: 'Questions',
    product_ask_question: 'Ask a question',
    product_size_guide: 'SIZE GUIDE',
    product_plus_size_alert: '* Plus Size selected',
    product_size_tip: '💡 Size Tip: Our jerseys have a slim athletic fit. If you prefer a looser or more comfortable fit, we recommend ordering one size larger than your usual size.',
    product_custom_name: 'NAME',
    product_custom_number: 'NUMBER',
    product_wholesale_header: '🔥 Official Size Guide',
    product_table_length: 'LENGTH',
    product_table_width: 'WIDTH',
    product_table_height: 'SUGGESTED HEIGHT',
    product_table_weight: 'SUGGESTED WEIGHT',
    product_social_title: 'What our customers say',
    product_social_subtitle_part1: 'We are already ',
    product_social_subtitle_part2: ' wearing the passion in Canada & US! 🍁',
    product_faq_title: 'Frequently Asked Questions',
    product_cta_secure: 'Secure Purchase',
    product_cta_guarantee: 'We guarantee product quality and full customer support via WhatsApp.',
    success_title: 'Order Received! ⚽',
    success_subtitle: 'Your jersey is being prepared.',
    success_subtitle_paid: 'Your payment has been confirmed!',
    success_message: "We've sent a detailed summary to your email. Please check your inbox (and spam folder).",
    success_whatsapp_error: "Couldn't open WhatsApp?",
    success_whatsapp_btn: 'Send Summary Manually',
    success_support_btn: 'Chat with our team',
    success_home_btn: 'Back to Shop',
    auth_title: 'Fan Zone',
    auth_subtitle: 'Sign in to track your orders and complete your purchases at iFooty.',
    auth_loading: 'Waiting for Google...',
    auth_google_btn: 'Sign in with Google',
    auth_terms: 'By signing in, you agree to our privacy terms and international shipping policy.',
    auth_error_default: 'Login failed. Please try again.',
    profile_loading: 'Loading profile...',
    profile_tab_orders: 'My Orders',
    profile_tab_feedback: 'My Feedback',
    profile_logout: 'Sign Out',
    profile_orders_loading: 'Fetching your jerseys...',
    profile_no_orders_title: 'No orders found.',
    profile_no_orders_text: "You haven't placed any orders yet. Browse our collections to find yours!",
    profile_explore_btn: 'Explore Collection',
    profile_status_pending: '🟡 Awaiting Confirmation',
    profile_status_paid: '💳 Paid',
    profile_status_processing: '🔵 Preparing Shipment',
    profile_status_shipped: '🟢 Shipped',
    profile_status_completed: '✅ Delivered',
    profile_status_cancelled: '❌ Cancelled',
    profile_delivery: 'Shipping to:',
    profile_order_prefix: 'Order #',
    profile_feedback_title: 'What did you think of iFooty? 🗣️',
    profile_feedback_subtitle: 'Your review helps us grow and helps other Brazilians in Canada & US!',
    profile_feedback_rating_label: 'Rate your experience:',
    profile_feedback_location_label: 'Where did you buy from? (City, Province)',
    profile_feedback_location_placeholder: 'e.g. Toronto, ON',
    profile_feedback_comment_label: 'Your comment:',
    profile_feedback_comment_placeholder: 'Share your experience with the product, delivery and service...',
    profile_feedback_submitting: 'Submitting...',
    profile_feedback_submit: 'Publish Review',
    profile_feedback_my_reviews: 'My Submitted Reviews',
    profile_feedback_loading: 'Loading history...',
    profile_feedback_empty: "You haven't submitted any reviews yet.",
    profile_feedback_approved: 'Published',
    profile_feedback_pending_review: 'Under Review',
    profile_feedback_sent_on: 'Sent on:',
    profile_feedback_error: 'Error submitting review: ',
    profile_feedback_success: 'Review submitted! It will appear on the site after moderation.',
    category_home: 'Home',
    category_items_found: 'items found',
    category_filters: 'Filters',
    category_filter_fan: 'Fan Edition',
    category_filter_player: 'Player Edition',
    category_filter_retro: 'Retro',
    category_jersey_version: 'Jersey Version',
    category_clear_filters: 'Clear filters',
    category_filter_btn: 'Filter Products',
    category_showing: 'Showing',
    category_of: 'of',
    category_products: 'products',
    category_filtered_by: 'filtered by:',
    category_sort_by: 'Sort by:',
    category_sort_popular: 'Most Popular',
    category_sort_price_asc: 'Lowest Price',
    category_sort_price_desc: 'Highest Price',
    category_loading: 'Searching for jerseys...',
    category_empty_title: 'Empty locker room!',
    category_empty_text: 'No jerseys found for this category at the moment.',
    checkout_login_title: 'Hold on, striker!',
    checkout_login_text: 'You need to sign in to reserve your jerseys.',
    checkout_login_btn: 'Sign In / Register',
    checkout_delivery_title: 'Delivery in Canada / US',
    checkout_summary_title: 'Summary',
    checkout_subtotal: 'Subtotal',
    checkout_discount: 'Volume Discount',
    checkout_back_btn: 'Back',
    checkout_attention: 'Attention',
    checkout_attention_btn: 'Got it!',
    checkout_select_province: 'Select...',
    checkout_name: 'Full Name *',
    checkout_street: 'Street Address *',
    checkout_apt: 'Apt/Suite',
    checkout_city: 'City *',
    checkout_province: 'Province *',
    checkout_postal: 'Postal Code *',
    checkout_phone: 'Phone Number *',
    checkout_social: 'Instagram or WhatsApp (Optional)',
    checkout_social_placeholder: 'e.g. @yourinsta or Phone',
    checkout_save_address: 'Save this address for future purchases',
    checkout_validation_error: 'Please fill in all required address fields.',
    checkout_processing: 'Processing...',
    checkout_confirm_btn: 'Place Order (WhatsApp)',
    checkout_cart_empty_title: 'Your cart is empty.',
    checkout_back_shopping: 'Back to Shopping',
    checkout_wa_order_title: '*NEW ORDER - iFooty*',
    checkout_wa_customer: '*CUSTOMER:*',
    checkout_wa_shipping: '*SHIPPING ADDRESS:*',
    checkout_wa_items: '*ORDER ITEMS:*',
    checkout_wa_total: '*TOTAL:*',
    checkout_wa_footer: 'I await the instructions for Interac e-Transfer! 🇨🇦',
    payment_method_title: 'Payment Method',
    coming_soon: 'Coming Soon',
    success_message_paid: 'We received your paid order. You will receive the tracking code shortly via email.',
    success_support_wa_msg_paid: 'Hi! I just placed a paid order via PayPal and I would like to track the shipment. 😊',
    product_ready_delivery: '⚡ In Stock - 24h Shipping',
    product_stock_units: 'Only {count} units left in Canada & US',
    product_stock_sizes_available: 'Available in Stock (24h Shipping):',
    product_stock_preorder: 'Pre-order sizes (10-15 days):',
    checkout_title: 'Delivery or Pickup',
    checkout_home_delivery: 'Home Delivery',
    checkout_home_delivery_desc: 'Standard Shipping (10-15 days)',
    checkout_pickup_delivery: 'Pickup at Wolf Willow',
    checkout_pickup_delivery_desc: 'Free Shipping',
    checkout_pickup_alert_title: '⚠️ IMPORTANT: Pickup Only Upon Confirmation',
    checkout_pickup_alert_text: 'Pickup at Wolf Willow (South Calgary) is only available upon prior confirmation of local stock availability.',
    checkout_autocomplete_label: 'Start with Street No. & Name (Autocomplete) *',
    checkout_autocomplete_hint: '💡 Type the number first to fill the rest automatically.',
    checkout_address_number: 'Number *',
    checkout_district: 'District *',
    checkout_unit: 'Unit (Apt)',
    checkout_city_label: 'City *',
    checkout_province_label: 'State/Province *',
    checkout_country_label: 'Country',
    exit_title: 'Before you go...',
    exit_subtitle: 'We are sorry that you did not find what you were looking for.',
    exit_label: 'Tell us: which product would you like to see here at iFooty?',
    exit_placeholder: 'e.g. Retro Brazil 1970 jersey, Real Madrid tracksuit...',
    exit_btn_submit: 'Submit Suggestion',
    exit_submitting: 'Sending...',
    exit_footer: 'We promise to try to bring this update to you! ⚽',
    exit_success: 'Thank you for your feedback! We will check it out. ⚽',
    exit_error: 'An error occurred while sending. Please try again later.',

    // ═══ REBRAND KEYS (rb_*) — EN ═══
    rb_free_shipping: 'Free Shipping Across Canada',
    rb_vip_whatsapp: 'VIP WhatsApp Group',
    rb_track_order: 'Track Order',
    rb_my_account: 'My Account',
    rb_hello_sign_in: 'Hello, Sign In',
    rb_guest: 'Guest',
    rb_popup_weekly_deal: 'Deal of the Week',
    rb_popup_get_extra: 'GET EXTRA 10% OFF',
    rb_popup_subtitle: 'Add promotional jerseys directly to your cart and use the coupon at checkout:',
    rb_popup_coupon_label: 'COUPON:',
    rb_popup_copied: 'Copied',
    rb_popup_copy: 'Copy',
    rb_popup_selected_promos: '🏷️ Selected Jerseys on Sale',
    rb_popup_added: 'Added!',
    rb_popup_add: 'Add',
    rb_popup_disclaimer: '* 10% coupon valid for all purchases.',
    rb_popup_view_all: 'View All Jerseys on Sale',
    rb_my_cart: 'My Cart',
    rb_jerseys_bag: 'Jerseys bag',
    rb_search_placeholder: 'Find your favorite team...',
    rb_slogan: "Canada's Sports Jersey Store",
    rb_admin_panel: 'Admin Panel',
    rb_my_profile: 'My Profile',
    rb_guest_checkout: 'Guest Checkout',
    rb_sign_out: 'Sign Out',
    rb_exit_guest: 'Exit Guest',
    rb_nav_soccer: 'Soccer',
    rb_nav_basketball: 'Basketball',
    rb_nav_football: 'Football',
    rb_nav_baseball: 'Baseball',
    rb_nav_hockey: 'Hockey',
    rb_nav_new_arrivals: 'New Arrivals',
    rb_nav_best_sellers: 'Best Sellers',
    rb_nav_sale: 'Sale Items',
    rb_footer_shipping_title: 'Canada-Wide Shipping',
    rb_footer_shipping_desc: 'Free shipping on premium orders',
    rb_footer_quality_title: '100% Premium Quality',
    rb_footer_quality_desc: 'Officially stitched details & fabrics',
    rb_footer_support_title: '24/7 VIP Support',
    rb_footer_support_desc: 'Talk directly to our team via WhatsApp',
    rb_footer_about_text: "At iFooty, we're passionate about connecting sports fans with premium jerseys from the world's biggest leagues and national teams. From soccer to hockey, basketball, football and baseball, we help fans wear their passion every day.",
    rb_footer_shop_by_sport: 'Shop By Sport',
    rb_footer_soccer_jerseys: '⚽ Soccer Jerseys',
    rb_footer_basketball_jerseys: '🏀 Basketball Jerseys',
    rb_footer_football_jerseys: '🏈 Football Jerseys',
    rb_footer_baseball_jerseys: '⚾ Baseball Jerseys',
    rb_footer_hockey_jerseys: '🏒 Hockey Jerseys',
    rb_footer_info_service: 'Info & Service',
    rb_footer_track_order: 'Track Order',
    rb_footer_about_us: 'About Us',
    rb_footer_affiliate: 'Affiliate Program',
    rb_footer_contact: 'Contact Us',
    rb_footer_join_vip: 'Join VIP WhatsApp Group',
    rb_footer_rights: "Canada's Sports Jersey Store. All rights reserved.",
    rb_prod_back_catalog: 'Back to Catalog',
    rb_prod_reviews: 'Reviews',
    rb_prod_size: 'Size',
    rb_prod_size_guide: 'Size Guide',
    rb_prod_whats_included: "What's Included",
    rb_prod_full_kit: 'Full Kit (Shirt + Shorts)',
    rb_prod_shirt_only: 'Shirt Only',
    rb_prod_add_custom: 'Add Custom Name & Number',
    rb_prod_player_name: 'Player Name (e.g. MAHOMES)',
    rb_prod_player_number: 'Number (e.g. 15)',
    rb_prod_add_patch: 'Add Patch',
    rb_prod_patch_placeholder: 'Desired Patch (e.g. Champions League)',
    rb_prod_quantity: 'Quantity',
    rb_prod_add_to_cart: 'Add to Cart',
    rb_prod_shipping: 'Shipping',
    rb_prod_shipping_leaves: 'This item leaves our warehouse in 1-3 business days.',
    rb_prod_shipping_ready: '✓ Ready To Ship immediately upon processing.',
    rb_prod_shipping_free: 'Eligible for free Canada-wide shipping on orders over $99 CAD.',
    rb_prod_description: 'Description',
    rb_prod_premium_quality: 'Premium Quality',
    rb_prod_high_grade: 'High-grade fabrics',
    rb_prod_defect_warranty: 'Defect Warranty',
    rb_prod_factory_covered: '100% factory covered',
    rb_prod_fast_shipping: 'Fast Shipping',
    rb_prod_with_tracking: 'With tracking number',
    rb_prod_loading: 'Loading product...',
    rb_prod_not_found: 'Product not found.',
    rb_prod_free_shipping_eligible: '✓ Free Shipping Eligible',
    rb_search_title: 'Search Results',
    rb_search_results_for: 'Results for',
    rb_search_no_results: 'No results found.',
    rb_search_try_again: 'Try searching with different terms.',
    rb_cart_title: 'Jerseys Bag',
    rb_cart_empty: 'Your bag is empty.',
    rb_cart_start_shopping: 'Start shopping!',
    rb_cart_subtotal: 'Subtotal',
    rb_cart_volume_discount: 'Volume Discount',
    rb_cart_shipping: 'Shipping',
    rb_cart_free: 'FREE',
    rb_cart_total: 'Total',
    rb_cart_checkout: 'Checkout',
    rb_cart_continue: 'Continue Shopping',
    rb_cart_remove: 'Remove',
    rb_cart_size: 'Size',
    rb_cart_custom: 'Custom',
    rb_checkout_title: 'Delivery or Pickup',
    rb_checkout_home_delivery: 'Home Delivery',
    rb_checkout_home_delivery_desc: 'Shipped to your door (10 - 15 days)',
    rb_checkout_pickup: 'Pickup at Wolf Willow',
    rb_checkout_pickup_desc: 'Free Shipping',
    rb_checkout_login_title: 'Sign in first!',
    rb_checkout_login_text: 'You need to sign in to complete your order.',
    rb_checkout_login_btn: 'Sign In / Register',
    rb_checkout_summary: 'Summary',
    rb_checkout_subtotal: 'Subtotal',
    rb_checkout_discount: 'Volume Discount',
    rb_checkout_shipping_cost: 'Shipping',
    rb_checkout_handling: 'Handling Fee',
    rb_checkout_total: 'Total',
    rb_checkout_place_order: 'Place Order',
    rb_checkout_processing: 'Processing...',
    rb_checkout_name: 'Full Name *',
    rb_checkout_street: 'Street Address *',
    rb_checkout_apt: 'Apt/Suite',
    rb_checkout_city: 'City *',
    rb_checkout_province: 'Province *',
    rb_checkout_postal: 'Postal Code *',
    rb_checkout_phone: 'Phone *',
    rb_checkout_country: 'Country',
    rb_checkout_payment: 'Payment Method',
    rb_checkout_empty: 'Your cart is empty.',
    rb_checkout_back: 'Back to Shopping',
    rb_auth_title: 'Fan Zone',
    rb_auth_subtitle: 'Sign in to track your orders and complete your purchases at iFooty.',
    rb_auth_google: 'Sign in with Google',
    rb_auth_loading: 'Waiting for Google...',
    rb_auth_terms: 'By signing in, you agree to our privacy terms and shipping policy.',
    rb_auth_error: 'Login failed. Please try again.',
    rb_auth_loading_google: 'Loading Google Login...',
    rb_auth_or_email_code: 'OR USE EMAIL CODE',
    rb_auth_email_placeholder: 'Enter your email address',
    rb_auth_send_code: 'Send Verification Code',
    rb_auth_code_sent_to: 'We sent the verification code to:',
    rb_auth_verify_signin: 'Verify Code & Sign In',
    rb_auth_change_email: 'Change email',
    rb_auth_processing: 'Processing, please wait...',
    rb_profile_loading: 'Loading profile...',
    rb_profile_orders: 'My Orders',
    rb_profile_feedback: 'My Feedback',
    rb_profile_sign_out: 'Sign Out',
    rb_profile_no_orders: 'No orders found.',
    rb_profile_no_orders_text: "You haven't placed any orders yet. Browse our collections!",
    rb_profile_explore: 'Explore Collection',
    rb_profile_order: 'Order',
    rb_profile_status_pending: '🟡 Awaiting Confirmation',
    rb_profile_status_paid: '💳 Paid',
    rb_profile_status_processing: '🔵 Preparing Shipment',
    rb_profile_status_shipped: '🟢 Shipped',
    rb_profile_status_completed: '✅ Delivered',
    rb_profile_status_cancelled: '❌ Cancelled',
    rb_about_title: 'Our Story ⚽',
    rb_about_text1: "At iFooty, we're passionate about connecting sports fans with premium jerseys from the world's biggest leagues and national teams.",
    rb_about_text2: 'Born in Canada in 2022, we grew from a small operation to a trusted store serving fans coast to coast.',
    rb_affiliates_title: 'Affiliate Program',
    rb_affiliates_subtitle: 'Earn commission by referring iFooty jerseys',
    rb_language: 'Language',
    rb_home_hero_title: 'WEAR YOUR TEAM.',
    rb_home_hero_subtitle: 'Find Your Favorite Jersey',
    rb_home_shop_now: 'Shop Now',
    rb_home_trending: 'Trending Now 🔥',
    rb_home_trending_subtitle: 'The most searched jerseys this week',
    rb_home_shop_by_sport: 'Shop by Sport',
    rb_home_view_collection: 'View Collection',
    rb_home_testimonials_title: 'What Our Customers Say',
    rb_home_testimonials_subtitle: 'Join hundreds of satisfied fans across Canada & US',
    rb_home_customer_since: 'Customer since',
    rb_home_faq_title: 'Frequently Asked Questions',
    rb_home_promo_title: '🔥 SPECIAL OFFER',
    rb_home_promo_jerseys: 'Jerseys',
    rb_home_promo_for_only: 'for only',
    rb_home_promo_each: 'each',
    rb_home_promo_save: 'You save',
    rb_home_promo_apply: 'Apply Discount',
    rb_home_promo_best: 'Best Offer',
    rb_home_view_all: 'View All',
    rb_home_browse_licensed: 'Browse officially licensed gear',
    rb_home_shop_by_league: 'Shop by League',
    rb_home_starting_at: 'Starting at',
    rb_home_featured_in: 'Featured in',
    rb_home_spotlight_collection: 'Spotlight Collection',
    rb_home_special_bundle_deals: '⚡ Special Bundle Deals',
    rb_home_buy_2_jerseys: 'Buy 2 Jerseys',
    rb_home_buy_3_jerseys: 'Buy 3 Jerseys',
    rb_home_get_2_for_only: 'Get them for only',
    rb_home_save: 'Save',
    rb_home_select_jerseys: 'Select Jerseys',
    rb_home_best_deal: 'Best Deal',
    rb_home_discounts_calculated_at_checkout: '* Discounts are calculated and applied automatically at checkout',
    rb_home_trending_fan_gear: 'Trending Fan Gear',
    rb_home_show_all: 'Show All',
    rb_home_trending_teams_in_canada: 'TRENDING TEAMS IN CANADA',
    rb_sport_soccer: 'Soccer',
    rb_sport_basketball: 'Basketball',
    rb_sport_football: 'Football',
    rb_sport_baseball: 'Baseball',
    rb_sport_hockey: 'Hockey',
    rb_badge_new_arrival: 'New Arrival',
    rb_badge_best_seller: 'Best Seller',
    rb_badge_sale: 'Sale',
    rb_badge_almost_gone: 'Almost Gone',
    rb_badge_trending: 'Trending',
    rb_cat_back_home: 'Back to Home',
    rb_cat_jerseys: 'Jerseys',
    rb_cat_items_found: 'items found',
    rb_cat_filters: 'Filters',
    rb_cat_jersey_version: 'Jersey Version',
    rb_cat_fan: 'Fan Edition',
    rb_cat_player: 'Player Edition',
    rb_cat_retro: 'Retro',
    rb_cat_league: 'League',
    rb_cat_team: 'Team',
    rb_cat_all: 'All',
    rb_cat_clear_filters: 'Clear Filters',
    rb_cat_official_fan_shop: 'Official Fan Shop',
    rb_cat_items: 'ITEMS',
    rb_cat_up_to_discount: '● Up to 30% Off select items',
    rb_cat_shop_by_category: 'Shop By Category',
    rb_cat_department: 'Department',
    rb_cat_league_comp: 'League / Competition',
    rb_cat_gender_age: 'Gender / Age',
    rb_cat_teams: 'Teams',
    rb_cat_all_teams: 'All Teams',
    rb_cat_players: 'Players',
    rb_cat_all_players: 'All Players',
    rb_cat_price_range: 'Price Range',
    rb_cat_all_prices: 'All Prices',
    rb_cat_under_100: 'Under $100 CAD',
    rb_cat_over_100: 'Over $100 CAD',
    rb_cat_men: 'Men',
    rb_cat_women: 'Women',
    rb_cat_kids: 'Kids & Youth',
    rb_cat_tshirts: 'T-Shirts',
    rb_cat_caps: 'Caps & Hats',
    rb_cat_hoodies: 'Hoodies',
    rb_cart_urgency_banner: 'Items May Sell Out, Order Now!',
    rb_cart_each: 'each',
    rb_cart_have_promo_code: 'Have a Promo Code?',
    rb_cart_promo_code: 'Promo Code',
    rb_cart_add: 'ADD',
    rb_cart_edit: 'EDIT',
    rb_cart_applied: 'applied',
    rb_cart_apply: 'Apply',
    rb_checkout_guest_continue: 'Continue as Guest',
    rb_checkout_or: 'Or',
    rb_checkout_signin_create: 'Sign In / Create Account',
    rb_checkout_signin_desc: 'Sign in or create a free account to track orders and save your address.',
    rb_checkout_delivery_method: 'Delivery Method',
    rb_checkout_home_delivery_label: 'Home Delivery',
    rb_checkout_shipped_to_door: 'Shipped to your door (10 - 15 days)',
    rb_checkout_local_pickup: 'Local Pickup',
    rb_checkout_pickup_subtext: 'FREE — Calgary, AB',
    rb_checkout_contact_info: 'Contact Information',
    rb_checkout_full_name: 'Full Name',
    rb_checkout_as_on_id: 'As on your ID',
    rb_checkout_phone_number: 'Phone Number',
    rb_checkout_shipping_address: 'Shipping Address',
    rb_checkout_postal_code: 'Postal / ZIP Code',
    rb_checkout_street_address: 'Street Address',
    rb_checkout_type_autocomplete: '(type to autocomplete)',
    rb_checkout_number: 'Number',
    rb_checkout_neighbourhood: 'Neighbourhood',
    rb_checkout_unit_apt: 'Unit / Apt (Optional)',
    rb_checkout_province_state: 'Province / State',
    rb_checkout_instructions: 'Delivery Instructions (Optional — IN ENGLISH ONLY)',
    rb_checkout_instructions_placeholder: 'e.g. Leave at front door, buzzer code 1234...',
    rb_checkout_save_address: 'Save my address for future orders',
    rb_checkout_order_summary: 'Order Summary',
    rb_checkout_payment_method: 'Payment Method',
    rb_checkout_place_order_wa: 'Place Order via WhatsApp',
    rb_checkout_pay_card: 'Pay with Card',
    rb_checkout_secure: 'Secure & Encrypted Checkout',
    rb_checkout_ready_to_ship_banner: 'This item leaves our warehouse in 1–4 business days. Eligible for free Canada-wide shipping.',
    rb_cat_sort_by: 'Sort by:',
    rb_cat_sort_popular: 'Most Popular',
    rb_cat_sort_newest: 'Newest',
    rb_cat_sort_price_asc: 'Lowest Price',
    rb_cat_sort_price_desc: 'Highest Price',
    rb_cat_showing: 'Showing',
    rb_cat_of: 'of',
    rb_cat_products: 'products',
    rb_cat_loading: 'Searching for jerseys...',
    rb_cat_empty_title: 'Empty locker room!',
    rb_cat_empty_text: 'No jerseys found for this category at the moment.',
    rb_cat_load_more: 'Load More',
    rb_cat_previous: 'Previous',
    rb_cat_next: 'Next',
  },

  es: {
    nav_home: 'Inicio',
    nav_br: 'Liga Brasileña',
    nav_intl: 'Internacional',
    nav_retro: 'Retro',
    nav_tenis: 'Zapatillas',
    nav_nba: 'NBA',
    nav_streetwear: 'Streetwear',
    top_bar_announcement: '🍁 Envío Gratis a todo Canadá',
    nav_admin: 'Admin',
    hero_title_part1: 'VISTE LOS COLORES DE TU EQUIPO ',
    hero_title_accent: 'LEJOS DE CASA',
    hero_subtitle: 'Camisetas brasileñas, europeas e internacionales | Envío a Canadá y EE.UU.',
    hero_satisfied_clients: '⭐ +400 clientes satisfechos en Canadá y EE.UU.',
    hero_shipping_all: 'Canadá y EE.UU.',
    hero_shipping_calgary: 'Entrega prioritaria a Calgary',
    hero_shipping_guaranteed: 'Entrega garantizada',
    hero_shipping_moneyback: 'O devolución del dinero',
    hero_btn_guarantee: 'CONSIGUE TU CAMISETA',
    hero_btn_view_all: 'Ver todas las camisetas',
    btn_shop_now: 'Comprar Ahora',
    section_favorites: 'Nuestros Favoritos',
    section_best_seller: 'Más Vendido Actual',
    section_new: 'Novedad',
    section_categories: 'Explorar Categorías',
    promo_banner_title: '🔥 OFERTA ESPECIAL',
    promo_banner_combo2: '2 Camisetas',
    promo_banner_combo3: '3 Camisetas',
    promo_banner_from: 'Desde',
    promo_banner_for: 'por solo',
    promo_banner_each: 'cada una',
    promo_banner_savings: 'Ahorras',
    promo_banner_apply: 'Aplicar Descuento',
    promo_banner_best_offer: 'Mejor Oferta',
    product_price_transfer: 'vía e-Transfer',
    product_customization: 'Personalización',
    product_customization_none: 'No',
    product_customization_yes: 'Sí',
    product_size: 'Talla',
    product_qty: 'Cantidad',
    product_buy_now: 'COMPRAR AHORA',
    product_wholesale_table: '🔥 Tabla de Mayoreo / Combos',
    product_wholesale_unit: 'c/u',
    product_wholesale_each: 'cada',
    product_from: 'Desde',
    product_composition: 'Artículos Incluidos',
    product_composition_full: 'Kit Completo (Camiseta + Short)',
    product_composition_only_shirt: 'Solo Camiseta',
    product_coming_soon: 'Registrar Interés (Pre-Venta)',
    interest_modal_title: 'Interesado en este Lanzamiento',
    interest_modal_subtitle: 'Registra tu interés para ser notificado en cuanto esta camiseta esté disponible.',
    interest_name_label: 'Tu Nombre',
    interest_whatsapp_label: 'Tu WhatsApp (Ej: +1 403 123 4567)',
    interest_size_label: 'Talla Preferida',
    interest_submit: 'REGISTRAR MI INTERÉS',
    interest_success_title: '¡Éxito!',
    interest_success_msg: '¡Tu interés ha sido registrado! Te notificaremos cuando este modelo sea lanzado.',
    interest_success_whatsapp: 'Chatear en WhatsApp Soporte',
    cart_title: 'Mi Carrito',
    cart_empty: 'Tu carrito está vacío.',
    cart_subtotal: 'Subtotal',
    cart_discount: 'Descuento por Volumen',
    cart_total: 'Total',
    cart_checkout: 'Finalizar Compra',
    cart_continue_shopping: 'Seguir Comprando',
    sales_popup_bought: 'compró',
    sales_popup_time: 'Comprado',
    stats_clients: 'Clientes satisfechos en Canadá y EE.UU.',
    stats_shipping: 'Tasa de envío a tiempo',
    stats_whatsapp: 'Tiempo de respuesta promedio en WhatsApp',
    stats_payment: 'Pago seguro garantizado',
    section_favorites_title: 'Camisetas Tendencia 🇧🇷',
    section_favorites_subtitle: 'Desliza para ver las camisetas más solicitadas.',
    promo_footer_note: '* Precios basados en camiseta estándar. El descuento aplica a cualquier artículo. ¡Agrega al carrito y la magia sucede!',
    customization_title: 'Haz tu camiseta única ✍️',
    customization_subtitle: 'Puedes solicitar personalización con la misma fuente oficial de los jugadores directamente en las opciones del producto.',
    customization_item1: 'Nombre + Número',
    customization_item2: 'Parches de Liga',
    emotional_title: 'Porque ser fan no conoce distancia 🇧🇷',
    emotional_text: 'La nostalgia por tu país y la pasión por el fútbol viven en el mismo cajón. Entregamos calidad de jugador profesional directamente a tu puerta en Canadá y EE.UU.',
    social_proof_title: 'Voz de la Tribuna 🗣️',
    social_proof_subtitle: 'Desde 2022, conectando brasileños en Canadá y EE.UU. con sus camisetas favoritas.',
    social_proof_client_since: 'Cliente desde',
    social_proof_swipe: 'Desliza para leer más →',
    faq_title: 'Preguntas Frecuentes',
    faqs: [
      { question: '¿Las camisetas de iFooty son originales?', answer: 'No. Somos transparentes: nuestras camisetas son réplicas premium tailandesas (Thai AAA), consideradas las mejores del mundo en calidad de réplica.' },
      { question: '¿Por qué el precio es menor que en tiendas oficiales?', answer: 'Las camisetas oficiales Nike/Adidas cuestan CA$150-200. Nuestras réplicas Thai AAA entregan 99% de la calidad por una fracción del precio, entre CA$47.90 y CA$74.90.' },
      { question: '¿Puedo cancelar después de personalizar?', answer: 'Lamentablemente no. La personalización se hace bajo demanda. Verifica nombre, número y talla antes de finalizar.' },
      { question: '¿Qué formas de pago aceptan?', answer: 'Aceptamos PayPal (tarjeta, débito o saldo) y atención directa vía WhatsApp. También Interac e-Transfer.' },
      { question: '¿Es seguro comprar en iFooty?', answer: 'Sí. Todos los pagos pasan por proveedores certificados (PayPal) con cifrado SSL y protección al comprador.' },
      { question: '¿Cuánto tarda en llegar?', answer: '10 a 15 días calendario después del envío. Camisetas personalizadas pueden tardar 1-2 días más.' },
      { question: '¿Entregan a todo Canadá y Estados Unidos?', answer: 'Sí — enviamos a todas las provincias de Canadá y estados de EE.UU.' },
      { question: '¿Cuánto cuesta el envío?', answer: 'Gratis para todo Canadá y EE.UU. Oferta por tiempo limitado.' },
      { question: '¿Puedo cambiar si la talla no me queda?', answer: 'No. Los cambios solo aplican por defectos de fabricación. Consulta la guía de tallas antes de comprar.' },
      { question: '¿Qué pasa si el producto viene con defecto?', answer: 'Contáctanos dentro de 7 días con fotos del defecto. iFooty asume todos los costos del reembolso o cambio.' },
      { question: '¿Cómo debo lavar y cuidar mi camiseta?', answer: 'Recomendamos: 1) Lavar a mano y del revés; 2) Agua fría y jabón neutro; 3) No blanquear ni usar secadora; 4) No planchar sobre estampados.' }
    ],
    cta_security: 'Sitio 100% Blindado',
    cta_title: '¡Consigue tu camiseta antes de que se agote!',
    cta_btn: 'Ver Catálogo',
    footer_about: 'Tu conexión con el fútbol, donde quiera que estés. Especialistas en camisetas en Canadá y EE.UU.',
    footer_links: 'Enlaces Rápidos',
    footer_how_to_buy: 'Cómo Comprar',
    footer_about_us: 'Sobre Nosotros',
    footer_payment: 'Pago',
    footer_payment_desc: 'Aceptamos PayPal (Tarjeta/Saldo) e Interac e-Transfer.',
    footer_rights: 'Todos los derechos reservados.',
    footer_dev: 'Desarrollado por',
    footer_affiliates: 'Programa de Afiliados',
    footer_contact: 'Contáctanos',
    nav_selecoes: 'Selecciones',
    nav_lancamentos: 'Novedades',
    footer_catalog: 'Catálogo',
    about_title: 'Nuestra Historia ⚽',
    about_text1: 'Nacida en Coquitlam, BC en 2022, iFooty surgió de un deseo simple pero poderoso: acercar a los brasileños en Canadá y EE.UU. a sus raíces.',
    about_text2: 'Después de conquistar nuestra comunidad en Columbia Británica, ahora llegamos a Calgary con camisetas de alta calidad.',
    success_support_wa_msg: '¡Hola! Acabo de hacer un pedido en iFooty y tengo algunas preguntas. 😊',
    checkout_summary_footer_note: 'Enviarás un resumen del pedido a nuestro soporte. El pago solo se hará después de confirmar los detalles. ¡Pago vía Interac e-Transfer!',
    checkout_summary_footer_note_paypal: 'El pago es procesado de forma segura por PayPal. Tus datos están protegidos.',
    home_numbers_title: 'Nuestros números',
    home_empty_team: 'No se encontraron camisetas. ¡Prueba con otro equipo!',
    home_comes_out_to: 'Sale a',
    home_only: 'Solo',
    home_savings: 'Ahorras',
    home_view_all: 'Ver todos',
    home_best_options: 'Las mejores opciones en',
    home_comming_soon: 'Próximamente de',
    product_loading: 'Cargando producto...',
    product_not_found: 'Producto no encontrado.',
    product_free_shipping: 'Envío gratis a todo Canadá y EE.UU.',
    product_volume_promo: '🚀 ¡Descuento por volumen: compra 2 o más y ahorra! 🚀',
    product_reviews_count: 'Reseñas',
    product_questions_count: 'Preguntas',
    product_ask_question: 'Hacer una pregunta',
    product_size_guide: 'GUÍA DE TALLAS',
    product_plus_size_alert: '* Talla Plus Size seleccionada',
    product_size_tip: '💡 Tip de Talla: Nuestras camisetas tienen corte atlético ajustado. Si prefieres un ajuste más holgado, recomendamos pedir una talla más grande.',
    product_custom_name: 'NOMBRE',
    product_custom_number: 'NÚMERO',
    product_wholesale_header: '🔥 Guía de Tallas Oficial',
    product_table_length: 'LARGO',
    product_table_width: 'ANCHO',
    product_table_height: 'ALTURA SUG.',
    product_table_weight: 'PESO SUG.',
    product_social_title: 'Lo que dicen nuestros clientes',
    product_social_subtitle_part1: 'Ya somos ',
    product_social_subtitle_part2: ' vistiendo la pasión en Canadá y EE.UU. 🍁',
    product_faq_title: 'Preguntas Frecuentes',
    product_cta_secure: 'Compra Segura',
    product_cta_guarantee: 'Garantizamos la calidad del producto y soporte completo vía WhatsApp.',
    success_title: '¡Pedido Recibido! ⚽',
    success_subtitle: 'Tu camiseta está siendo preparada.',
    success_subtitle_paid: '¡Tu pago ha sido confirmado!',
    success_message: 'Hemos enviado un resumen detallado a tu email. Por favor revisa tu bandeja de entrada (y spam).',
    success_whatsapp_error: '¿No pudiste abrir WhatsApp?',
    success_whatsapp_btn: 'Enviar Resumen Manualmente',
    success_support_btn: 'Chatear con nuestro equipo',
    success_home_btn: 'Volver a la Tienda',
    auth_title: 'Zona Fan',
    auth_subtitle: 'Inicia sesión para rastrear tus pedidos y completar tus compras en iFooty.',
    auth_loading: 'Esperando a Google...',
    auth_google_btn: 'Iniciar sesión con Google',
    auth_terms: 'Al iniciar sesión, aceptas nuestros términos de privacidad y política de envíos.',
    auth_error_default: 'Error al iniciar sesión. Inténtalo de nuevo.',
    profile_loading: 'Cargando perfil...',
    profile_tab_orders: 'Mis Pedidos',
    profile_tab_feedback: 'Mi Feedback',
    profile_logout: 'Cerrar Sesión',
    profile_orders_loading: 'Buscando tus camisetas...',
    profile_no_orders_title: 'No se encontraron pedidos.',
    profile_no_orders_text: 'Aún no has hecho ningún pedido. ¡Explora nuestras colecciones!',
    profile_explore_btn: 'Explorar Colección',
    profile_status_pending: '🟡 Esperando Confirmación',
    profile_status_paid: '💳 Pagado',
    profile_status_processing: '🔵 Preparando Envío',
    profile_status_shipped: '🟢 Enviado',
    profile_status_completed: '✅ Entregado',
    profile_status_cancelled: '❌ Cancelado',
    profile_delivery: 'Envío a:',
    profile_order_prefix: 'Pedido #',
    profile_feedback_title: '¿Qué te pareció iFooty? 🗣️',
    profile_feedback_subtitle: '¡Tu opinión nos ayuda a crecer!',
    profile_feedback_rating_label: 'Califica tu experiencia:',
    profile_feedback_location_label: '¿Desde dónde compraste? (Ciudad, Provincia)',
    profile_feedback_location_placeholder: 'Ej: Toronto, ON',
    profile_feedback_comment_label: 'Tu comentario:',
    profile_feedback_comment_placeholder: 'Comparte tu experiencia con el producto, entrega y servicio...',
    profile_feedback_submitting: 'Enviando...',
    profile_feedback_submit: 'Publicar Reseña',
    profile_feedback_my_reviews: 'Mis Reseñas Enviadas',
    profile_feedback_loading: 'Cargando historial...',
    profile_feedback_empty: 'Aún no has enviado reseñas.',
    profile_feedback_approved: 'Publicado',
    profile_feedback_pending_review: 'En Revisión',
    profile_feedback_sent_on: 'Enviado el:',
    profile_feedback_error: 'Error al enviar reseña: ',
    profile_feedback_success: '¡Reseña enviada! Aparecerá después de moderación.',
    category_home: 'Inicio',
    category_items_found: 'artículos encontrados',
    category_filters: 'Filtros',
    category_filter_fan: 'Edición Fan',
    category_filter_player: 'Edición Jugador',
    category_filter_retro: 'Retro',
    category_jersey_version: 'Versión de Camiseta',
    category_clear_filters: 'Limpiar filtros',
    category_filter_btn: 'Filtrar Productos',
    category_showing: 'Mostrando',
    category_of: 'de',
    category_products: 'productos',
    category_filtered_by: 'filtrado por:',
    category_sort_by: 'Ordenar por:',
    category_sort_popular: 'Más Populares',
    category_sort_price_asc: 'Menor Precio',
    category_sort_price_desc: 'Mayor Precio',
    category_loading: 'Buscando camisetas...',
    category_empty_title: '¡Vestuario vacío!',
    category_empty_text: 'No se encontraron camisetas para esta categoría.',
    checkout_login_title: '¡Espera, goleador!',
    checkout_login_text: 'Necesitas iniciar sesión para reservar tus camisetas.',
    checkout_login_btn: 'Iniciar Sesión / Registrarse',
    checkout_delivery_title: 'Entrega en Canadá / EE.UU.',
    checkout_summary_title: 'Resumen',
    checkout_subtotal: 'Subtotal',
    checkout_discount: 'Descuento por Volumen',
    checkout_back_btn: 'Volver',
    checkout_attention: 'Atención',
    checkout_attention_btn: '¡Entendido!',
    checkout_select_province: 'Seleccionar...',
    checkout_name: 'Nombre Completo *',
    checkout_street: 'Dirección *',
    checkout_apt: 'Apto/Suite',
    checkout_city: 'Ciudad *',
    checkout_province: 'Provincia *',
    checkout_postal: 'Código Postal *',
    checkout_phone: 'Teléfono *',
    checkout_social: 'Instagram o WhatsApp (Opcional)',
    checkout_social_placeholder: 'Ej: @tuinsta o Teléfono',
    checkout_save_address: 'Guardar esta dirección para futuras compras',
    checkout_validation_error: 'Por favor completa todos los campos obligatorios.',
    checkout_processing: 'Procesando...',
    checkout_confirm_btn: 'Confirmar Pedido (WhatsApp)',
    checkout_cart_empty_title: 'Tu carrito está vacío.',
    checkout_back_shopping: 'Volver a la Tienda',
    checkout_wa_order_title: '*NUEVO PEDIDO - iFooty*',
    checkout_wa_customer: '*CLIENTE:*',
    checkout_wa_shipping: '*DIRECCIÓN DE ENVÍO:*',
    checkout_wa_items: '*ARTÍCULOS DEL PEDIDO:*',
    checkout_wa_total: '*TOTAL:*',
    checkout_wa_footer: '¡Espero instrucciones para el Interac e-Transfer! 🇨🇦',
    payment_method_title: 'Método de Pago',
    coming_soon: 'Próximamente',
    success_message_paid: 'Recibimos tu pedido pagado. Recibirás el código de rastreo pronto.',
    success_support_wa_msg_paid: '¡Hola! Acabo de hacer un pedido pagado vía PayPal y quiero rastrear el envío. 😊',
    product_ready_delivery: '⚡ En Stock - Envío en 24h',
    product_stock_units: 'Solo quedan {count} unidades en Canadá y EE.UU.',
    product_stock_sizes_available: 'Disponible en Stock (Envío 24h):',
    product_stock_preorder: 'Tallas por encargo (10-15 días):',
    checkout_title: 'Entrega o Recogida',
    checkout_home_delivery: 'Entrega a Domicilio',
    checkout_home_delivery_desc: 'Envío Estándar (10-15 días)',
    checkout_pickup_delivery: 'Recoger en Wolf Willow',
    checkout_pickup_delivery_desc: 'Envío Gratis',
    checkout_pickup_alert_title: '⚠️ IMPORTANTE: Recogida Solo Tras Confirmación',
    checkout_pickup_alert_text: 'La recogida en Wolf Willow solo está disponible previa confirmación de stock local.',
    checkout_autocomplete_label: 'Comienza por el Nº y Calle (Autocompletar) *',
    checkout_autocomplete_hint: '💡 Escribe el número primero para completar el resto.',
    checkout_address_number: 'Número *',
    checkout_district: 'Distrito *',
    checkout_unit: 'Unidad (Apto)',
    checkout_city_label: 'Ciudad *',
    checkout_province_label: 'Estado/Provincia *',
    checkout_country_label: 'País',
    exit_title: 'Antes de irte...',
    exit_subtitle: 'Lamentamos que no hayas encontrado lo que buscabas.',
    exit_label: '¿Qué producto te gustaría ver aquí en iFooty?',
    exit_placeholder: 'Ej: Camiseta retro de Brasil 1970...',
    exit_btn_submit: 'Enviar Sugerencia',
    exit_submitting: 'Enviando...',
    exit_footer: '¡Prometemos intentar traer esa novedad! ⚽',
    exit_success: '¡Gracias por tu feedback! Lo revisaremos. ⚽',
    exit_error: 'Ocurrió un error al enviar. Inténtalo más tarde.',

    // ═══ REBRAND KEYS (rb_*) — ES ═══
    rb_free_shipping: 'Envío Gratis a todo Canadá',
    rb_vip_whatsapp: 'Grupo VIP WhatsApp',
    rb_track_order: 'Rastrear Pedido',
    rb_my_account: 'Mi Cuenta',
    rb_hello_sign_in: 'Hola, Iniciar Sesión',
    rb_guest: 'Invitado',
    rb_popup_weekly_deal: 'Oferta de la Semana',
    rb_popup_get_extra: 'CONSIGUE 10% OFF EXTRA',
    rb_popup_subtitle: 'Añade las camisetas en promoción a tu carrito y usa el cupón en el checkout:',
    rb_popup_coupon_label: 'CUPÓN:',
    rb_popup_copied: 'Copiado',
    rb_popup_copy: 'Copiar',
    rb_popup_selected_promos: '🏷️ Camisetas Seleccionadas en Oferta',
    rb_popup_added: '¡Añadido!',
    rb_popup_add: 'Añadir',
    rb_popup_disclaimer: '* Cupón de 10% válido para todas las compras.',
    rb_popup_view_all: 'Ver Todas las Camisetas en Oferta',
    rb_my_cart: 'Mi Carrito',
    rb_jerseys_bag: 'Bolsa',
    rb_search_placeholder: 'Encuentra tu equipo favorito...',
    rb_slogan: 'Tienda de Camisetas Deportivas de Canadá',
    rb_admin_panel: 'Panel Admin',
    rb_my_profile: 'Mi Perfil',
    rb_guest_checkout: 'Checkout Invitado',
    rb_sign_out: 'Cerrar Sesión',
    rb_exit_guest: 'Salir del Modo Invitado',
    rb_nav_soccer: 'Fútbol',
    rb_nav_basketball: 'Baloncesto',
    rb_nav_football: 'Fútbol Americano',
    rb_nav_baseball: 'Béisbol',
    rb_nav_hockey: 'Hockey',
    rb_nav_new_arrivals: 'Novedades',
    rb_nav_best_sellers: 'Más Vendidos',
    rb_nav_sale: 'Ofertas',
    rb_footer_shipping_title: 'Envío a Todo Canadá',
    rb_footer_shipping_desc: 'Envío gratis en pedidos premium',
    rb_footer_quality_title: '100% Calidad Premium',
    rb_footer_quality_desc: 'Detalles y telas cosidos oficialmente',
    rb_footer_support_title: 'Soporte VIP 24/7',
    rb_footer_support_desc: 'Habla directamente con nuestro equipo vía WhatsApp',
    rb_footer_about_text: 'En iFooty, nos apasiona conectar a los fans del deporte con camisetas premium de las ligas y selecciones más grandes del mundo. Del fútbol al hockey, baloncesto, fútbol americano y béisbol, ayudamos a los fans a vestir su pasión todos los días.',
    rb_footer_shop_by_sport: 'Compra por Deporte',
    rb_footer_soccer_jerseys: '⚽ Camisetas de Fútbol',
    rb_footer_basketball_jerseys: '🏀 Camisetas de Baloncesto',
    rb_footer_football_jerseys: '🏈 Camisetas de Fútbol Americano',
    rb_footer_baseball_jerseys: '⚾ Camisetas de Béisbol',
    rb_footer_hockey_jerseys: '🏒 Camisetas de Hockey',
    rb_footer_info_service: 'Info y Servicio',
    rb_footer_track_order: 'Rastrear Pedido',
    rb_footer_about_us: 'Sobre Nosotros',
    rb_footer_affiliate: 'Programa de Afiliados',
    rb_footer_contact: 'Contáctanos',
    rb_footer_join_vip: 'Unirse al Grupo VIP WhatsApp',
    rb_footer_rights: 'Tienda de Camisetas Deportivas de Canadá. Todos los derechos reservados.',
    rb_prod_back_catalog: 'Volver al Catálogo',
    rb_prod_reviews: 'Reseñas',
    rb_prod_size: 'Talla',
    rb_prod_size_guide: 'Guía de Tallas',
    rb_prod_whats_included: 'Qué Incluye',
    rb_prod_full_kit: 'Kit Completo (Camiseta + Short)',
    rb_prod_shirt_only: 'Solo Camiseta',
    rb_prod_add_custom: 'Agregar Nombre y Número Personalizados',
    rb_prod_player_name: 'Nombre del Jugador (ej: MAHOMES)',
    rb_prod_player_number: 'Número (ej: 15)',
    rb_prod_add_patch: 'Agregar Parche',
    rb_prod_patch_placeholder: 'Parche Deseado (ej: Champions League)',
    rb_prod_quantity: 'Cantidad',
    rb_prod_add_to_cart: 'Agregar al Carrito',
    rb_prod_shipping: 'Envío',
    rb_prod_shipping_leaves: 'Este artículo sale de nuestro almacén en 1-3 días hábiles.',
    rb_prod_shipping_ready: '✓ Listo para Enviar inmediatamente al procesar.',
    rb_prod_shipping_free: 'Elegible para envío gratis a todo Canadá en pedidos superiores a $99 CAD.',
    rb_prod_description: 'Descripción',
    rb_prod_premium_quality: 'Calidad Premium',
    rb_prod_high_grade: 'Telas de alta calidad',
    rb_prod_defect_warranty: 'Garantía Contra Defectos',
    rb_prod_factory_covered: '100% cubierto por fábrica',
    rb_prod_fast_shipping: 'Envío Rápido',
    rb_prod_with_tracking: 'Con número de rastreo',
    rb_prod_loading: 'Cargando producto...',
    rb_prod_not_found: 'Producto no encontrado.',
    rb_prod_free_shipping_eligible: '✓ Envío Gratis Elegible',
    rb_search_title: 'Resultados de Búsqueda',
    rb_search_results_for: 'Resultados para',
    rb_search_no_results: 'No se encontraron resultados.',
    rb_search_try_again: 'Intenta buscar con otros términos.',
    rb_cart_title: 'Bolsa de Camisetas',
    rb_cart_empty: 'Tu bolsa está vacía.',
    rb_cart_start_shopping: '¡Empieza a comprar!',
    rb_cart_subtotal: 'Subtotal',
    rb_cart_volume_discount: 'Descuento por Volumen',
    rb_cart_shipping: 'Envío',
    rb_cart_free: 'GRATIS',
    rb_cart_total: 'Total',
    rb_cart_checkout: 'Finalizar Compra',
    rb_cart_continue: 'Seguir Comprando',
    rb_cart_remove: 'Eliminar',
    rb_cart_size: 'Talla',
    rb_cart_custom: 'Personalización',
    rb_checkout_title: 'Entrega o Recogida',
    rb_checkout_home_delivery: 'Entrega a Domicilio',
    rb_checkout_home_delivery_desc: 'Enviado a tu puerta (10-15 días)',
    rb_checkout_pickup: 'Recoger en Wolf Willow',
    rb_checkout_pickup_desc: 'Envío Gratis',
    rb_checkout_login_title: '¡Inicia sesión primero!',
    rb_checkout_login_text: 'Necesitas iniciar sesión para completar tu pedido.',
    rb_checkout_login_btn: 'Iniciar Sesión / Registrarse',
    rb_checkout_summary: 'Resumen',
    rb_checkout_subtotal: 'Subtotal',
    rb_checkout_discount: 'Descuento por Volumen',
    rb_checkout_shipping_cost: 'Envío',
    rb_checkout_handling: 'Tarifa de Manejo',
    rb_checkout_total: 'Total',
    rb_checkout_place_order: 'Realizar Pedido',
    rb_checkout_processing: 'Procesando...',
    rb_checkout_name: 'Nombre Completo *',
    rb_checkout_street: 'Dirección *',
    rb_checkout_apt: 'Apto/Suite',
    rb_checkout_city: 'Ciudad *',
    rb_checkout_province: 'Provincia *',
    rb_checkout_postal: 'Código Postal *',
    rb_checkout_phone: 'Teléfono *',
    rb_checkout_country: 'País',
    rb_checkout_payment: 'Método de Pago',
    rb_checkout_empty: 'Tu carrito está vacío.',
    rb_checkout_back: 'Volver a la Tienda',
    rb_auth_title: 'Zona Aficionado',
    rb_auth_subtitle: 'Inicia sesión para rastrear tus pedidos y completar tus compras en iFooty.',
    rb_auth_google: 'Iniciar sesión con Google',
    rb_auth_loading: 'Esperando a Google...',
    rb_auth_terms: 'Al iniciar sesión, aceptas nuestros términos de privacidad y política de envíos.',
    rb_auth_error: 'Error al iniciar sesión. Inténtalo de nuevo.',
    rb_auth_loading_google: 'Cargando inicio de sesión de Google...',
    rb_auth_or_email_code: 'O USA CÓDIGO POR CORREO',
    rb_auth_email_placeholder: 'Ingresa tu correo electrónico',
    rb_auth_send_code: 'Enviar Código de Verificación',
    rb_auth_code_sent_to: 'Enviamos el código de verificación a:',
    rb_auth_verify_signin: 'Verificar Código e Iniciar Sesión',
    rb_auth_change_email: 'Cambiar correo',
    rb_auth_processing: 'Procesando, por favor espera...',
    rb_profile_loading: 'Cargando perfil...',
    rb_profile_orders: 'Mis Pedidos',
    rb_profile_feedback: 'Mi Feedback',
    rb_profile_sign_out: 'Cerrar Sesión',
    rb_profile_no_orders: 'No se encontraron pedidos.',
    rb_profile_no_orders_text: 'Aún no has hecho ningún pedido. ¡Explora nuestras colecciones!',
    rb_profile_explore: 'Explorar Colección',
    rb_profile_order: 'Pedido',
    rb_profile_status_pending: '🟡 Esperando Confirmación',
    rb_profile_status_paid: '💳 Pagado',
    rb_profile_status_processing: '🔵 Preparando Envío',
    rb_profile_status_shipped: '🟢 Enviado',
    rb_profile_status_completed: '✅ Entregado',
    rb_profile_status_cancelled: '❌ Cancelado',
    rb_about_title: 'Nuestra Historia ⚽',
    rb_about_text1: 'En iFooty, nos apasiona conectar a los fans del deporte con camisetas premium de las ligas y selecciones más grandes del mundo.',
    rb_about_text2: 'Nacida en Canadá en 2022, crecimos de una pequeña operación a una tienda de confianza sirviendo fans de costa a costa.',
    rb_affiliates_title: 'Programa de Afiliados',
    rb_affiliates_subtitle: 'Gana comisión recomendando camisetas de iFooty',
    rb_language: 'Idioma',
    rb_home_hero_title: 'VISTE TU EQUIPO.',
    rb_home_hero_subtitle: 'Encuentra Tu Camiseta Favorita',
    rb_home_shop_now: 'Comprar Ahora',
    rb_home_trending: 'Tendencia Ahora 🔥',
    rb_home_trending_subtitle: 'Las camisetas más buscadas esta semana',
    rb_home_shop_by_sport: 'Compra por Deporte',
    rb_home_view_collection: 'Ver Colección',
    rb_home_testimonials_title: 'Lo Que Dicen Nuestros Clientes',
    rb_home_testimonials_subtitle: 'Únete a cientos de fans satisfechos en Canadá y EE.UU.',
    rb_home_customer_since: 'Cliente desde',
    rb_home_faq_title: 'Preguntas Frecuentes',
    rb_home_promo_title: '🔥 OFERTA ESPECIAL',
    rb_home_promo_jerseys: 'Camisetas',
    rb_home_promo_for_only: 'por solo',
    rb_home_promo_each: 'cada una',
    rb_home_promo_save: 'Ahorras',
    rb_home_promo_apply: 'Aplicar Descuento',
    rb_home_promo_best: 'Mejor Oferta',
    rb_home_view_all: 'Ver Todos',
    rb_home_browse_licensed: 'Colección Oficial Licenciada',
    rb_home_shop_by_league: 'Comprar por Liga',
    rb_home_starting_at: 'Desde',
    rb_home_featured_in: 'Destacados en',
    rb_home_spotlight_collection: 'Colección Destacada',
    rb_home_special_bundle_deals: '⚡ Ofertas y Combos Especiales',
    rb_home_buy_2_jerseys: 'Compra 2 Camisetas',
    rb_home_buy_3_jerseys: 'Compra 3 Camisetas',
    rb_home_get_2_for_only: 'Llévalas por solo',
    rb_home_save: 'Ahorra',
    rb_home_select_jerseys: 'Elegir Camisetas',
    rb_home_best_deal: 'Mejor Oferta',
    rb_home_discounts_calculated_at_checkout: '* Los descuentos se calculan y aplican automáticamente en el checkout',
    rb_home_trending_fan_gear: 'Camisetas Tendencia',
    rb_home_show_all: 'Ver Todas',
    rb_home_trending_teams_in_canada: 'EQUIPOS TENDENCIA EN CANADÁ',
    rb_sport_soccer: 'Fútbol',
    rb_sport_basketball: 'Baloncesto',
    rb_sport_football: 'Fútbol Americano',
    rb_sport_baseball: 'Béisbol',
    rb_sport_hockey: 'Hockey',
    rb_badge_new_arrival: 'Novedad',
    rb_badge_best_seller: 'Más Vendido',
    rb_badge_sale: 'Oferta',
    rb_badge_almost_gone: 'Pocas Unidades',
    rb_badge_trending: 'Tendencia',
    rb_cat_back_home: 'Volver al Inicio',
    rb_cat_jerseys: 'Camisetas',
    rb_cat_items_found: 'artículos encontrados',
    rb_cat_filters: 'Filtros',
    rb_cat_jersey_version: 'Versión de Camiseta',
    rb_cat_fan: 'Edición Fan',
    rb_cat_player: 'Edición Jugador',
    rb_cat_retro: 'Retro',
    rb_cat_league: 'Liga',
    rb_cat_team: 'Equipo',
    rb_cat_all: 'Todos',
    rb_cat_clear_filters: 'Limpiar Filtros',
    rb_cat_official_fan_shop: 'Tienda Oficial Fan',
    rb_cat_items: 'ARTÍCULOS',
    rb_cat_up_to_discount: '● Hasta 30% de descuento en artículos seleccionados',
    rb_cat_shop_by_category: 'Comprar por Categoría',
    rb_cat_department: 'Departamento',
    rb_cat_league_comp: 'Liga / Competición',
    rb_cat_gender_age: 'Género / Edad',
    rb_cat_teams: 'Equipos',
    rb_cat_all_teams: 'Todos los Equipos',
    rb_cat_players: 'Jugadores',
    rb_cat_all_players: 'Todos los Jugadores',
    rb_cat_price_range: 'Rango de Precio',
    rb_cat_all_prices: 'Todos los Precios',
    rb_cat_under_100: 'Menos de $100 CAD',
    rb_cat_over_100: 'Más de $100 CAD',
    rb_cat_men: 'Hombre',
    rb_cat_women: 'Mujer',
    rb_cat_kids: 'Niños & Juvenil',
    rb_cat_tshirts: 'Camisetas',
    rb_cat_caps: 'Gorras & Sombreros',
    rb_cat_hoodies: 'Sudaderas',
    rb_cart_urgency_banner: '¡Los artículos pueden agotarse, pide ahora!',
    rb_cart_each: 'cada',
    rb_cart_have_promo_code: '¿Tienes un código de descuento?',
    rb_cart_promo_code: 'Código de Descuento',
    rb_cart_add: 'AGREGAR',
    rb_cart_edit: 'EDITAR',
    rb_cart_applied: 'aplicado',
    rb_cart_apply: 'Aplicar',
    rb_checkout_guest_continue: 'Continuar sin cuenta',
    rb_checkout_or: 'O',
    rb_checkout_signin_create: 'Iniciar Sesión / Crear Cuenta',
    rb_checkout_signin_desc: 'Inicia sesión o crea una cuenta para rastrear pedidos y guardar tu dirección.',
    rb_checkout_delivery_method: 'Método de Entrega',
    rb_checkout_home_delivery_label: 'Entrega a Domicilio',
    rb_checkout_shipped_to_door: 'Enviado a tu puerta (10 - 15 días)',
    rb_checkout_local_pickup: 'Recogida Local',
    rb_checkout_pickup_subtext: 'GRATIS — Calgary, AB',
    rb_checkout_contact_info: 'Información de Contacto',
    rb_checkout_full_name: 'Nombre Completo',
    rb_checkout_as_on_id: 'Como en tu documento',
    rb_checkout_phone_number: 'Teléfono',
    rb_checkout_shipping_address: 'Dirección de Envío',
    rb_checkout_postal_code: 'Código Postal',
    rb_checkout_street_address: 'Calle y Dirección',
    rb_checkout_type_autocomplete: '(escribe para autocompletar)',
    rb_checkout_number: 'Número',
    rb_checkout_neighbourhood: 'Barrio / Colonia',
    rb_checkout_unit_apt: 'Apto / Unidad (Opcional)',
    rb_checkout_province_state: 'Estado / Provincia',
    rb_checkout_instructions: 'Instrucciones de Entrega (Opcional — SOLO EN INGLÉS)',
    rb_checkout_instructions_placeholder: 'Ej: Dejar en la puerta principal, código 1234...',
    rb_checkout_save_address: 'Guardar mi dirección para futuras compras',
    rb_checkout_order_summary: 'Resumen del Pedido',
    rb_checkout_payment_method: 'Método de Pago',
    rb_checkout_place_order_wa: 'Realizar Pedido por WhatsApp',
    rb_checkout_pay_card: 'Pagar con Tarjeta',
    rb_checkout_secure: 'Pago Seguro y Encriptado',
    rb_checkout_ready_to_ship_banner: 'Este artículo sale de nuestro almacén en 1–4 días hábiles. Elegible para envío gratis.',
    rb_cat_sort_by: 'Ordenar por:',
    rb_cat_sort_popular: 'Más Populares',
    rb_cat_sort_newest: 'Más Recientes',
    rb_cat_sort_price_asc: 'Menor Precio',
    rb_cat_sort_price_desc: 'Mayor Precio',
    rb_cat_showing: 'Mostrando',
    rb_cat_of: 'de',
    rb_cat_products: 'productos',
    rb_cat_loading: 'Buscando camisetas...',
    rb_cat_empty_title: '¡Vestuario vacío!',
    rb_cat_empty_text: 'No se encontraron camisetas para esta categoría.',
    rb_cat_load_more: 'Cargar Más',
    rb_cat_previous: 'Anterior',
    rb_cat_next: 'Siguiente',
  }
};

// ─── LANGUAGE PREFERENCE MIGRATION ─────────────────────────────────────────────
// v1 key: 'preferredLanguage' (legacy, default was 'pt')
// v2 key: 'preferredLanguage_v2' (rebrand, default is 'en')
//
// Migration strategy:
// - If v2 exists → use it (user already chose under rebrand)
// - If v2 does NOT exist → new user OR legacy user → default to 'en'
// - The old v1 key is NOT read, preventing legacy 'pt' from leaking into rebrand
// ────────────────────────────────────────────────────────────────────────────────

const LANG_STORAGE_KEY = 'preferredLanguage_v2';
const SUPPORTED_LANGUAGES = ['en', 'pt', 'es'];

function getInitialLanguage() {
  try {
    const saved = localStorage.getItem(LANG_STORAGE_KEY);
    if (saved && SUPPORTED_LANGUAGES.includes(saved)) {
      return saved;
    }
  } catch (e) {
    // localStorage unavailable (SSR, incognito, etc.)
  }
  return 'en'; // default for new users and legacy migration
}

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(getInitialLanguage);
  const [currency, setCurrencyState] = useState(localStorage.getItem('preferredCurrency') || 'CAD');
  const [exchangeRate, setExchangeRate] = useState(0.73);

  const setLanguage = (lang) => {
    if (SUPPORTED_LANGUAGES.includes(lang)) {
      setLanguageState(lang);
    }
  };

  const setCurrency = (curr) => {
    setCurrencyState(curr);
    localStorage.setItem('preferredCurrency', curr);
  };

  // Persist language preference & update HTML lang attribute
  useEffect(() => {
    try {
      localStorage.setItem(LANG_STORAGE_KEY, language);
    } catch (e) {
      // localStorage unavailable
    }
    const langMap = { en: 'en', pt: 'pt-BR', es: 'es' };
    document.documentElement.lang = langMap[language] || 'en';
  }, [language]);

  // Auto-detect currency by IP (first visit only)
  useEffect(() => {
    const savedCurrency = localStorage.getItem('preferredCurrency');
    if (!savedCurrency) {
      const detectIP = async () => {
        try {
          const res = await fetch('https://ipapi.co/json/');
          if (res.ok) {
            const data = await res.json();
            if (data && data.country_code === 'US') {
              setCurrency('USD');
            } else {
              setCurrency('CAD');
            }
          }
        } catch (e) {
          console.warn("Failed to detect country by IP:", e);
        }
      };
      detectIP();
    }
  }, []);

  // Fetch live exchange rate
  useEffect(() => {
    const fetchRate = async () => {
      try {
        const res = await fetch('https://open.er-api.com/v6/latest/CAD');
        if (res.ok) {
          const data = await res.json();
          if (data && data.rates && data.rates.USD) {
            setExchangeRate(data.rates.USD);
          }
        }
      } catch (e) {
        console.warn("Failed to fetch live exchange rate:", e);
      }
    };
    fetchRate();
  }, []);

  const convertPrice = (priceInCAD) => {
    const val = Number(priceInCAD || 0);
    if (currency === 'USD') {
      return val * exchangeRate;
    }
    return val;
  };

  const formatPrice = (priceInCAD) => {
    const converted = convertPrice(priceInCAD);
    return `$${converted.toFixed(2)} ${currency}`;
  };

  const toggleCurrency = () => {
    setCurrency(currency === 'CAD' ? 'USD' : 'CAD');
  };

  // Safe fallback: current language → EN → raw key
  const t = (key) => {
    return translations?.[language]?.[key] ?? translations?.en?.[key] ?? key;
  };

  // Legacy product name translation (PT → EN mapping, kept for compatibility)
  const translateProductDisplay = (name) => {
    if (language === 'pt') return name;

    let translated = name;
    const mapping = {
      'Camisa ': '',
      'Titular': 'Home Jersey',
      'Reserva': 'Away Jersey',
      'Terceira': 'Third Jersey',
      'Goleiro': 'Goalkeeper',
      'Treino': 'Training',
      'Infantil': 'Kids',
      'Feminina': 'Womens',
      'Jogador': 'Player Edition',
      'Torcedor': 'Fan Edition',
      'Fã': 'Fan Edition'
    };

    Object.entries(mapping).forEach(([pt, en]) => {
      const regex = new RegExp(pt, 'gi');
      translated = translated.replace(regex, en);
    });

    return translated.trim();
  };

  // Legacy compatibility — toggles between PT and EN only
  // Kept for backward compatibility; new code should use setLanguage(lang)
  const toggleLanguage = () => {
    setLanguageState(prev => prev === 'pt' ? 'en' : 'pt');
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t, translateProductDisplay, currency, setCurrency, exchangeRate, convertPrice, formatPrice, toggleCurrency }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
