import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  pt: {
    nav_home: 'Home',
    nav_br: 'Brasileirão',
    nav_intl: 'Internacionais',
    nav_retro: 'Retrô',
    top_bar_announcement: '⚡ Entrega para todo Canadá | Para Calgary (24h), se disponível',
    nav_admin: 'Admin',
    hero_title_part1: 'VISTA AS CORES DO SEU TIME MESMO ',
    hero_title_accent: 'LONGE DE CASA',
    hero_subtitle: 'Camisas brasileiras, europeias e internacionais',
    hero_satisfied_clients: '⭐ +200 clientes satisfeitos no Canadá',
    hero_shipping_all: 'Todo o Canadá',
    hero_shipping_calgary: 'Entrega prioritária para Calgary',
    hero_shipping_guaranteed: 'Entrega garantida',
    hero_shipping_moneyback: 'Ou devolução do dinheiro',
    hero_btn_guarantee: 'GARANTIR MINHA CAMISA',
    hero_btn_view_all: 'Ver todas as camisas',
    btn_shop_now: 'Ver Catálogo',
    section_favorites: 'Nossas Queridinhas',
    section_best_seller: 'Mais Vendida do Momento',
    section_new: 'Lançamento',
    section_categories: 'Navegue por Categorias',
    promo_banner_title: '🔥 OFERTA ESPECIAL',
    promo_banner_combo2: '2 Camisas',
    promo_banner_combo3: '3 Camisas',
    promo_banner_from: 'De',
    promo_banner_for: 'por apenas',
    promo_banner_each: 'cada',
    promo_banner_savings: 'Economia de',
    promo_banner_apply: 'Aplicar desconto',
    promo_banner_best_offer: 'Maior Desconto',
    product_price_transfer: 'no e-Transfer',
    product_customization: 'Personalização',
    product_customization_none: 'Não',
    product_customization_yes: 'Somente Personalizado',
    product_size: 'Tamanho',
    product_qty: 'Quantidade',
    product_buy_now: 'COMPRAR AGORA',
    product_wholesale_table: '🔥 Tabela de Atacado / Combos',
    product_wholesale_unit: 'unit.',
    product_wholesale_each: 'cada',
    cart_title: 'Minha Sacola',
    cart_empty: 'Sua sacola está vazia.',
    cart_subtotal: 'Subtotal',
    cart_discount: 'Desconto de Volume',
    cart_total: 'Total',
    cart_checkout: 'Finalizar Pedido',
    cart_continue_shopping: 'Continuar Comprando',
    sales_popup_bought: 'comprou',
    sales_popup_time: 'Comprado',
    stats_clients: 'Clientes satisfeitos no Canadá',
    stats_shipping: 'Taxa de envio no prazo',
    stats_whatsapp: 'Resposta média no WhatsApp',
    stats_payment: 'Pagamento seguro garantido',
    section_favorites_title: 'As Queridinhas 🇧🇷',
    section_favorites_subtitle: 'Deslize para ver os mantos sagrados mais pedidos.',
    promo_footer_note: '* Preços baseados na camisa padrão. O desconto se aplica a qualquer peça. Adicione à sacola e a mágica acontece!',
    customization_title: 'Deixe sua camisa única ✍️',
    customization_subtitle: 'Você poderá solicitar a personalização com a mesma fonte oficial dos jogadores diretamente dentro das opções do produto.',
    customization_item1: 'Nome + Número',
    customization_item2: 'Patch de Campeonatos',
    emotional_title: 'Porque ser torcedor não tem distância 🇧🇷',
    emotional_text: 'A saudade do seu país e a paixão pelo futebol vivem na mesma gaveta. Entregamos a qualidade de jogador profissional diretamente na sua porta no Canadá.',
    social_proof_title: 'Voz da Arquibancada 🗣️',
    social_proof_subtitle: 'Desde 2022, conectando brasileiros em todo o Canadá com seus mantos favoritos.',
    social_proof_client_since: 'Cliente desde',
    social_proof_swipe: 'Deslize lateralmente para ler mais →',
    faq_title: 'Dúvidas Rápidas',
    faq_q1: 'Vocês entregam em todo o Canadá?',
    faq_a1: 'Sim, enviamos para todas as províncias e cidades do Canadá com rastreamento.',
    faq_q2: 'Qual o prazo de entrega?',
    faq_a2: 'Entre 10 e 20 dias úteis, dependendo de sua região.',
    faq_q3: 'Como escolher o tamanho?',
    faq_a3: 'Use seu tamanho normal ou peça para ver a tabela de medidas no WhatsApp. Para estilo largo (streetwear), escolha um número maior.',
    faq_q4: 'O pagamento é seguro?',
    faq_a4: '100% Seguro através de gateways blindados, ou aceitamos e-Transfer via Interac.',
    cta_security: 'Site 100% Blindado',
    cta_title: 'Garanta sua camisa antes que acabe!',
    cta_btn: 'Ver Catálogo',
    footer_about: 'A sua conexão com o futebol, onde quer que você esteja. Especialistas em camisas de futebol para brasileiros no Canadá.',
    footer_links: 'Links Rápidos',
    footer_how_to_buy: 'Como Comprar',
    footer_about_us: 'Sobre Nós',
    footer_payment: 'Pagamento',
    footer_payment_desc: 'Aceitamos transferências Interac simples, rápidas e seguras.',
    footer_rights: 'Todos os direitos reservados.',
    footer_dev: 'Desenvolvido por',
    footer_affiliates: 'Programa de Afiliados',
    footer_contact: 'Fale Conosco',
    nav_selecoes: 'Seleções',
    nav_lancamentos: 'Lançamentos',
    footer_catalog: 'Catálogo',
    about_title: 'Nossa História ⚽',
    about_text1: 'Nascida em Coquitlam/BC, em 2022, a iFooty surgiu de um desejo simples, mas poderoso: aproximar os brasileiros no Canadá de suas raízes. Sabemos que uma camisa de futebol não é apenas uma peça de roupa, é uma segunda pele que carrega memórias e pertencimento.',
    about_text2: 'Após conquistar nossa comunidade na Columbia Britânica, agora chegamos com tudo em Calgary, especializados em entregar mantos oficiais de alta qualidade para que cada grito de "gol" tenha o orgulho do seu time do coração.',
    success_support_wa_msg: 'Olá! Acabei de fazer um pedido na iFooty e gostaria de tirar algumas dúvidas. 😊',
    checkout_summary_footer_note: 'Você enviará um resumo do pedido para nosso atendimento. O pagamento só será feito após confirmarmos os detalhes do pedido com você. Pagamento via e-Transfer Interac!',
    // Home Extras
    home_numbers_title: 'Nossos números',
    home_empty_team: 'Nenhuma camisa encontrada no momento. Tente outro clube!',
    home_comes_out_to: 'Sai por',
    home_only: 'Sai por só',
    home_savings: 'Você economiza',
    home_view_all: 'Ver todas',
    home_best_options: 'As melhores opções em',
    home_comming_soon: 'Novidades em breve de',
    // Product Extras
    product_loading: 'Carregando produto...',
    product_not_found: 'Produto não encontrado.',
    product_free_shipping: 'Frete grátis para todo o Canadá',
    product_volume_promo: '🚀 Desconto progressivo: na compra de 2 ou mais camisas você economiza! 🚀',
    product_reviews_count: 'Avaliações',
    product_questions_count: 'Perguntas',
    product_size_guide: 'GUIA DE MEDIDAS',
    product_plus_size_alert: '* Tamanho Plus Size selecionado',
    product_custom_name: 'NOME',
    product_custom_number: 'NÚMERO',
    product_wholesale_header: '🔥 Guia de Medidas Oficial',
    product_table_length: 'COMPRIMENTO',
    product_table_width: 'LARGURA',
    product_table_height: 'ALTURA IND.',
    product_table_weight: 'PESO IND.',
    product_social_title: 'O que nossos clientes dizem',
    product_social_subtitle_part1: 'Já somos ',
    product_social_subtitle_part2: ' vestindo a paixão no Canadá! 🍁',
    product_faq_title: 'Perguntas Frequentes',
    product_faq_q1: 'As camisas são originais?',
    product_faq_a1: 'São camisas de alta qualidade estilo jogador, com acabamento premium idêntico.',
    product_faq_q2: 'Vocês entregam em todo o Canadá?',
    product_faq_a2: 'Sim, enviamos para todas as províncias e cidades do Canadá com rastreamento.',
    product_faq_q3: 'O pagamento é seguro?',
    product_faq_a3: '100% Seguro. Utilizamos gateways certificados e operamos preferencialmente e-Transfer para residentes canadenses.',
    product_cta_secure: 'Compra Segura',
    product_cta_guarantee: 'Garantimos a qualidade do produto e suporte completo ao cliente via WhatsApp.',
    // Success
    success_title: 'Pedido Recebido! ⚽',
    success_subtitle: 'Seu manto já está sendo preparado.',
    success_message: 'Enviamos um resumo detalhado para seu e-mail. Por favor, verifique sua caixa de entrada (e a pasta de spam).',
    success_whatsapp_error: 'Não conseguiu abrir o WhatsApp?',
    success_whatsapp_btn: 'Enviar Resumo Manualmente',
    success_support_btn: 'Tirar dúvidas com nossa equipe',
    success_home_btn: 'Voltar para a Loja',
    // Auth
    auth_title: 'Área do Torcedor',
    auth_subtitle: 'Identifique-se para acessar seus pedidos e concluir suas compras na iFooty.',
    auth_loading: 'Aguardando Google...',
    auth_google_btn: 'Entrar com Google',
    auth_terms: 'Ao entrar, você concorda com nossos termos de privacidade e política de envios internacionais.',
    auth_error_default: 'Erro ao fazer login. Tente novamente.',
    // Profile
    profile_loading: 'Carregando perfil...',
    profile_tab_orders: 'Meus Pedidos',
    profile_tab_feedback: 'Meu Feedback',
    profile_logout: 'Sair da Conta',
    profile_orders_loading: 'Buscando suas armaduras...',
    profile_no_orders_title: 'Nenhum pedido encontrado.',
    profile_no_orders_text: 'Você ainda não garantiu a sua armadura. Visite as coleções para escolher a sua!',
    profile_explore_btn: 'Explorar Coleção',
    profile_status_pending: '🟡 Aguardando Confirmação',
    profile_status_processing: '🔵 Preparando Envio',
    profile_status_shipped: '🟢 Enviado',
    profile_status_completed: '✅ Entregue',
    profile_status_cancelled: '❌ Cancelado',
    profile_delivery: 'Entrega:',
    profile_order_prefix: 'Pedido #',
    profile_feedback_title: 'O que você achou da iFooty? 🗣️',
    profile_feedback_subtitle: 'Sua opinião nos ajuda a crescer e ajuda outros brasileiros no Canadá!',
    profile_feedback_rating_label: 'Nota para sua experiência:',
    profile_feedback_location_label: 'De onde você comprou? (Cidade, Província)',
    profile_feedback_location_placeholder: 'Ex: Toronto, ON',
    profile_feedback_comment_label: 'Seu comentário:',
    profile_feedback_comment_placeholder: 'Conte sua experiência com o produto, entrega e atendimento...',
    profile_feedback_submitting: 'Enviando...',
    profile_feedback_submit: 'Publicar Depoimento',
    profile_feedback_my_reviews: 'Meus Depoimentos Enviados',
    profile_feedback_loading: 'Carregando histórico...',
    profile_feedback_empty: 'Você ainda não enviou feedbacks.',
    profile_feedback_approved: 'Publicado',
    profile_feedback_pending_review: 'Em Análise',
    profile_feedback_sent_on: 'Enviado em:',
    profile_feedback_error: 'Erro ao enviar feedback: ',
    profile_feedback_success: 'Depoimento enviado com sucesso! Ele aparecerá no site após a moderação.',
    // Category
    category_home: 'Início',
    category_items_found: 'itens encontrados',
    category_filters: 'Filtros',
    category_filter_fan: 'Torcedor',
    category_filter_player: 'Jogador',
    category_filter_retro: 'Retrô',
    category_jersey_version: 'Versão da Camisa',
    category_clear_filters: 'Limpar filtros',
    category_filter_btn: 'Filtrar Produtos',
    category_showing: 'Exibindo',
    category_of: 'de',
    category_products: 'produtos',
    category_filtered_by: 'filtrado por:',
    category_sort_by: 'Ordenar por:',
    category_sort_popular: 'Mais Populares',
    category_sort_price_asc: 'Menor Preço',
    category_sort_price_desc: 'Maior Preço',
    category_loading: 'Buscando o manto sagrado...',
    category_empty_title: 'Vestiário vazio!',
    category_empty_text: 'Não encontramos camisas para essa categoria no momento.',
    // Checkout
    checkout_login_title: 'Calma lá, artilheiro!',
    checkout_login_text: 'Você precisa se identificar no nosso sistema para separar suas camisas.',
    checkout_login_btn: 'Fazer Login / Cadastro',
    checkout_delivery_title: 'Entrega no Canadá',
    checkout_summary_title: 'Resumo',
    checkout_subtotal: 'Subtotal',
    checkout_discount: 'Desconto Progressivo',
    checkout_back_btn: 'Voltar',
    checkout_attention: 'Atenção',
    checkout_attention_btn: 'Entendido!',
    checkout_select_province: 'Selecione...',
    checkout_name: 'Nome Completo *',
    checkout_street: 'Endereço (Rua e Número) *',
    checkout_apt: 'Apto/Suite',
    checkout_city: 'Cidade *',
    checkout_province: 'Província *',
    checkout_postal: 'Postal Code *',
    checkout_social: 'Instagram ou WhatsApp (Opcional)',
    checkout_social_placeholder: 'Ex: @seuinsta ou Telefone',
    checkout_save_address: 'Salvar este endereço para futuras compras',
    checkout_validation_error: 'Por favor, preencha todos os campos obrigatórios de endereço.',
    checkout_processing: 'Processando...',
    checkout_confirm_btn: 'Confirmar Pedido (WhatsApp)',
    checkout_cart_empty_title: 'Seu carrinho está vazio.',
    checkout_wa_order_title: '*NOVO PEDIDO - iFOOTY*',
    checkout_wa_customer: '*CLIENTE:*',
    checkout_wa_shipping: '*ENDEREÇO DE ENTREGA:*',
    checkout_wa_items: '*ITENS DO PEDIDO:*',
    checkout_wa_total: '*TOTAL:*',
    checkout_wa_footer: 'Aguardo as instruções para o Interac e-Transfer! 🇨🇦',
  },
  en: {
    nav_home: 'Home',
    nav_br: 'Brazilian League',
    nav_intl: 'International',
    nav_retro: 'Retro',
    top_bar_announcement: '⚡ Delivery across Canada | Within 24h in Calgary if available',
    nav_admin: 'Admin',
    hero_title_part1: 'WEAR YOUR TEAM COLORS EVEN ',
    hero_title_accent: 'FAR FROM HOME',
    hero_subtitle: 'Brazilian, European and International Jerseys | Shipping across Canada',
    hero_satisfied_clients: '⭐ +200 satisfied customers in Canada',
    hero_shipping_all: 'All of Canada',
    hero_shipping_calgary: 'Priority delivery to Calgary',
    hero_shipping_guaranteed: 'Guaranteed delivery',
    hero_shipping_moneyback: 'Or money back guarantee',
    hero_btn_guarantee: 'GET YOUR JERSEY',
    hero_btn_view_all: 'View all jerseys',
    btn_shop_now: 'Shop Now',
    section_favorites: 'Our Favorites',
    section_best_seller: 'Current Best Seller',
    section_new: 'New Arrival',
    section_categories: 'Browse Categories',
    promo_banner_title: '🔥 SPECIAL OFFER',
    promo_banner_combo2: '2 Jerseys',
    promo_banner_combo3: '3 Jerseys',
    promo_banner_from: 'From',
    promo_banner_for: 'for only',
    promo_banner_each: 'each',
    promo_banner_savings: 'Savings of',
    promo_banner_apply: 'Apply Discount',
    promo_banner_best_offer: 'Best Offer',
    product_price_transfer: 'via e-Transfer',
    product_customization: 'Customization',
    product_customization_none: 'No',
    product_customization_yes: 'Personalized Only',
    product_size: 'Size',
    product_qty: 'Quantity',
    product_buy_now: 'BUY NOW',
    product_wholesale_table: '🔥 Wholesale Table / Combos',
    product_wholesale_unit: 'each',
    product_wholesale_each: 'each',
    cart_title: 'My Cart',
    cart_empty: 'Your cart is empty.',
    cart_subtotal: 'Subtotal',
    cart_discount: 'Volume Discount',
    cart_total: 'Total',
    cart_checkout: 'Checkout',
    cart_continue_shopping: 'Continue Shopping',
    sales_popup_bought: 'bought',
    sales_popup_time: 'Purchased',
    stats_clients: 'Satisfied customers in Canada',
    stats_shipping: 'On-time shipping rate',
    stats_whatsapp: 'Avg response time on WhatsApp',
    stats_payment: 'Secure payment guaranteed',
    section_favorites_title: 'Trending Jerseys 🇧🇷',
    section_favorites_subtitle: 'Swipe to see the most requested holy mantles.',
    promo_footer_note: '* Prices based on standard jerseys. Discount applies to any item. Add to cart and the magic happens!',
    customization_title: 'Make your jersey unique ✍️',
    customization_subtitle: 'You can request customization with the same official font as the players directly in the product options.',
    customization_item1: 'Name + Number',
    customization_item2: 'League Patches',
    emotional_title: 'Because being a fan knows no distance 🇧🇷',
    emotional_text: 'The longing for your country and the passion for football live in the same drawer. We deliver professional player quality directly to your door in Canada.',
    social_proof_title: 'Voice of the Stands 🗣️',
    social_proof_subtitle: 'Since 2022, connecting Brazilians across Canada with their favorite mantles.',
    social_proof_client_since: 'Customer since',
    social_proof_swipe: 'Swipe to read more →',
    faq_title: 'Quick FAQ',
    faq_q1: 'Do you deliver across Canada?',
    faq_a1: 'Yes, we ship to all provinces and cities in Canada with tracking.',
    faq_q2: 'What is the delivery time?',
    faq_a2: 'Between 10 and 20 business days, depending on your region.',
    faq_q3: 'How to choose the size?',
    faq_a3: 'Use your normal size or ask to see the measurement table on WhatsApp. For a loose style (streetwear), choose one size up.',
    faq_q4: 'Is the payment secure?',
    faq_a4: '100% Secure through protected gateways, or we accept e-Transfer via Interac.',
    cta_security: '100% Shielded Site',
    cta_title: 'Guarantee your jersey before it sells out!',
    cta_btn: 'View Catalog',
    footer_about: 'Your connection to football, wherever you are. Specialized in football jerseys for Brazilians in Canada.',
    footer_links: 'Quick Links',
    footer_how_to_buy: 'How to Buy',
    footer_about_us: 'About Us',
    footer_payment: 'Payment',
    footer_payment_desc: 'We accept Interac e-Transfer, simple, fast and secure.',
    footer_rights: 'All rights reserved.',
    footer_dev: 'Developed by',
    footer_affiliates: 'Affiliate Program',
    footer_contact: 'Contact Us',
    nav_selecoes: 'National Teams',
    nav_lancamentos: 'New Arrivals',
    footer_catalog: 'Catalog',
    about_title: 'Our Story ⚽',
    about_text1: 'Born in Coquitlam, BC in 2022, iFooty emerged from a simple but powerful desire: to bring Brazilians in Canada closer to their roots. We know that a football jersey is not just a piece of clothing, it is a second skin that carries memories and belonging.',
    about_text2: 'After winning over our community in British Columbia, we have now arrived in Calgary, specialized in delivering high-quality official fan jerseys so that every shout of "goal" carries the pride of your heart team.',
    success_support_wa_msg: 'Hi! I just placed an order on iFooty and have some questions. 😊',
    checkout_summary_footer_note: 'You will send an order summary to our support. Payment will only be made after we confirm the order details with you. Payment via Interac e-Transfer!',
    // Home Extras
    home_numbers_title: 'Our numbers',
    home_empty_team: 'No jerseys found for this team at the moment. Try another club!',
    home_comes_out_to: 'Comes out to',
    home_only: 'Only',
    home_savings: 'You save',
    home_view_all: 'View all',
    home_best_options: 'The best options in',
    home_comming_soon: 'New arrivals soon for',
    // Product Extras
    product_loading: 'Loading product...',
    product_not_found: 'Product not found.',
    product_free_shipping: 'Free shipping to all Canada',
    product_volume_promo: '🚀 Volume discount: buy 2 or more jerseys and save! 🚀',
    product_reviews_count: 'Reviews',
    product_questions_count: 'Questions',
    product_size_guide: 'SIZE GUIDE',
    product_plus_size_alert: '* Plus Size selected',
    product_custom_name: 'NAME',
    product_custom_number: 'NUMBER',
    product_wholesale_header: '🔥 Official Size Guide',
    product_table_length: 'LENGTH',
    product_table_width: 'WIDTH',
    product_table_height: 'SUGGESTED HEIGHT',
    product_table_weight: 'SUGGESTED WEIGHT',
    product_social_title: 'What our customers say',
    product_social_subtitle_part1: "We are already ",
    product_social_subtitle_part2: ' wearing the passion in Canada! 🍁',
    product_faq_title: 'Frequently Asked Questions',
    product_faq_q1: 'Are the jerseys original?',
    product_faq_a1: 'These are high-quality player-edition jerseys, with identical premium finish.',
    product_faq_q2: 'Do you deliver across Canada?',
    product_faq_a2: 'Yes, we ship to all provinces and cities in Canada with tracking.',
    product_faq_q3: 'Is payment secure?',
    product_faq_a3: '100% Secure. We use certified gateways and preferentially operate e-Transfer for Canadian residents.',
    product_cta_secure: 'Secure Purchase',
    product_cta_guarantee: 'We guarantee product quality and full customer support via WhatsApp.',
    // Success
    success_title: 'Order Received! ⚽',
    success_subtitle: 'Your jersey is being prepared.',
    success_message: "We've sent a detailed summary to your email. Please check your inbox (and spam folder).",
    success_whatsapp_error: "Couldn't open WhatsApp?",
    success_whatsapp_btn: 'Send Summary Manually',
    success_support_btn: 'Chat with our team',
    success_home_btn: 'Back to Shop',
    // Auth
    auth_title: 'Fan Zone',
    auth_subtitle: 'Sign in to track your orders and complete your purchases at iFooty.',
    auth_loading: 'Waiting for Google...',
    auth_google_btn: 'Sign in with Google',
    auth_terms: 'By signing in, you agree to our privacy terms and international shipping policy.',
    auth_error_default: 'Login failed. Please try again.',
    // Profile
    profile_loading: 'Loading profile...',
    profile_tab_orders: 'My Orders',
    profile_tab_feedback: 'My Feedback',
    profile_logout: 'Sign Out',
    profile_orders_loading: 'Fetching your jerseys...',
    profile_no_orders_title: 'No orders found.',
    profile_no_orders_text: "You haven't placed any orders yet. Browse our collections to find yours!",
    profile_explore_btn: 'Explore Collection',
    profile_status_pending: '🟡 Awaiting Confirmation',
    profile_status_processing: '🔵 Preparing Shipment',
    profile_status_shipped: '🟢 Shipped',
    profile_status_completed: '✅ Delivered',
    profile_status_cancelled: '❌ Cancelled',
    profile_delivery: 'Shipping to:',
    profile_order_prefix: 'Order #',
    profile_feedback_title: 'What did you think of iFooty? 🗣️',
    profile_feedback_subtitle: 'Your review helps us grow and helps other Brazilians in Canada!',
    profile_feedback_rating_label: 'Rate your experience:',
    profile_feedback_location_label: 'Where did you buy from? (City, Province)',
    profile_feedback_location_placeholder: 'e.g. Toronto, ON',
    profile_feedback_comment_label: 'Your comment:',
    profile_feedback_comment_placeholder: 'Share your experience with the product, delivery and service...',
    profile_feedback_submitting: 'Submitting...',
    profile_feedback_submit: 'Publish Review',
    profile_feedback_my_reviews: 'My Submitted Reviews',
    profile_feedback_loading: 'Loading history...',
    profile_feedback_empty: "You haven't submitted any reviews yet.",
    profile_feedback_approved: 'Published',
    profile_feedback_pending_review: 'Under Review',
    profile_feedback_sent_on: 'Sent on:',
    profile_feedback_error: 'Error submitting review: ',
    profile_feedback_success: 'Review submitted! It will appear on the site after moderation.',
    // Category
    category_home: 'Home',
    category_items_found: 'items found',
    category_filters: 'Filters',
    category_filter_fan: 'Fan Edition',
    category_filter_player: 'Player Edition',
    category_filter_retro: 'Retro',
    category_jersey_version: 'Jersey Version',
    category_clear_filters: 'Clear filters',
    category_filter_btn: 'Filter Products',
    category_showing: 'Showing',
    category_of: 'of',
    category_products: 'products',
    category_filtered_by: 'filtered by:',
    category_sort_by: 'Sort by:',
    category_sort_popular: 'Most Popular',
    category_sort_price_asc: 'Lowest Price',
    category_sort_price_desc: 'Highest Price',
    category_loading: 'Searching for jerseys...',
    category_empty_title: 'Empty locker room!',
    category_empty_text: 'No jerseys found for this category at the moment.',
    // Checkout
    checkout_login_title: 'Hold on, striker!',
    checkout_login_text: 'You need to sign in to reserve your jerseys.',
    checkout_login_btn: 'Sign In / Register',
    checkout_delivery_title: 'Delivery in Canada',
    checkout_summary_title: 'Summary',
    checkout_subtotal: 'Subtotal',
    checkout_discount: 'Volume Discount',
    checkout_back_btn: 'Back',
    checkout_attention: 'Attention',
    checkout_attention_btn: 'Got it!',
    checkout_select_province: 'Select...',
    checkout_name: 'Full Name *',
    checkout_street: 'Street Address *',
    checkout_apt: 'Apt/Suite',
    checkout_city: 'City *',
    checkout_province: 'Province *',
    checkout_postal: 'Postal Code *',
    checkout_social: 'Instagram or WhatsApp (Optional)',
    checkout_social_placeholder: 'e.g. @yourinsta or Phone',
    checkout_save_address: 'Save this address for future purchases',
    checkout_validation_error: 'Please fill in all required address fields.',
    checkout_processing: 'Processing...',
    checkout_confirm_btn: 'Place Order (WhatsApp)',
    checkout_cart_empty_title: 'Your cart is empty.',
    checkout_back_shopping: 'Back to Shopping',
    checkout_wa_order_title: '*NEW ORDER - iFOOTY*',
    checkout_wa_customer: '*CUSTOMER:*',
    checkout_wa_shipping: '*SHIPPING ADDRESS:*',
    checkout_wa_items: '*ORDER ITEMS:*',
    checkout_wa_total: '*TOTAL:*',
    checkout_wa_footer: 'I await the instructions for Interac e-Transfer! 🇨🇦',
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(localStorage.getItem('preferredLanguage') || 'pt');

  useEffect(() => {
    localStorage.setItem('preferredLanguage', language);
  }, [language]);

  const t = (key) => {
    return translations[language][key] || key;
  };

  const translateProductDisplay = (name) => {
    if (language === 'pt') return name;

    let translated = name;
    // Map of common Portuguese football terms to English
    const mapping = {
      'Camisa ': '',
      'Titular': 'Home Jersey',
      'Reserva': 'Away Jersey',
      'Terceira': 'Third Jersey',
      'Goleiro': 'Goalkeeper',
      'Treino': 'Training',
      'Infantil': 'Kids',
      'Feminina': 'Womens',
      'Jogador': 'Player Edition',
      'Torcedor': 'Fan Edition',
      'Fã': 'Fan Edition'
    };

    Object.entries(mapping).forEach(([pt, en]) => {
      const regex = new RegExp(pt, 'gi');
      translated = translated.replace(regex, en);
    });

    return translated.trim();
  };

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'pt' ? 'en' : 'pt');
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t, translateProductDisplay }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
